import {brand,animateBrand} from './brand.js';
import {esc,money,icon,productCard,categoriesMarkup,safeImage} from './commerce-ui.js';
const root=document.querySelector('#shop'),modal=document.querySelector('#shop-modal');
const secret=location.hash.slice(1).split('?')[0];
let info=null,products=new Map(),basket=new Map(),view='home',category='',query='',offset=0,sort='',replenish=false,busy=false,requestId=crypto.randomUUID(),quote=null,orderHistory=[],loadVersion=0;
const cartKey='surtiva.basket.'+secret.slice(0,16);
try{basket=new Map(JSON.parse(sessionStorage.getItem(cartKey)||'[]'));}catch{}
async function api(operation,payload={}){const response=await fetch('/api/commercial/portal',{method:'POST',credentials:'omit',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:secret,operation,payload}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error(response.status===403?'Este enlace ya no está disponible. Pide uno nuevo a tu vendedor.':data.error||'No se pudo completar. Intenta nuevamente.');return data;}
function notice(message){const n=document.querySelector('#shop-notice');n.textContent=message;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),4000);}
function save(){quote=null;requestId=crypto.randomUUID();try{sessionStorage.setItem(cartKey,JSON.stringify([...basket]));}catch{} updateCart();}
function header(){return `<header class="shop-header"><div class="shop-top"><button data-shop="home" aria-label="Inicio">${brand}</button><span class="shop-person">${esc(info?.name||'Tu negocio')}</span><button class="icon-button" data-shop="cart" aria-label="Ver mi pedido">${icon('bag')}<b class="cart-count">${basket.size||''}</b></button></div><label class="shop-search">${icon('search')}<input id="shop-search" type="search" placeholder="¿Qué necesitas surtir hoy?" value="${esc(query)}" autocomplete="off"><button data-shop="search" aria-label="Buscar productos">${icon('arrow')}</button></label></header>`;}
function nav(){return `<nav class="shop-nav" aria-label="Navegación del catálogo">${[['home','home','Inicio'],['catalog','grid','Catálogo'],['orders','bag','Mis pedidos'],['account','person','Mi negocio']].map(([v,i,label])=>`<button data-shop="${v}" ${view===v?'aria-current="page"':''}>${icon(i)}${label}</button>`).join('')}</nav><button class="shop-cart-floating" data-shop="cart" ${basket.size?'':'hidden'}>${icon('bag')}<span>Mi pedido · ${[...basket.values()].reduce((n,p)=>n+p.quantity,0)} unidades</span>${icon('arrow')}</button>`;}
function layout(content){root.innerHTML=header()+`<main class="shop-main">${content}</main>`+nav();}
function updateCart(){const b=document.querySelector('.shop-cart-floating');if(b){b.hidden=!basket.size;b.querySelector('span').textContent='Mi pedido · '+[...basket.values()].reduce((n,p)=>n+p.quantity,0)+' unidades';}document.querySelectorAll('.cart-count').forEach(n=>n.textContent=basket.size||'');}
function renderGrid(list){return `<div class="shop-products">${list.map(p=>productCard(p,basket.get(p.id)?.quantity)).join('')}</div>`;}
function sheet(title,content){modal.innerHTML=`<header><h2>${esc(title)}</h2><button class="icon-button" data-shop="close" aria-label="Cerrar">${icon('close')}</button></header><div class="sheet-body">${content}</div><p class="sheet-feedback" role="status"></p>`;if(!modal.open)modal.showModal();}
async function loadCatalog(append=false){
 const version=++loadVersion;busy=true;
 try{
 const data=await api('catalog',{query,category,offset,sort,replenish,personalized:view==='home'});if(version!==loadVersion)return;info=data;data.products.forEach(p=>products.set(p.id,p));
 if(!append){
 if(view==='home'){
  const photo=data.products.find(p=>/hogar|juguet|belleza/i.test(p.category))||data.products[0];
  layout(`<section class="shop-hero"><div><span>HOLA, ${esc(data.name.toUpperCase())}</span><h1>Más surtido.<br>Más posibilidades.</h1><p>Encuentra lo que tu negocio necesita, a tu ritmo.</p><button class="shop-primary" data-shop="catalog">Explorar catálogo ${icon('arrow')}</button></div>${photo?`<button class="hero-product" data-shop="detail" data-id="${photo.id}" aria-label="Ver ${esc(photo.title)}"><img src="${safeImage(photo.image)}" alt="${esc(photo.title)}"><span>Descubre tu próximo producto ${icon('arrow')}</span></button>`:''}</section><section class="shop-section"><div class="section-heading"><h2>¿Qué vendes en tu negocio?</h2><button data-shop="account">Personalizar ${icon('arrow')}</button></div><div class="category-deck">${categoriesMarkup(data.categories)}</div></section>${data.interests.length?`<section class="interest-row"><span>Tu selección</span>${data.interests.map(c=>`<button data-shop="category" data-category="${esc(c)}">${esc(c)} ${icon('arrow')}</button>`).join('')}</section>`:''}<section class="shop-section"><div class="section-heading"><h2>${data.interests.length?'Según tus categorías':'Explora tu surtido'}</h2><button data-shop="catalog">Ver todo ${icon('arrow')}</button></div>${renderGrid(data.products.slice(0,8))}</section><aside class="shop-banner"><b>Más surtido, más negocio.</b><span>Elige. Prepara tu pedido. Sigue comprando.</span></aside>`);
  if(data.preparedItems?.length&&!basket.size&&!sessionStorage.getItem(cartKey)){data.preparedItems.forEach(item=>basket.set(item.productId,{id:item.productId,title:'Producto seleccionado',quantity:item.quantity}));save();notice('Tu vendedor dejó una selección preparada. Puedes revisarla y ajustarla.');}
 }else{
  layout(`<section class="shop-section"><div class="section-heading"><h1>${esc(replenish?'Reponer mi negocio':category||'Todo el catálogo')}</h1><button data-shop="filters">Filtrar ${icon('grid')}</button></div><div class="category-chips"><button data-shop="all" ${!category?'aria-pressed="true"':''}>Todo</button>${data.categories.map(c=>`<button data-shop="category" data-category="${esc(c.name)}" ${category===c.name?'aria-pressed="true"':''}>${esc(c.name)}</button>`).join('')}</div><div id="shop-results">${data.products.length?renderGrid(data.products):'<div class="shop-empty"><h2>No encontramos productos</h2><p>Prueba otra búsqueda o explora todas las categorías.</p><button class="shop-primary" data-shop="all">Ver todo el catálogo</button></div>'}</div><button class="shop-secondary load-more" data-shop="more" ${data.hasMore?'':'hidden'}>Mostrar más productos</button></section>`);
 }
 }else{document.querySelector('#shop-results .shop-products')?.insertAdjacentHTML('beforeend',data.products.map(p=>productCard(p,basket.get(p.id)?.quantity)).join(''));document.querySelector('[data-shop=more]').hidden=!data.hasMore;}
 }catch(e){if(!info)root.innerHTML=`<main class="shop-opening">${brand}<h1>No pudimos abrir tu catálogo</h1><p>${esc(e.message)}</p><button class="shop-primary" data-shop="retry">Reintentar</button></main>`;else notice(e.message);}finally{busy=false;}
}
async function go(next){view=next;offset=0;modal.close();window.scrollTo(0,0);if(['home','catalog'].includes(view)){if(view==='home'){category='';query='';replenish=false;}await loadCatalog();}else if(view==='orders')await ordersPage();else accountPage();}
function accountPage(){layout(`<section class="shop-section account-page"><span class="overline">TU NEGOCIO</span><h1>${esc(info.name)}</h1><p>Elige las categorías que quieres tener a mano.</p><form id="preferences"><div class="interest-options">${info.categories.map(c=>`<label><input type="checkbox" name="interest" value="${esc(c.name)}" ${info.interests.includes(c.name)?'checked':''}><span>${esc(c.name)}</span></label>`).join('')}</div><button class="shop-primary">Guardar mi selección</button></form><aside class="shop-note"><h2>Tu catálogo, siempre a mano</h2><p>Guarda este enlace en tus favoritos. Es privado para tu negocio: desde aquí puedes consultar productos y enviar pedidos sin contraseña.</p></aside>${sessionStorage.getItem('surtiva.handoff')?'<a class="shop-secondary" href="/#inicio">Volver al vendedor</a>':''}</section>`);}
async function ordersPage(){const data=await api('orders');orderHistory=data.orders;layout(`<section class="shop-section"><div class="section-heading"><h1>Mis pedidos</h1><button data-shop="replenish">Reponer ${icon('refresh')}</button></div>${data.orders.map(o=>`<article class="merchant-order"><header><b>${esc(o.number)}</b><span>${esc(({recibido:'Recibido',preparando:'En preparación',despachado:'En camino',entregado:'Entregado',aprobacion:'Por aprobar',cancelado:'Cancelado',rechazado:'Rechazado'})[o.status]||o.status)}</span></header><p>${new Date(o.created_at).toLocaleDateString('es-CO')} · ${o.items?.length||0} referencias</p><h2>${money(o.total)}</h2><details><summary>Ver productos</summary>${(o.items||[]).map(i=>`<p>${i.quantity} × ${esc(i.title)} · ${money(i.unitPrice)}</p>`).join('')}</details><button class="shop-secondary" data-shop="repeat" data-id="${o.id}">Preparar de nuevo ${icon('refresh')}</button></article>`).join('')||`<div class="shop-empty">${icon('bag')}<h2>Tu primer pedido empieza aquí</h2><p>Elige productos y cantidades. Tu vendedor recibirá el pedido para coordinar la entrega.</p><button class="shop-primary" data-shop="catalog">Encontrar productos</button></div>`}</section>`);}
function cartSheet(){sheet('Mi pedido',basket.size?`<div class="basket-lines">${[...basket.values()].map(p=>`<article><div><b>${esc(products.get(p.id)?.title||p.title)}</b><button data-shop="remove" data-id="${p.id}">Quitar</button></div><label>Cantidad<input type="number" inputmode="numeric" min="1" max="9999" step="1" value="${p.quantity}" data-quantity="${p.id}" aria-label="Cantidad de ${esc(p.title)}"></label></article>`).join('')}</div><p class="shop-note">Calculamos el precio correspondiente a tus cantidades antes de enviar. La entrega se coordina con tu vendedor.</p><button class="shop-primary full" data-shop="quote">Revisar precios y total ${icon('arrow')}</button>`:'<div class="shop-empty"><h3>Elige tu primer producto</h3><p>Tu selección aparecerá aquí.</p><button class="shop-primary" data-shop="close">Seguir explorando</button></div>');}
async function quoteSheet(){quote=await api('quote',{items:[...basket.values()].map(p=>({productId:p.id,quantity:p.quantity}))});sheet('Revisa y envía',`<div class="quote-lines">${quote.items.map(i=>`<article><div><b>${esc(i.title)}</b><small>${i.quantity} × ${money(i.unitPrice)} por unidad</small></div><strong>${money(i.unitPrice*i.quantity)}</strong></article>`).join('')}</div><div class="quote-total"><span>Total del pedido</span><b>${money(quote.total)}</b></div><p class="shop-note">Productos cotizados por 10 minutos. Existencias, entrega y cualquier costo de envío se confirman con tu vendedor antes de despachar. No se realiza un cobro en línea.</p><button class="shop-primary full" data-shop="send">Enviar pedido ${icon('check')}</button><button class="shop-secondary full" data-shop="cart">Cambiar cantidades</button>`);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-shop]');if(!b)return;const action=b.dataset.shop,id=b.dataset.id;b.disabled=true;try{
 if(['home','catalog','orders','account'].includes(action))await go(action);
 if(action==='close')modal.close();if(action==='retry')await loadCatalog();
 if(action==='category'){category=b.dataset.category;query='';replenish=false;await go('catalog');}
 if(action==='all'){category='';query='';replenish=false;await go('catalog');}
 if(action==='search'){query=document.querySelector('#shop-search').value;await go('catalog');}
 if(action==='replenish'){replenish=true;category='';query='';await go('catalog');}
 if(action==='more'&&!busy){offset+=24;await loadCatalog(true);}
 if(action==='filters')sheet('Encuentra tu surtido',`<form id="shop-filters"><label>Categoría<select name="category"><option value="">Todas</option>${info.categories.map(c=>`<option ${category===c.name?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Ordenar<select name="sort"><option value="">Nombre</option><option value="price" ${sort==='price'?'selected':''}>Menor precio</option></select></label><button class="shop-primary">Ver productos</button></form>`);
 if(action==='add'){const p=products.get(id);if(basket.size>=100&&!basket.has(id))throw Error('Puedes incluir hasta 100 referencias por pedido.');basket.set(id,{id,title:p.title,quantity:(basket.get(id)?.quantity||0)+1});save();notice('Agregado a tu pedido');b.innerHTML=icon('check')+'Agregado · '+basket.get(id).quantity;}
 if(action==='detail'){const p=products.get(id);sheet(p.title,`<img class="detail-photo" src="${safeImage(p.image)}" alt="${esc(p.title)}"><small>${esc(p.category)} · Ref. ${esc(p.sku)}</small><h2>${money(p.price)} <small>/ unidad</small></h2><p>${esc(p.availability)} · El precio se ajusta a la cantidad al revisar el pedido.</p><button class="shop-primary full" data-shop="add" data-id="${id}" ${p.availability==='Agotado'?'disabled':''}>${icon('bag')} Agregar al pedido</button>`);}
 if(action==='cart')cartSheet();if(action==='remove'){basket.delete(id);save();cartSheet();}
 if(action==='quote')await quoteSheet();
 if(action==='send'){if(!quote)throw Error('Revisa primero tu pedido.');const order=await api('order',{quoteId:quote.id,requestKey:requestId});basket.clear();save();sheet('Pedido recibido',`<div class="order-success">${icon('check')}<h2>¡Tu pedido está en marcha!</h2><p>${esc(order.number)}</p><b>${money(order.total)}</b><p>Tu vendedor ya puede verlo y coordinar contigo la entrega.</p><button class="shop-primary" data-shop="orders">Ver mi pedido</button></div>`);}
 if(action==='repeat'){const order=orderHistory.find(o=>o.id===id);if(basket.size&&!confirm('Se reemplazará tu selección actual por este pedido. ¿Continuar?'))return;basket=new Map(order.items.map(i=>[i.productId,{id:i.productId,title:i.title,quantity:i.quantity}]));save();cartSheet();notice('Revisaremos los precios y la disponibilidad actuales.');}
 }catch(err){if(modal.open)modal.querySelector('.sheet-feedback').textContent=err.message;else notice(err.message);}finally{b.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.dataset.quantity){const quantity=Number(e.target.value);if(!Number.isInteger(quantity)||quantity<1||quantity>9999){e.target.reportValidity();return;}basket.get(e.target.dataset.quantity).quantity=quantity;save();}});
document.addEventListener('keydown',e=>{if(e.target.id==='shop-search'&&e.key==='Enter'){query=e.target.value;go('catalog').catch(err=>notice(err.message));}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=e.submitter;button.disabled=true;try{if(form.id==='preferences'){const interests=new FormData(form).getAll('interest');await api('preferences',{interests});info.interests=interests;notice('Tu selección está guardada');await go('home');}if(form.id==='shop-filters'){const values=Object.fromEntries(new FormData(form));category=values.category;sort=values.sort;await go('catalog');}}catch(err){notice(err.message);}finally{button.disabled=false;}});
animateBrand();if(/^[a-f0-9]{96}$/.test(secret))loadCatalog();else root.innerHTML=`<main class="shop-opening">${brand}<h1>Tu catálogo comienza con una invitación</h1><p>Abre el enlace o escanea el QR que te compartió tu vendedor.</p></main>`;
