import {photoAttributes} from './product-photos.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value||0);
const paths={home:'m3 10 9-7 9 7v10H3Z M9 20v-7h6v7',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',bag:'M5 7h14l1 14H4Z M8 8V6a4 4 0 0 1 8 0v2',grid:'M3 3h7v7H3Z M14 3h7v7h-7Z M3 14h7v7H3Z M14 14h7v7h-7Z',person:'M4 21a8 8 0 0 1 16 0 M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',arrow:'M4 12h16 M14 6l6 6-6 6',heart:'M12 21 3 12C-3 3 9-1 12 6c3-7 15-3 9 6Z',box:'m3 7 9-5 9 5v10l-9 5-9-5Z M3 7l9 5 9-5 M12 12v10',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',check:'m5 12 4 4L19 6',close:'m6 6 12 12 M6 18 18 6',share:'M12 16V2 M6 8l6-6 6 6 M4 13v8h16v-8',refresh:'M20 7A9 9 0 1 0 21 15 M20 2v6h-6'};
export const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.box}"/></svg>`;
export function categoryStyle(name){return /juguet/i.test(name)?'toys':/belleza|cosm|fantas/i.test(name)?'beauty':/hogar|cacharro/i.test(name)?'home':/escolar/i.test(name)?'school':'other';}
export const safeImage=value=>/^\/?assets\/productos\/[a-zA-Z0-9_.-]+$/.test(value||'')?'/'+value.replace(/^\//,''):'/brand/symbol-original.png';
export function productCard(p,quantity=0){return `<article class="shop-product"><button class="shop-photo" data-shop="detail" data-id="${p.id}" aria-label="Ver ${esc(p.title)}"><img src="${safeImage(p.image)}" ${photoAttributes(p.image)} alt="${esc(p.title)}" width="384" height="384" loading="lazy" decoding="async" data-product-image></button><div class="shop-product-body"><small>${esc(p.category)}</small><button class="product-title" data-shop="detail" data-id="${p.id}">${esc(p.title)}</button><div class="shop-price">${money(p.price)} <span>/ ${esc(p.presentation||'unidad')}</span></div><span class="availability">${esc(p.availability||'Por confirmar')}</span><button class="add-product" data-shop="add" data-id="${p.id}" ${p.availability==='Agotado'?'disabled':''}>${icon('bag')}${quantity?`Agregar · ${quantity} en pedido`:'Agregar al pedido'}</button></div></article>`;}
export function categoriesMarkup(categories){return categories.map(c=>`<button class="category-tile ${categoryStyle(c.name)}" data-shop="category" data-category="${esc(c.name)}"><span>${icon(/juguet/i.test(c.name)?'star':/belleza|fantas/i.test(c.name)?'heart':/hogar/i.test(c.name)?'home':'box')}</span><b>${esc(c.name)}</b><small>${c.count} productos</small></button>`).join('');}
