import {brand} from './brand.js';
import {esc,icon,safeImage,categoryStyle} from './commerce-ui.js';
import {photoAttributes} from './product-photos.js';
import {orderNext,orderStatus} from './order-ui.js';

const number=value=>Number(value||0).toLocaleString('es-CO');
export const distributorTools=[
 {id:'clientes',name:'Clientes y comercios',icon:'person',color:'beauty',permission:'customers.read',description:'Cada comercio, sus contactos y su próxima visita.',detail:'Consulta tus clientes, registra visitas y comparte el catálogo con cada negocio.'},
 {id:'vendedores',name:'Equipo de ventas',icon:'star',color:'toys',permission:'team.read',description:'Un equipo conectado con tus productos.',detail:'Invita vendedores y organiza quién atiende a cada cliente.'},
 {id:'seguimiento',name:'Seguimientos',icon:'arrow',color:'home',permission:'followups.manage',description:'La próxima conversación, en el momento oportuno.',detail:'Revisa notas y fechas de contacto para dar continuidad a tus ventas.'},
 {id:'cartera',name:'Cartera',icon:'bag',color:'various',permission:'receivables.read',description:'Tus documentos y saldos, a la vista.',detail:'Consulta las facturas y sus saldos registrados. No procesa pagos.'},
 {id:'proveedores',name:'Proveedores',icon:'box',color:'season',permission:'suppliers.read',description:'Tus contactos de abastecimiento, juntos.',detail:'Organiza los proveedores que decidas gestionar desde Surtiva.'},
 {id:'invitaciones',name:'Invitaciones',icon:'share',color:'beauty',permission:'team.read',description:'Una puerta de entrada para tu equipo.',detail:'Consulta las invitaciones y su estado de incorporación.'},
];
export const distributorCore=[['inicio','Inicio','home',null],['catalogo','Catálogo','grid','catalog.read'],['pedidos','Pedidos','bag','orders.read'],['inventario','Existencias','box','inventory.manage']];
export function distributorRoute(page,canRead=()=>true){
 return [...distributorCore,['herramientas','Herramientas','star',null],...distributorTools.map(t=>[t.id,t.name,t.icon,t.permission])].some(([id,,,p])=>id===page&&(!p||canRead(p)))?page:'inicio';
}
export function createDistributorPreferences(storage){
 const valid=values=>Array.isArray(values)?[...new Set(values)].filter(id=>distributorTools.some(t=>t.id===id)):[];
 const key=(user,org)=>'surtiva.distributor.menu.v1:'+user+':'+org;
 const memory=new Map();
 return {
  read(user,org,preview=false){const k=key(user,org)+(preview?':preview':'');if(memory.has(k))return memory.get(k);let values=[];if(!preview)try{values=valid(JSON.parse(storage.getItem(k)||'[]'));}catch{}return values;},
  toggle(user,org,id,preview=false){if(!distributorTools.some(t=>t.id===id))return [];const k=key(user,org)+(preview?':preview':''),current=this.read(user,org,preview),values=current.includes(id)?current.filter(v=>v!==id):[...current,id];memory.set(k,values);if(!preview)try{storage.setItem(k,JSON.stringify(values));}catch{}return values;}
 };
}
const routeLink=([id,label,shape],page)=>`<a href="#${id}" ${page===id?'aria-current="page"':''}>${icon(shape)}<span>${esc(label)}</span>${page===id?'<i aria-hidden="true"></i>':''}</a>`;
export function distributorShell(content,{page,avatar,name='',canRead=()=>true,pins=[]}){
 const core=distributorCore.filter(([,,,p])=>!p||canRead(p));
 const tools=distributorTools.filter(t=>canRead(t.permission)),pinned=tools.filter(t=>pins.includes(t.id));
 const current=[...distributorCore,...distributorTools.map(t=>[t.id,t.name]),['herramientas','Herramientas']].find(([id])=>id===page)?.[1]||'Inicio';
 return `<div class="shell distributor-shell"><aside class="distributor-rail"><a class="distributor-brand" href="#inicio" aria-label="SURTIVA, inicio">${brand}</a><nav aria-label="Operación del distribuidor"><span class="rail-caption">TU ESPACIO</span>${core.map(item=>routeLink(item,page)).join('')}<div class="rail-tools">${routeLink(['herramientas','Herramientas','star'],page)}${pinned.map(t=>routeLink([t.id,t.name,t.icon],page)).join('')}</div></nav><div class="rail-signature"><span class="signature-line"></span><b>Más surtido.<br>Más negocio.</b></div></aside><div class="distributor-body"><header class="distributor-topbar"><a class="distributor-mobile-brand" href="#inicio" aria-label="SURTIVA, inicio">${brand}</a><span class="distributor-context"><b>${esc(name||'Mi organización')}</b><span aria-hidden="true">/</span>${esc(current)}</span><button class="account-avatar" data-action="account" aria-label="Abrir mi perfil">${avatar}</button></header><main class="main" id="contenido"><div class="content">${content}</div></main></div><nav class="distributor-mobile-nav" aria-label="Operación móvil">${core.filter(([id])=>id!=='inventario').map(item=>routeLink(item,page)).join('')}${routeLink(['herramientas','Más','grid'],['inicio','catalogo','pedidos'].includes(page)?page:'herramientas')}</nav></div>`;
}
const categoryLink=(category,extra='')=>`<button class="distributor-collection ${categoryStyle(category.name)} ${extra}" data-action="distributor-category" data-category="${esc(category.name)}"><span class="collection-photo"><img src="${safeImage(category.image)}" ${photoAttributes(category.image,'(max-width: 760px) 80vw, 400px')} alt="" width="700" height="700" loading="lazy" data-product-image></span><span class="collection-label"><b>${esc(category.name)}</b><small>${number(category.count)} referencias</small>${icon('arrow')}</span></button>`;
export function distributorHome(data,catalog,{name='',canRead=()=>true}={}){
 const s=data.summary,o=data.orderSummary;
 const rank=name=>/grande/i.test(name)?0:/belleza/i.test(name)?1:/hogar/i.test(name)?2:3;
 const categories=catalog.categories.filter(c=>c.image).slice().sort((a,b)=>rank(a.name)-rank(b.name)).slice(0,3);
 const first=categories[0],remaining=categories.slice(1);
 const metric=(label,count,detail,tone,shape,href)=>`<a class="distributor-pulse ${tone}" href="#${href}"><span class="pulse-icon">${icon(shape)}</span><span><b>${number(count)}</b><strong>${label}</strong><small>${detail}</small></span>${icon('arrow')}</a>`;
 const featured=first?`<button class="distributor-feature ${categoryStyle(first.name)}" data-action="distributor-category" data-category="${esc(first.name)}"><span class="feature-copy"><small>TU CATÁLOGO EN SURTIVA</small><h2>${esc(first.name)}</h2><span class="feature-count">${number(first.count)} referencias</span><span class="feature-cta">Explorar colección ${icon('arrow')}</span></span><span class="feature-image"><img src="${safeImage(first.image)}" ${photoAttributes(first.image,'(max-width: 760px) 90vw, 650px')} alt="" width="900" height="900" fetchpriority="high" data-product-image></span></button>`:`<div class="distributor-feature empty-feature"><div class="feature-copy"><small>TU CATÁLOGO EN SURTIVA</small><h2>Tu próxima colección empieza aquí.</h2><p>Agrega tu primer producto para mostrarlo a la red.</p><a href="#catalogo" class="feature-cta">Abrir catálogo ${icon('arrow')}</a></div></div>`;
 return `<section class="distributor-home"><div class="distributor-page-heading"><div><span class="distributor-eyebrow">TU NEGOCIO, EN MOVIMIENTO</span><h1>Así va tu operación.</h1></div><button class="distributor-refresh" data-action="distributor-refresh" aria-label="Actualizar operación">${icon('refresh')}<span>Actualizar</span></button></div><div class="distributor-opening">${featured}<div class="distributor-pulses">${metric('Por confirmar',o.availability,'Disponibilidad de pedidos','season','bag','pedidos')}${metric('En preparación',o.preparing,'Pedidos para alistar','home','box','pedidos')}${metric('En camino',o.shipped,'Despachos en curso','beauty','arrow','pedidos')}</div></div><div class="distributor-work-grid"><section class="distributor-order-desk"><header><div><span class="distributor-eyebrow">PRÓXIMO PASO</span><h2>Pedidos que avanzan</h2></div><a href="#pedidos" aria-label="Ver todos los pedidos">${icon('arrow')}</a></header>${data.orders.length?data.orders.slice(0,4).map(order=>`<button class="distributor-order-row" data-action="order" data-id="${esc(order.id)}"><span class="order-row-icon ${orderStatus(order).group}">${icon('bag')}</span><span><b>${esc(order.number)}</b><small>${esc(orderNext(order,name).label)} · ${esc(orderNext(order,name).who)}</small></span><span class="distributor-order-label">${esc(orderStatus(order).label)}</span>${icon('arrow')}</button>`).join(''):'<div class="distributor-quiet"><span>'+icon('bag')+'</span><div><h3>Listo para tu próximo pedido</h3><p>Cuando llegue, podrás confirmar existencias y coordinar su despacho aquí.</p></div></div>'}</section><a class="distributor-stock-card" href="#inventario"><span class="distributor-eyebrow">EXISTENCIAS</span><div class="stock-card-title"><h2>Cada unidad<br>cuenta.</h2>${icon('box')}</div><div class="stock-card-totals"><span><b>${number(s.available)}</b>referencias con stock</span><span><b>${number(s.unknown)}</b>por confirmar</span></div><span class="stock-card-bottom">Revisar cantidades ${icon('arrow')}</span></a></div><div class="distributor-lower-grid"><section class="distributor-more-collections"><header><h2>Más de tu catálogo</h2><span>${number(catalog.catalogTotal??s.products)} referencias</span></header><div class="distributor-collection-grid">${remaining.map(c=>categoryLink(c)).join('')||'<a class="distributor-empty-link" href="#catalogo">Explorar mis productos →</a>'}</div></section><aside class="distributor-discover"><span class="distributor-eyebrow">A TU RITMO</span><h2>Tu espacio puede<br>hacer más.</h2><div class="discover-icons">${distributorTools.filter(t=>canRead(t.permission)).slice(0,3).map(t=>`<a class="${t.color}" href="#${t.id}" aria-label="Explorar ${esc(t.name)}">${icon(t.icon)}</a>`).join('')}</div><p>Clientes, equipo y seguimiento.<br>Elige qué sumar a tu día a día.</p><a href="#herramientas">Explorar herramientas ${icon('arrow')}</a></aside></div></section>`;
}
export function distributorToolsMarkup({canRead=()=>true,pins=[]}={}){
 const mobilePins=distributorTools.filter(t=>pins.includes(t.id)&&canRead(t.permission));
 return `<section class="distributor-tools-page"><header class="distributor-page-heading"><div><span class="distributor-eyebrow">A LA MEDIDA DE TU OPERACIÓN</span><h1>Más posibilidades.<br>A tu ritmo.</h1><p>Explora las herramientas y añade al menú las que quieras tener a mano.</p></div><span class="tools-heading-art" aria-hidden="true">${icon('grid')}</span></header>${mobilePins.length?`<nav class="distributor-pinned-mobile" aria-label="Tus accesos elegidos"><span>A MANO</span><div>${mobilePins.map(t=>`<a class="${t.color}" href="#${t.id}">${icon(t.icon)}${esc(t.name)}</a>`).join('' )}</div></nav>`:''}<a class="distributor-inventory-shortcut" href="#inventario">${icon('box')}<span><b>Existencias</b><small>Consulta y ajusta las cantidades de tu catálogo.</small></span>${icon('arrow')}</a><div class="distributor-tool-grid">${distributorTools.filter(t=>canRead(t.permission)).map(t=>`<article class="distributor-tool ${t.color}"><span class="tool-icon">${icon(t.icon)}</span><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><div class="tool-detail">${esc(t.detail)}</div><footer><a href="#${t.id}">Explorar ${icon('arrow')}</a><button data-action="distributor-pin" data-id="${t.id}" aria-pressed="${pins.includes(t.id)}" aria-label="${pins.includes(t.id)?'Quitar del menú':'Añadir al menú'}: ${esc(t.name)}">${pins.includes(t.id)?icon('check'):'+'}<span>${pins.includes(t.id)?'En tu menú':'Añadir al menú'}</span></button></footer></article>`).join('')}</div><p class="distributor-preference-note">Personalizas los accesos en este navegador. Añadir una herramienta al menú no cambia tu plan ni genera cobros.</p></section>`;
}
