'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const nf=n=>Number(n||0).toLocaleString('es-CO');
const TODAY=new Date('2026-09-14T12:00:00-05:00');
const iso=d=>new Date(d).toISOString();
const dateAgo=n=>iso(TODAY.getTime()-n*86400000);
const datefmt=d=>d?new Date(d).toLocaleDateString('es-CO',{day:'2-digit',month:'short',year:'numeric'}):'—';
const shortdate=d=>d?new Date(d).toLocaleDateString('es-CO',{day:'2-digit',month:'short'}):'—';
const daysSince=d=>Math.max(0,Math.floor((TODAY-new Date(d))/86400000));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const icons={home:'M3 10 12 3l9 7v10H3z M9 20v-7h6v7',box:'M3 7l9-4 9 4v11l-9 4-9-4z M3 7l9 5 9-5 M12 12v10 M7 5l10 5',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75',cart:'M2 3h3l3 12h11l3-9H6 M9 20h.01 M18 20h.01',order:'M6 3h12v18H6z M9 7h6 M9 11h6 M9 15h4',chart:'M3 3v18h18 M7 16v-5 M12 16V7 M17 16V4',wallet:'M3 5h16v14H3z M3 5V3h13v2 M14 10h7v5h-7z',tag:'M2 12l10-10h8v8L10 20z M16 6h.01',arrow:'M5 12h14 M14 7l5 5-5 5',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',check:'M4 12l5 5L20 6',close:'M6 6l12 12 M18 6 6 18',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4',out:'M9 4H4v16h5 M12 12h9 M17 8l4 4-4 4',menu:'M4 6h16 M4 12h16 M4 18h16',pin:'M20 9c0 6-8 12-8 12S4 15 4 9a8 8 0 0 1 16 0 M15 9a3 3 0 1 1-6 0 3 3 0 0 1 6 0',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2',heart:'M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-5 5 8 15 8 15S25 10 20 5z',truck:'M2 5h12v12H2z M14 9h4l4 5v3h-8 M7 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0 M21 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0',edit:'M4 16l12-12 4 4L8 20H4z M14 6l4 4',upload:'M12 16V3 M7 8l5-5 5 5 M4 16v5h16v-5',download:'M12 3v13 M7 11l5 5 5-5 M4 18v3h16v-3',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',shield:'M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6z M8 12l3 3 5-6',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12 M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',spark:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',store:'M3 3h18l1 6H2z M4 9v12h16V9 M9 21v-7h6v7',refresh:'M20 7v5h-5 M4 17v-5h5 M5 7a8 8 0 0 1 13-3l2 3 M4 17l2 3a8 8 0 0 0 13-3',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 10v7 M12 7h.01'};
const icon=(name,extra='')=>`<svg class="ico ${extra}" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.box}"></path></svg>`;
const button=(text,action,id='',style='primary',more='')=>`<button class="btn ${style}" data-a="${action}" data-id="${esc(id)}" ${more}>${text}</button>`;
const empty=(h,p='',ico='box')=>`<div class="empty">${icon(ico)}<h3>${h}</h3><p>${p}</p></div>`;
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
const RAW=window.CATALOG||[];const RAWMAP=Object.fromEntries(RAW.map(p=>[p.code,p]));
const CATORDER=['Juguetería grande','Juguetería económica','Hogar y cacharro','Escolar','Mascotas','Tecnología','Belleza y cosmética','Fantasía y accesorios','Ferretería','Varios'];
const CATNAMES={'Juguetería grande':'Juguetes grandes','Juguetería económica':'Juguetes pequeños','Hogar y cacharro':'Hogar','Fantasía y accesorios':'Accesorios','Belleza y cosmética':'Belleza'};
const catname=c=>CATNAMES[c]||c;
const SEED_CODES=['J-9802M-9','J-RZ023','J-1002A','H-DK-6390','M-DK-5773','T-DK-1698','E-DK-4985','BV-DK-4518','J-6688-1A','H-DK-3860','M-DK-5749','V-DK-5700'];
const NAMES={daniela:'Daniela',jesus:'Jesús Hipinto',amelie:'Variedades Amelie',regalo:'Casa del Regalo',horizonte:'Variedades Horizonte',alex:'Alex Rodríguez',publico:'Sara · compra de prueba'};
const ROLES={daniela:'proveedor',jesus:'vendedor',amelie:'cliente',regalo:'cliente',horizonte:'cliente',alex:'aliado',publico:'publico'};
const STATUSES={aprobacion:['Por aprobar','orange'],recibido:['Recibido','blue'],preparando:['En preparación','orange'],despachado:['En camino','blue'],entregado:['Entregado','green'],rechazado:['Rechazado','red'],cancelado:['Cancelado','red'],listo:['Listo para retirar','green']};
const statusBadge=s=>`<span class="pill ${STATUSES[s]?.[1]||''}">${STATUSES[s]?.[0]||esc(s)}</span>`;
function multiplier(q){return q>=48?1:q>=24?1.03:q>=12?1.08:q>=6?1.13:q>=3?1.18:1.27;}
function seed(){
 const customers=[{id:'amelie',name:'Variedades Amelie',owner:'Amelie',city:'La Dorada',type:'Variedades y regalos',last:dateAgo(8),seller:'jesus',partner:'alex',cadence:21,credit:2000000},{id:'regalo',name:'Casa del Regalo',owner:'Carolina',city:'Doradal',type:'Regalos y hogar',last:dateAgo(24),seller:'jesus',partner:'alex',cadence:21,credit:1500000},{id:'horizonte',name:'Variedades Horizonte',owner:'Mauricio',city:'Puerto Boyacá',type:'Remate y variedades',last:dateAgo(46),seller:'jesus',partner:'alex',cadence:21,credit:1200000}];
 const changes={};SEED_CODES.filter(c=>RAWMAP[c]).forEach((c,i)=>{changes[c]={stock:180+i*24,stockOrigin:'simulado',updatedAt:dateAgo(0),updatedBy:'Daniela'};});
 const calcLines=arr=>arr.filter(([c,q])=>RAWMAP[c]).map(([code,qty])=>({code,qty,title:RAWMAP[code].title,unit:Math.round(RAWMAP[code].base*multiplier(qty)),base:RAWMAP[code].base}));
 const mk=(id,client,items,status,days)=>{const lines=calcLines(items),subtotal=lines.reduce((s,l)=>s+l.qty*l.unit,0);return{id,kind:'b2b',client,seller:'jesus',partner:'alex',supplier:'daniela',lines,subtotal,total:subtotal,discount:0,commission:Math.round(subtotal*.08),status,createdAt:dateAgo(days),updatedAt:dateAgo(days),history:[{time:dateAgo(days),actor:'Jesús Hipinto',text:'Pedido registrado'},...(status!=='aprobacion'?[{time:dateAgo(days),actor:'Daniela',text:STATUSES[status][0]}]:[])]};};
 const orders=[mk('RT-1038','horizonte',[['J-1002A',48],['T-DK-1698',48]],'entregado',46),mk('RT-1039','regalo',[['H-DK-6390',24],['M-DK-5773',48]],'entregado',24),mk('RT-1040','amelie',[['J-RZ023',12],['H-DK-6390',12]],'entregado',8),mk('RT-1042','regalo',[['E-DK-4985',48],['H-DK-3860',12]],'recibido',1),mk('RT-1043','amelie',[['J-9802M-9',12],['M-DK-5773',24]],'preparando',1),mk('RT-1044','amelie',[['J-RZ023',6],['H-DK-6390',12]],'aprobacion',0)];
 const invoices=orders.slice(0,3).map((o,i)=>({id:'FC-'+(2038+i),order:o.id,client:o.client,total:o.total,paid:i===0?o.total:i===1?50000:0,due:dateAgo(i===0?26:i===1?3:-7),issued:o.createdAt,payments:i===1?[{id:'AB-001',amount:50000,status:'validado',date:dateAgo(7),method:'Transferencia de prueba'}]:[]}));
 const retail={};customers.forEach((c,j)=>{retail[c.id]={};SEED_CODES.filter(code=>RAWMAP[code]).forEach((code,i)=>{retail[c.id][code]={qty:Math.max(1,18-i+j*2),price:[49900,54900,7900,8900,3900,4900,3500,14900,34900,17900,12900,7900][i]+j*500,published:true,cost:Math.round(RAWMAP[code].base*1.08)};});});
 return{version:6,customers,changes,custom:[],orders,invoices,retail,cart:{client:'amelie',items:[],discount:0},retailCart:{client:'amelie',items:[]},promos:[],notes:[{id:'N-1',client:'horizonte',text:'Consultar reposición de juguetería y accesorios. Lleva 46 días sin pedido.',date:dateAgo(0),next:'2026-09-14',actor:'Jesús Hipinto'}],tasks:[],notifications:[{id:'NT-1',for:'jesus',title:'Variedades Horizonte necesita seguimiento',body:'46 días sin pedir. Última compra: '+shortdate(dateAgo(46)),target:'clientes',read:false,time:dateAgo(0)},{id:'NT-2',for:'amelie',title:'Tienes un pedido por aprobar',body:'Jesús preparó RT-1044 para tu negocio.',target:'pedidos',read:false,time:dateAgo(0)}],events:[],favorites:[],nextOrder:1045,nextInvoice:2041,imports:[],team:[{name:'Jesús Hipinto',kind:'vendedor',territory:'Magdalena Medio',active:true},{name:'Alex Rodríguez',kind:'aliado',territory:'Red comercial SURTIVA',active:true}]};
}
let db;try{db=JSON.parse((localStorage.getItem('surtiva.demo.v1')||localStorage.getItem('ruta.demo.v6')));if(db?.version!==6)db=seed();}catch{db=seed();}
let user='';try{user=sessionStorage.getItem('surtiva.user.v1')||'';}catch{}
let screen='',sub='',filter='todos',category='Todos',query='',sort='featured',limit=24,customerTab='';let importPreview=null;let activeProduct='';
function save(){try{localStorage.setItem('surtiva.demo.v1',JSON.stringify(db));return true;}catch{toast('No se pudo guardar en este navegador. Exporta una copia de tus pruebas.');return false;}}
function actor(){return NAMES[user]||'Visitante';}function role(){return ROLES[user]||'';}function client(){return role()==='cliente'?user:db.cart.client;}
function customer(id){return db.customers.find(c=>c.id===id);}
function product(code){const p=RAWMAP[code]||db.custom.find(x=>x.code===code);return p?{...p,...db.changes[code]}:null;}
function allProducts(){return[...RAW,...db.custom].map(p=>product(p.code));}
function categories(){return[...CATORDER,...new Set(db.custom.map(p=>p.category).filter(c=>!CATORDER.includes(c)))];}
function photo(p,small=true){if(!p?.image)return'';const path=small?(p.thumb||p.image):p.image;if(window.INLINE_IMAGES)return window.INLINE_IMAGES[p.image]||p.image;return path;}
function media(p,small=true,cl='',lazy=true){return p?.image?`<img class="${cl}" src="${esc(photo(p,small))}" alt="${esc(p.title||p.name)}" ${lazy?'loading="lazy"':''} decoding="async">`:`<div class="product-empty ${cl}">${icon('box')}<small>${p?.sourceUnavailable?'Agotado en catálogo':'Fotografía pendiente'}</small></div>`;}
function promoFor(code){return db.promos.filter(x=>x.active&&x.code===code&&new Date(x.until+'T23:59:59')>=TODAY).sort((a,b)=>b.percent-a.percent)[0];}
function price(code,qty=1){const p=product(code);if(!p)return 0;const promo=promoFor(code);return Math.round(p.base*(1-(promo?.percent||0)/100)*multiplier(qty));}
function reserved(code){return db.orders.filter(o=>o.kind==='b2b'&&o.status==='preparando').reduce((s,o)=>s+o.lines.filter(l=>l.code===code).reduce((a,l)=>a+l.qty,0),0);}
function available(code){const p=product(code);return p?.stock==null?null:Math.max(0,p.stock-reserved(code));}
function unavailable(p){return p.active===false||p.stock===0||(p.stock==null&&p.sourceUnavailable);}
function retailReserved(id,code){return db.orders.filter(o=>o.kind==='retail'&&o.client===id&&['recibido','preparando','listo'].includes(o.status)).reduce((a,o)=>a+o.lines.filter(l=>l.code===code).reduce((b,l)=>b+l.qty,0),0);}
function retailAvailable(id,code){return Math.max(0,(db.retail[id]?.[code]?.qty||0)-retailReserved(id,code));}
function retailTotal(){const c=db.retailCart;return c.items.reduce((s,i)=>s+i.qty*(db.retail[c.client]?.[i.code]?.price||0),0);}
function cartLines(){return db.cart.items.map(i=>{const p=product(i.code);return p?{code:i.code,title:p.title,qty:i.qty,base:p.base,unit:price(i.code,i.qty)}:null;}).filter(Boolean);}
function cartTotals(){const subtotal=cartLines().reduce((s,l)=>s+l.qty*l.unit,0),budget=Math.round(subtotal*.08),discount=Math.min(Math.round(subtotal*db.cart.discount/100),budget);return{subtotal,discount,total:subtotal-discount,commission:budget-discount};}
function scopedOrders(){if(role()==='proveedor')return db.orders.filter(o=>o.kind==='b2b');if(role()==='vendedor')return db.orders.filter(o=>o.seller==='jesus'&&o.kind==='b2b');if(role()==='cliente')return db.orders.filter(o=>o.client===user);if(role()==='aliado')return db.orders.filter(o=>o.partner==='alex'&&o.kind==='b2b');return db.orders.filter(o=>o.kind==='retail'&&o.buyer==='Sara');}
function scopedInvoices(){return role()==='cliente'?db.invoices.filter(i=>i.client===user):db.invoices;}
function balance(i){return Math.max(0,i.total-i.paid);}
function clientDebt(id){return db.invoices.filter(i=>i.client===id).reduce((s,i)=>s+balance(i),0);}
function overdue(i){return balance(i)>0&&new Date(i.due)<TODAY;}
function invoiceState(i){return !balance(i)?'<span class="pill green">Pagada</span>':overdue(i)?'<span class="pill red">Vencida</span>':'<span class="pill orange">Por vencer</span>';}
function notify(to,title,body,target='pedidos'){db.notifications.unshift({id:'NT-'+Date.now()+'-'+Math.random().toString(36).slice(2,5),for:to,title,body,target,read:false,time:iso(new Date())});}
function audit(text){db.events.unshift({id:'EV-'+Date.now(),time:iso(new Date()),actor:actor(),text});}
function logOrder(o,text){const evt={time:iso(new Date()),actor:actor(),text};o.updatedAt=evt.time;o.history.push(evt);audit(o.id+' · '+text);}
function changeRole(id){if(!ROLES[id])return;user=id;try{sessionStorage.setItem('surtiva.user.v1',user);}catch{}query='';category='Todos';filter='todos';limit=24;if(role()==='cliente')switchCartClient(id);go(role()==='vendedor'?'catalogo':role()==='cliente'?'inicio':role()==='publico'?'tienda':'inicio');}
function go(page){if(page==='acceso'){user='';try{sessionStorage.removeItem('surtiva.user.v1');}catch{}}location.hash=page;screen=page;render();window.scrollTo(0,0);}
function openDialog(title,body,foot=''){const d=$('#modal');d.dataset.dirty='0';d.dataset.kind='';d.dataset.retail='0';d.innerHTML=`<div class="dialoghead"><h2>${title}</h2><button class="iconbtn" data-a="close" aria-label="Cerrar">${icon('close')}</button></div><div class="dialogbody">${body}</div>${foot?`<div class="dialogfoot">${foot}</div>`:''}`;if(!d.open)d.showModal();}
function closeDialog(force=false){const d=$('#modal');if(!force&&d.open&&d.dataset.dirty==='1'&&d.querySelector('form')&&!confirm('¿Descartar los cambios sin guardar?'))return false;if(d.open)d.close();d.dataset.dirty='0';activeProduct='';return true;}
function setQty(code,qty,retail=false){qty=Math.max(0,Math.min(99999,Math.floor(Number(qty)||0)));const bucket=retail?db.retailCart:db.cart;const p=product(code);if(!p)return;if(!retail&&unavailable(p)){toast('Esta referencia no está habilitada para pedidos.');return;}if(retail&&qty>retailAvailable(bucket.client,code)){toast('No hay esa cantidad disponible en la tienda.');return;}let row=bucket.items.find(l=>l.code===code);if(!qty)bucket.items=bucket.items.filter(i=>i.code!==code);else if(row)row.qty=qty;else bucket.items.push({code,qty});save();updateCatalogAndCart();}
function add(code,retail=false){const b=retail?db.retailCart:db.cart;setQty(code,(b.items.find(x=>x.code===code)?.qty||0)+1,retail);toast('Agregado al pedido');}
function makeOrder(){const lines=cartLines();if(!lines.length){toast('Agrega al menos un producto.');return;}if(lines.some(l=>unavailable(product(l.code)))){toast('Revisa las referencias agotadas del pedido.');return;}const t=cartTotals(),id='RT-'+db.nextOrder++,cl=client();const o={id,kind:'b2b',client:cl,seller:'jesus',partner:'alex',supplier:'daniela',lines,...t,status:role()==='cliente'?'recibido':'aprobacion',createdAt:iso(new Date()),updatedAt:iso(new Date()),history:[]};logOrder(o,role()==='cliente'?'Pedido enviado por el cliente':'Cotización enviada para aprobación');db.orders.unshift(o);notify(role()==='cliente'?'daniela':cl,'Nuevo pedido '+id,actor()+' registró '+money(t.total));notify('jesus','Seguimiento '+id,customer(cl).name+' · '+money(t.total));db.cart.items=[];db.cart.discount=0;save();closeDialog();go('pedidos');toast('Pedido '+id+' registrado en el entorno de prueba');}
function transition(id,to){const o=db.orders.find(x=>x.id===id);if(!o)return;
 const rules=o.kind==='b2b'?{aprobacion:{cliente:['recibido','rechazado'],vendedor:['cancelado']},recibido:{proveedor:['preparando','cancelado']},preparando:{proveedor:['despachado','cancelado']},despachado:{cliente:['entregado']}}:{recibido:{cliente:['preparando','cancelado']},preparando:{cliente:['listo','cancelado']},listo:{cliente:['entregado']}};
 if(!(rules[o.status]?.[role()]||[]).includes(to)||(role()==='cliente'&&o.client!==user)){toast('Esta acción no está disponible para tu perfil.');return;}
 if(o.kind==='b2b'&&to==='preparando'){
  const failure=o.lines.find(l=>available(l.code)==null||available(l.code)<l.qty);
  if(failure){toast('Confirma existencias suficientes para '+failure.code+' en Inventario.');return;}
 }
 if(o.kind==='b2b'&&to==='despachado'){
  const failure=o.lines.find(l=>product(l.code).stock==null||product(l.code).stock<reserved(l.code));
  if(failure){toast('El inventario cambió. Revisa '+failure.code+' antes de despachar.');return;}
  o.lines.forEach(l=>{db.changes[l.code]={...db.changes[l.code],stock:product(l.code).stock-l.qty};});
  if(!db.invoices.some(i=>i.order===o.id))db.invoices.unshift({id:'FC-'+db.nextInvoice++,order:o.id,client:o.client,total:o.total,paid:0,due:iso(new Date(Date.now()+15*86400000)),issued:iso(new Date()),payments:[]});
 }
 if(o.kind==='b2b'&&to==='entregado'){
  db.retail[o.client]??={};o.lines.forEach(l=>{const prev=db.retail[o.client][l.code]||{qty:0,price:0,published:false};db.retail[o.client][l.code]={...prev,qty:prev.qty+l.qty,cost:l.unit};});customer(o.client).last=iso(new Date());
 }
 if(o.kind==='retail'&&to==='entregado'){
  if(o.lines.some(l=>(db.retail[o.client]?.[l.code]?.qty||0)<l.qty)){toast('No hay existencias suficientes para completar la entrega.');return;}
  o.lines.forEach(l=>db.retail[o.client][l.code].qty-=l.qty);
 }
 o.status=to;logOrder(o,STATUSES[to][0]);if(o.kind==='b2b'){notify(o.client,o.id+' · '+STATUSES[to][0],actor()+' actualizó tu pedido');notify('jesus',o.id+' · '+STATUSES[to][0],customer(o.client).name);if(to==='recibido')notify('daniela','Pedido aprobado '+o.id,customer(o.client).name+' · '+money(o.total));}
 save();closeDialog();render();orderDetail(id);toast('Pedido actualizado: '+STATUSES[to][0]);
}
const NAV={proveedor:[['inicio','Resumen','home'],['inventario','Catálogo e inventario','box'],['pedidos','Pedidos','order'],['ventas','Ventas','chart'],['cartera','Cartera','wallet'],['equipo','Vendedores y alianzas','users'],['promociones','Promociones','tag'],['sincronizar','Actualizar catálogo','refresh']],vendedor:[['inicio','Mi jornada','home'],['catalogo','Catálogo','box'],['clientes','Mis clientes','users'],['pedidos','Pedidos','order'],['seguimiento','Seguimientos','clock'],['comisiones','Comisiones','wallet']],cliente:[['inicio','Mi negocio','home'],['catalogo','Comprar mercancía','box'],['pedidos','Mis pedidos','order'],['cartera','Facturas y pagos','wallet'],['miinventario','Mi inventario','store'],['ventas','Ventas de mi tienda','chart']],aliado:[['inicio','Mi alianza','home'],['clientes','Red de comercios','users'],['pedidos','Pedidos de la red','order'],['ventas','Ventas y territorio','chart'],['equipo','Relaciones comerciales','link']]};
function titleFor(p){return NAV[role()]?.find(n=>n[0]===p)?.[1]||({notificaciones:'Notificaciones',tienda:'Tienda',pedido:'Pedido'}[p]||'Inicio');}
function shell(body){const r=role(),unread=db.notifications.filter(n=>n.for===user&&!n.read).length;return`<div class="shell" id="shell"><aside class="sidebar"><a class="logo" href="#tienda">${wordmark()}</a><div class="workspace"><div class="avatar">${r==='proveedor'?'DK':r==='vendedor'?'JH':r==='aliado'?'AR':actor().split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>${r==='proveedor'?'Dukes · mayorista':r==='vendedor'?'Mi oficina comercial':r==='aliado'?'Mi alianza':esc(actor())}</strong><small>${r==='proveedor'?'Catálogo central':r==='vendedor'?'Magdalena Medio':r==='aliado'?'Socio estratégico':customer(user)?.city||''}</small></div></div><div class="navtitle">MI ESPACIO</div><nav class="navlist">${NAV[r].map(([id,t,i])=>`<a class="navitem ${screen===id?'active':''}" href="#${id}">${icon(i)}<span>${t}</span>${id==='pedidos'?`<span class="count">${scopedOrders().filter(o=>!['entregado','cancelado','rechazado'].includes(o.status)).length}</span>`:''}</a>`).join('')}</nav><div class="sidebarfooter">${button(icon('store')+'Ver tienda pública','shop','','full')}<div class="profile"><span class="avatar">${actor().split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div class="grow"><strong style="font-size:12px">${esc(actor())}</strong><small>${r==='aliado'?'Socio estratégico':r==='proveedor'?'Administradora':r==='vendedor'?'Vendedor':'Negocio afiliado'}</small></div><button data-a="logout" aria-label="Cambiar acceso" title="Cambiar acceso de prueba">${icon('out')}</button></div></div></aside><main class="main"><header class="topbar"><div class="flex"><button class="iconbtn mobilemenu" data-a="menu" aria-label="Abrir menú">${icon('menu')}</button><span class="breadcrumb"><span class="root">Mi espacio &nbsp; / &nbsp; </span><b>${titleFor(screen)}</b></span></div><div class="actions"><span class="testbadge">Entorno de prueba</span><button class="iconbtn" style="position:relative" data-a="notifications" aria-label="Notificaciones">${icon('bell')}${unread?`<span class="badgeDot">${unread}</span>`:''}</button><span class="avatar">${actor().split(' ').map(s=>s[0]).slice(0,2).join('')}</span></div></header><div class="content">${body}</div></main></div>`;}
function accessView(){return accessScreen();}
function pagehead(title,subtitle='',actions=''){return`<div class="pagehead"><div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div><div class="row">${actions}</div></div>`;}
function stats(items){return`<div class="stats">${items.map(([v,l,d,i],idx)=>`<div class="stat ${idx===0?'primary':''}"><small>${l}${icon(i||'chart')}</small><b>${v}</b><em>${d||'&nbsp;'}</em></div>`).join('')}</div>`;}
function taskRow(title,desc,action,id='',text='Ver',ico='clock'){return`<div class="task">${icon(ico)}<div class="grow"><h3>${title}</h3><small>${desc}</small></div>${button(text,action,id,'light small')}</div>`;}
function dashboardView(){const r=role(),orders=scopedOrders(),b2b=orders.filter(o=>o.kind==='b2b'),open=b2b.filter(o=>!['entregado','cancelado','rechazado'].includes(o.status)),inv=scopedInvoices(),debt=inv.reduce((s,i)=>s+balance(i),0),delivered=b2b.filter(o=>o.status==='entregado').reduce((s,o)=>s+o.total,0);
 if(r==='proveedor')return pagehead('Buenos días, Daniela.','Lunes, 14 de septiembre · tu operación de hoy',button(icon('plus')+'Nuevo producto','newproduct')+button(icon('upload')+'Actualizar existencias','goto','sincronizar','light'))+stats([[money(open.reduce((s,o)=>s+o.total,0)),'Pedidos abiertos',open.length+' pedidos en proceso','order'],[nf(allProducts().length),'Referencias en catálogo',categories().length+' categorías','box'],[money(debt),'Cartera por cobrar',inv.filter(overdue).length+' cuentas vencidas','wallet'],[money(delivered),'Ventas entregadas','Operaciones de prueba','chart']])+`<div class="dashboard"><div><div class="panel"><div class="panelhead"><h2>Necesitan tu atención</h2><span class="pill orange">${open.length} pedidos</span></div>${open.slice(0,4).map(o=>taskRow(o.id+' · '+customer(o.client).name,STATUSES[o.status][0]+' · '+money(o.total),'order',o.id,'Abrir','order')).join('')}</div><div class="sectionhead"><h2>Últimos movimientos</h2>${button('Ver ventas','goto','ventas','ghost small')}</div>${compactOrders(b2b.slice(0,5))}</div><div class="stack"><div class="panel pad"><div class="flex between"><h2>Catálogo central</h2>${icon('box')}</div><div class="minirow"><small>Stock confirmado en prueba</small><strong>${allProducts().filter(p=>p.stock!=null).length} referencias</strong></div><div class="minirow"><small>Existencias por confirmar</small><strong>${allProducts().filter(p=>p.stock==null).length}</strong></div><div class="minirow"><small>Conexión a tu software</small><span class="pill orange">Sin conectar</span></div><div class="mt">${button('Importar archivo de existencias','goto','sincronizar','light full')}</div></div><div class="panel"><div class="panelhead"><h2>Tu red comercial</h2>${icon('users')}</div>${db.team.map(t=>`<div class="teamrow"><span class="avatar">${t.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div class="grow"><h3>${esc(t.name)}</h3><small>${esc(t.territory)}</small></div><span class="pill ${t.kind==='aliado'?'blue':'green'}">${t.kind==='aliado'?'Alianza':'Vendedor'}</span></div>`).join('')}</div></div></div>`;
 if(r==='vendedor'){const late=db.customers.filter(c=>daysSince(c.last)>c.cadence),comm=b2b.filter(o=>o.status==='entregado').reduce((s,o)=>s+o.commission,0);return pagehead('Buenos días, Jesús.','Tres negocios en tu ruta. Un siguiente paso para cada uno.',button(icon('plus')+'Nuevo pedido','goto','catalogo'))+stats([[money(open.reduce((s,o)=>s+o.total,0)),'Pedidos en movimiento',open.length+' operaciones activas','order'],[db.customers.length,'Clientes asignados','Magdalena Medio','users'],[late.length,'Seguimientos pendientes','Clientes fuera de frecuencia','clock'],[money(comm),'Comisión proyectada','8 % simulado · no liquidada','wallet']])+`<div class="spotlight"><div><h2>Variedades Horizonte lleva ${daysSince(customer('horizonte').last)} días sin pedir.</h2><p>Última compra ${shortdate(customer('horizonte').last)} · Puerto Boyacá</p></div>${button('Abrir cliente','client','horizonte','primary')}</div><div class="dashboard"><div><div class="panel"><div class="panelhead"><h2>Mis siguientes pasos</h2>${button('Ver todos','goto','seguimiento','ghost small')}</div>${late.map(c=>taskRow(c.name,'Fuera de frecuencia · '+daysSince(c.last)+' días sin pedido','client',c.id,'Atender')).join('')}${b2b.filter(o=>o.status==='aprobacion').map(o=>taskRow('Esperando aprobación · '+o.id,customer(o.client).name+' · '+money(o.total),'order',o.id,'Revisar','order')).join('')}</div><div class="sectionhead"><h2>Pedidos recientes</h2></div>${compactOrders(b2b.slice(0,4))}</div><div class="panel"><div class="panelhead"><h2>Mi agenda</h2>${button('Registrar','note',db.cart.client,'ghost small')}</div>${db.notes.slice(0,5).map(n=>taskRow(customer(n.client)?.name||'',esc(n.text),'client',n.client,'Ver','pin')).join('')}</div></div>`;}
 if(r==='cliente'){const mine=customer(user),ret=orders.filter(o=>o.kind==='retail'&&!['entregado','cancelado'].includes(o.status)),pending=b2b.filter(o=>o.status==='aprobacion');return pagehead('Hola, '+esc(mine.owner)+'.',esc(mine.name)+' · '+esc(mine.city),button(icon('plus')+'Hacer un pedido','goto','catalogo'))+stats([[money(debt),'Pendiente de pago',inv.filter(overdue).length+' facturas vencidas','wallet'],[open.length,'Pedidos de mercancía',pending.length+' por aprobar','order'],[ret.length,'Pedidos de mi tienda','Venta al público','store'],[Object.values(db.retail[user]||{}).filter(i=>i.published&&i.qty>0).length,'Productos publicados','Tu vitrina local','box']])+`<div class="dashboard"><div><div class="panel"><div class="panelhead"><h2>Por revisar</h2>${icon('bell')}</div>${pending.map(o=>taskRow('Pedido preparado por Jesús',o.id+' · '+money(o.total),'order',o.id,'Revisar','order')).join('')}${inv.filter(i=>balance(i)>0).map(i=>taskRow(i.id+' · '+(overdue(i)?'Factura vencida':'Próximo pago'),money(balance(i))+' · vence '+datefmt(i.due),'invoice',i.id,'Ver factura','wallet')).join('')}${ret.map(o=>taskRow('Nueva compra en tu tienda',o.id+' · '+money(o.total),'order',o.id,'Preparar','store')).join('')}</div><div class="sectionhead"><h2>Mis últimos pedidos</h2></div>${compactOrders(b2b.slice(0,4))}</div><div class="stack"><div class="panel pad"><div class="flex"><span class="avatar">JH</span><div><h3>Jesús Hipinto</h3><small>Tu vendedor asignado</small></div></div><div class="divider"></div>${button('Dejar un mensaje','message','jesus','light full')}</div><div class="panel pad"><h2>Mi tienda está abierta.</h2><p class="muted" style="font-size:12px;margin:9px 0 18px">${esc(mine.city)} · ${Object.values(db.retail[user]||{}).filter(x=>x.published).length} referencias publicadas</p>${button('Ver mi vitrina','shop',user,'primary full')}</div></div></div>`;}
 return pagehead('Tu alianza, Alex.','Red comercial SURTIVA · no perteneces a la lista de vendedores',button(icon('store')+'Ver comercios','goto','clientes'))+stats([[money(delivered),'Ventas entregadas','Red vinculada a tu alianza','chart'],[3,'Negocios afiliados','Tres territorios de prueba','store'],[1,'Mayorista vinculado','Dukes · Daniela','box'],[open.length,'Pedidos en movimiento','Operaciones de la red','order']])+`<div class="dashboard"><div><div class="panel"><div class="panelhead"><h2>Territorios</h2>${icon('pin')}</div>${db.customers.map(c=>`<div class="teamrow"><span class="avatar">${c.city[0]}</span><div class="grow"><h3>${c.city}</h3><small>${c.name}</small></div>${button('Ver negocio','client',c.id,'light small')}</div>`).join('')}</div><div class="sectionhead"><h2>Operación de la alianza</h2></div>${compactOrders(open)}</div><div class="panel pad"><span class="pill blue">Socio estratégico</span><h2 style="margin:14px 0">Alex Rodríguez</h2><div class="minirow"><small>Proveedor</small><strong>Daniela · Dukes</strong></div><div class="minirow"><small>Modelo comercial</small><strong>Por acordar</strong></div><div class="minirow"><small>Comisión de vendedor</small><strong>No aplica</strong></div><div class="minirow"><small>Condiciones de alianza</small><span class="pill orange">Pendientes</span></div></div></div>`;}
function compactOrders(orders){return`<div class="panel"><div class="tablewrap"><table class="datatable"><thead><tr><th>Pedido / negocio</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${o.id}</strong><small style="display:block">${customer(o.client)?.name||o.buyer}</small></td><td class="nowrap">${money(o.total)}</td><td>${statusBadge(o.status)}</td><td>${button('Abrir','order',o.id,'ghost small')}</td></tr>`).join('')}</tbody></table></div></div>`;}
function matchingProducts(publicView=false){let list=allProducts();if(publicView){const shopId=db.retailCart.client;list=list.filter(p=>db.retail[shopId]?.[p.code]?.published&&retailAvailable(shopId,p.code)>0);}else if(role()!=='proveedor')list=list.filter(p=>p.active!==false);
 if(category!=='Todos')list=list.filter(p=>p.category===category);
 if(query){const q=norm(query);list=list.filter(p=>norm([p.code,p.name,p.title,p.category].join(' ')).includes(q));}
 if(filter==='favoritos')list=list.filter(p=>db.favorites.includes(p.code));if(filter==='remates')list=list.filter(p=>!!promoFor(p.code));
 if(sort==='asc')list.sort((a,b)=>(publicView?db.retail[db.retailCart.client][a.code].price:a.base)-(publicView?db.retail[db.retailCart.client][b.code].price:b.base));
 else if(sort==='desc')list.sort((a,b)=>(publicView?db.retail[db.retailCart.client][b.code].price:b.base)-(publicView?db.retail[db.retailCart.client][a.code].price:a.base));
 else if(sort==='az')list.sort((a,b)=>a.title.localeCompare(b.title,'es'));
 else list.sort((a,b)=>{const ai=SEED_CODES.indexOf(a.code),bi=SEED_CODES.indexOf(b.code);return(ai<0?10000:ai)-(bi<0?10000:bi);});
 return list;
}
function catControls(){return`<div class="catalogtools"><label class="search">${icon('search')}<input id="q" placeholder="Buscar producto o referencia" value="${esc(query)}" aria-label="Buscar producto"></label><select id="category" aria-label="Categoría"><option value="Todos">Todas las categorías</option>${categories().map(c=>`<option value="${esc(c)}" ${category===c?'selected':''}>${catname(c)}</option>`).join('')}</select><select id="sort" aria-label="Orden"><option value="featured" ${sort==='featured'?'selected':''}>Selección del catálogo</option><option value="asc" ${sort==='asc'?'selected':''}>Menor precio</option><option value="desc" ${sort==='desc'?'selected':''}>Mayor precio</option><option value="az" ${sort==='az'?'selected':''}>Nombre A–Z</option></select></div><div class="categoryline" id="catline">${['Todos',...categories()].map(c=>`<button class="chip ${category===c?'active':''}" data-a="category" data-id="${esc(c)}">${c==='Todos'?'Todos':catname(c)}</button>`).join('')}</div>`;}
function productCard(p,publicView=false){const row=db.cart.items.find(i=>i.code===p.code),q=row?.qty||1,stock=available(p.code),prom=publicView?null:promoFor(p.code);const unit=publicView?db.retail[db.retailCart.client][p.code].price:role()==='proveedor'?p.base:price(p.code,q);const off=!publicView&&unavailable(p);return`<article class="product"><button class="productpic" data-a="detail" data-id="${esc(p.code)}" aria-label="Ver ${esc(p.title)}">${media(p,true)}${off?'<span class="pill red">No disponible</span>':prom?`<span class="pill orange">−${prom.percent}%</span>`:publicView?'<span class="pill">Recoge en tienda</span>':''}</button><div class="productbody">${!publicView?`<span class="sku">${esc(p.code)}</span>`:`<span class="pdetails">${esc(customer(db.retailCart.client).name)}</span>`}<h3>${esc(p.title)}</h3><div class="pricing"><b>${money(unit)}</b>${!publicView?`<small>${role()==='proveedor'?'precio base':'por referencia'}</small>`:''}</div>${!publicView?`<span class="pdetails">${role()==='proveedor'?(p.stock!=null?'Físico: '+nf(p.stock)+' · Reservado: '+reserved(p.code):'Stock por confirmar'):(q>=48?'Escala mayorista aplicada':'Mayorista desde '+money(prom?Math.round(p.base*(1-prom.percent/100)):p.base))}</span>`:''}<div class="foot"><small>${publicView?`${retailAvailable(db.retailCart.client,p.code)} disponibles`:stock!=null?`${stock} para pedido · prueba`:'Existencias por confirmar'}</small>${role()==='proveedor'&&!publicView?`<button class="addbtn" data-a="editproduct" data-id="${esc(p.code)}" aria-label="Editar ${esc(p.code)}">${icon('edit')}</button>`:!publicView&&row?qtyControl(p.code,q):`<button class="addbtn" data-a="${publicView?'retailadd':'add'}" data-id="${esc(p.code)}" aria-label="Agregar ${esc(p.code)}" ${off?'disabled':''}>${icon('plus')}</button>`}</div></div></article>`;}
function qtyControl(code,q,retail=false){return`<div class="qty"><button data-a="${retail?'rqminus':'qminus'}" data-id="${esc(code)}" aria-label="Restar ${esc(code)}">−</button><input aria-label="Cantidad ${esc(code)}" type="number" min="0" max="99999" value="${q}" data-qty="${esc(code)}" ${retail?'data-retail="1"':''}><button data-a="${retail?'rqplus':'qplus'}" data-id="${esc(code)}" aria-label="Sumar ${esc(code)}">+</button></div>`;}
function catalogueContent(publicView=false){if(publicView)return marketGrid();const list=matchingProducts(publicView);return`<div class="resultsbar"><span>${nf(list.length)} referencias${category!=='Todos'?' · '+catname(category):''}</span>${!publicView?`<span>${role()==='proveedor'?'Fuente: catálogos Dukes':'Precios por cantidad · prueba'}</span>`:''}</div><div class="productgrid">${list.slice(0,limit).map(p=>productCard(p,publicView)).join('')}</div>${!list.length?empty('No encontramos productos.','Prueba otra categoría o referencia.','search'):''}${list.length>limit?`<div class="loadmore">${button('Ver más productos ('+(list.length-limit)+')','more','','light')}</div>`:''}`;}
function cartContent(retail=false){if(retail){const c=db.retailCart;return`<div class="carthead"><h2>Tu compra</h2><small>${publicShopLabel(c.client)}</small></div><div class="cartlines">${c.items.length?c.items.map(l=>{const p=product(l.code),offer=db.retail[c.client][l.code];return`<div class="cartline">${media(p,true,'smallpic')}<div class="grow"><h4>${esc(p.title)}</h4><small>${money(offer.price)}</small><div class="row" style="margin-top:7px">${qtyControl(l.code,l.qty,true)}</div></div><strong style="font-size:12px">${money(offer.price*l.qty)}</strong></div>`;}).join(''):empty('Tu bolsa está vacía.','Encuentra algo que te guste.','cart')}</div><div class="totals"><div class="line total"><span>Subtotal</span><span>${money(retailTotal())}</span></div>${button('Continuar','checkout','','primary full',c.items.length?'':'disabled')}<small style="font-size:10px;display:block;margin-top:10px">Pedido de prueba · sin cobro ni envío real.</small></div>`;}
 const lines=cartLines(),t=cartTotals(),c=customer(client());return`<div class="carthead"><div class="flex between"><h2>Pedido actual</h2><span class="pill">${lines.length} ref.</span></div><small>${esc(c.name)}</small></div><div class="cartlines">${lines.length?lines.map(l=>`<div class="cartline">${media(product(l.code),true,'smallpic')}<div class="grow"><h4>${esc(l.title)}</h4><small>${money(l.unit)} · escala ${l.qty>=48?'48+':l.qty>=24?'24+':l.qty>=12?'12+':l.qty>=6?'6+':l.qty>=3?'3+':'1–2'}</small><div class="row" style="margin-top:7px">${qtyControl(l.code,l.qty)}</div></div><button data-a="remove" data-id="${esc(l.code)}" aria-label="Quitar ${esc(l.code)}" style="color:#91a087">${icon('close')}</button></div>`).join(''):empty('Arma el próximo pedido.','Agrega productos desde el catálogo.','cart')}</div><div class="totals">${role()==='vendedor'?`<div class="discount"><label>Ceder de mi comisión <span class="flex" style="gap:4px"><input type="number" min="0" max="8" step="0.5" id="discount" value="${db.cart.discount}" aria-label="Descuento de la comisión">%</span></label><small>Mi comisión proyectada: ${money(t.commission)}</small></div>`:''}<div class="line"><span>Mercancía</span><span>${money(t.subtotal)}</span></div>${t.discount?`<div class="line"><span>Descuento comercial</span><span>− ${money(t.discount)}</span></div>`:''}<div class="line"><span>Flete</span><span>Por confirmar</span></div><div class="line total"><span>Total mercancía</span><span>${money(t.total)}</span></div>${button(role()==='cliente'?'Enviar pedido':'Enviar para aprobación','send','','primary full',lines.length?'':'disabled')}<small style="font-size:10px;display:block;margin-top:9px">Presentación e impuestos por confirmar. No genera pago.</small></div>`;}
function catalogView(){const supplier=role()==='proveedor';const head=supplier?pagehead('Tu catálogo, en un solo lugar.','Productos, precios y existencias de todas las categorías.',button(icon('upload')+'Importar stock','goto','sincronizar','light')+button(icon('plus')+'Nuevo producto','newproduct')):pagehead(role()==='cliente'?'Compra para tu negocio.':'Vamos con el siguiente pedido.',role()==='cliente'?customer(user).name+' · lista comercial':'Cliente activo: '+customer(client()).name,role()==='vendedor'?`<select id="cartclient" aria-label="Cliente del pedido">${db.customers.map(c=>`<option value="${c.id}" ${client()===c.id?'selected':''}>${c.name} · ${c.city}</option>`).join('')}</select>`:'');return head+`<div class="${supplier?'fullcatalog':'cataloglayout'}"><div>${catControls()}<div id="catalog-results">${catalogueContent()}</div></div>${supplier?'':`<aside class="cart panel" id="cartpanel">${cartContent()}</aside>`}</div>${supplier?'':mobileCartButton()}`;}
function mobileCartButton(retail=false){const b=retail?db.retailCart:db.cart;return`<button class="mobilecart" data-a="${retail?'retailcart':'cart'}"><span>${icon('cart')} &nbsp; ${b.items.reduce((s,l)=>s+l.qty,0)} productos</span><strong>${money(retail?retailTotal():cartTotals().total)} &nbsp; →</strong></button>`;}
function updateCatalogAndCart(){const publicView=screen==='tienda';if($('#catalog-results'))$('#catalog-results').innerHTML=catalogueContent(publicView);if($('#cartpanel'))$('#cartpanel').innerHTML=cartContent();if($('.mobilecart'))$('.mobilecart').outerHTML=mobileCartButton(publicView);if($('#modal').open&&$('#modal').dataset.kind==='cart'){$('.dialogbody').innerHTML=cartContent($('#modal').dataset.retail==='1');}if($('#modal').open&&activeProduct)showProduct(activeProduct);}
function showProduct(code){if(screen==='tienda'){openMarketProduct(code);return;}const p=product(code);if(!p)return;activeProduct=code;const isPublic=screen==='tienda'||role()==='publico',isSupplier=role()==='proveedor'&&!isPublic;const qty=db.cart.items.find(l=>l.code===code)?.qty||1;const priceVal=isPublic?db.retail[db.retailCart.client]?.[code]?.price:price(code,qty);const body=`<div class="detailgrid"><div class="detailmedia">${media(p,false,'',false)}</div><div class="detailinfo"><span class="eyebrow">${catname(p.category)}</span><h1>${esc(p.title)}</h1><span class="detailprice">${money(isSupplier?p.base:priceVal)}</span><p class="muted" style="font-size:11px;margin-top:4px">${isPublic?'Precio de '+customer(db.retailCart.client).name:isSupplier?'Precio del catálogo fuente':'Precio para '+qty+' referencias · simulación comercial'}</p>${isPublic?`<div class="divider"></div><div class="flex">${icon('store')}<div><h3>${customer(db.retailCart.client).name}</h3><small>${customer(db.retailCart.client).city} · ${retailAvailable(db.retailCart.client,code)} disponibles</small></div></div><div class="mt">${button(icon('cart')+'Agregar a mi compra','retailadd',code,'primary full',retailAvailable(db.retailCart.client,code)>0?'':'disabled')}</div>`:`<div class="tiers">${[1,3,6,12,24,48].map(q=>`<div class="tier ${multiplier(q)===multiplier(qty)?'selected':''}">${q===48?'48+':q+'+'} referencias<b>${money(price(code,q))}</b></div>`).join('')}</div><div class="facts"><div><small>Referencia</small><strong>${esc(code)}</strong></div><div><small>Paca reportada</small><strong>${p.paca||'Sin dato'}</strong></div><div><small>Medidas del catálogo</small><strong>${esc(p.dims)||'Por confirmar'}</strong></div><div><small>Existencias actuales</small><strong>${p.stock!=null?nf(available(code))+' · prueba':'Por confirmar'}</strong></div></div><p style="font-size:10px;color:#8e997f">${esc(p.nameOriginal||p.name)}</p><div class="row mt">${isSupplier?button('Editar producto','editproduct',code):button('Agregar al pedido','add',code,'primary',unavailable(p)?'disabled':'')}${isSupplier?button('Crear promoción','newpromo',code,'light'):button(db.favorites.includes(code)?'Guardado':'Guardar','favorite',code,'light')}</div>`}<div class="mt"><small style="font-size:10px">${isPublic?'Pedido de prueba. La disponibilidad mostrada es simulada.':esc(p.sourceFile||'Alta manual')+' · página '+(p.sourcePage||'—')+' · presentación comercial por confirmar.'}</small></div></div></div>`;openDialog(isPublic?'Detalle del producto':'Ficha de producto',body);$('#modal').dataset.kind='product';}
function ordersView(){const kind=screen==='ventas'&&role()==='cliente'?'retail':'b2b';let all=scopedOrders().filter(o=>o.kind===kind),list=filter==='todos'?all:all.filter(o=>o.status===filter);return pagehead(kind==='retail'?'Ventas de mi tienda':'Pedidos en movimiento',kind==='retail'?'Recibe, prepara y entrega las compras locales.':'Cada pedido conserva sus precios, aprobaciones y movimientos.',['vendedor','cliente'].includes(role())&&kind==='b2b'?button(icon('plus')+'Nuevo pedido','goto','catalogo'):'')+`<div class="filters">${['todos',...new Set(all.map(o=>o.status))].map(s=>`<button class="chip ${filter===s?'active':''}" data-a="filter" data-id="${s}">${s==='todos'?'Todos':STATUSES[s][0]} <small>${s==='todos'?all.length:all.filter(o=>o.status===s).length}</small></button>`).join('')}</div><div class="orderlist">${list.map(o=>`<article class="panel orderrow"><div><div class="flex wrap"><h3>${o.id} · ${kind==='retail'?esc(o.buyer):customer(o.client).name}</h3>${statusBadge(o.status)}</div><small>${shortdate(o.createdAt)} · ${o.lines.length} referencias · ${o.lines.reduce((s,l)=>s+l.qty,0)} unidades${kind==='b2b'?' · Jesús Hipinto':''}</small><div class="progress">${['aprobacion','recibido','preparando','despachado','entregado'].map((s,i)=>`<i class="${i<=['aprobacion','recibido','preparando','despachado','entregado'].indexOf(o.status)?'on':''}"></i>`).join('')}</div></div><div class="amount">${money(o.total)}</div><div class="actioncol">${button('Abrir pedido '+icon('arrow'),'order',o.id,'light small')}</div></article>`).join('')||empty('No hay pedidos en este estado.','','order')}</div>`;}
function orderActions(o){let actions=[];if(o.kind==='b2b'){
 if(role()==='cliente'&&o.client===user&&o.status==='aprobacion')actions=[['recibido','Aprobar pedido'],['rechazado','Rechazar']];
 if(role()==='proveedor'&&o.status==='recibido')actions=[['preparando','Confirmar y preparar']];
 if(role()==='proveedor'&&o.status==='preparando')actions=[['despachado','Registrar despacho']];
 if(role()==='cliente'&&o.client===user&&o.status==='despachado')actions=[['entregado','Confirmar recepción']];
 if(role()==='vendedor'&&o.status==='aprobacion')actions=[['cancelado','Cancelar cotización']];
 }else if(role()==='cliente'&&o.client===user){if(o.status==='recibido')actions=[['preparando','Preparar compra'],['cancelado','Cancelar']];if(o.status==='preparando')actions=[['listo','Marcar listo']];if(o.status==='listo')actions=[['entregado','Confirmar entrega']];}
 return actions.map(([to,label])=>button(label,'transition',o.id,to==='rechazado'||to==='cancelado'?'light danger':'primary',`data-to="${to}"`)).join('');}
function orderDetail(id){const o=scopedOrders().find(x=>x.id===id);if(!o){toast('El pedido no pertenece a este perfil.');return;}activeProduct='';const invoice=db.invoices.find(i=>i.order===id);const base=o.lines.reduce((s,l)=>s+l.qty*l.unit,0);const body=`<div class="invoicetop"><div><div class="eyebrow">${o.kind==='retail'?'Venta local':'Pedido comercial'}</div><h1 style="margin-top:7px">${id}</h1><small>${datefmt(o.createdAt)}</small></div><div>${statusBadge(o.status)}<p class="eyebrow" style="margin-top:9px">Operación de prueba</p></div></div><div class="invoicecols"><div><small>Negocio</small><p><strong>${customer(o.client).name}</strong></p><p>${customer(o.client).city}</p></div><div><small>${o.kind==='retail'?'Comprador':'Vendedor'}</small><p>${o.kind==='retail'?esc(o.buyer):'Jesús Hipinto'}</p><p>${o.kind==='retail'?(o.delivery==='pickup'?'Recoge en tienda':'Entrega local por confirmar'):'Proveedor: Daniela'}</p></div><div><small>Referencias</small><p>${o.lines.length} productos</p><p>${o.lines.reduce((s,l)=>s+l.qty,0)} unidades</p></div></div><div class="invoiceLines"><div class="il header"><span>Producto</span><span>Cant.</span><span>Precio</span><span>Total</span></div>${o.lines.map(l=>`<div class="il"><span><strong>${esc(l.title)}</strong><small style="display:block;font-size:9px">${esc(l.code)}</small></span><span>${l.qty}</span><span>${money(l.unit)}</span><span>${money(l.unit*l.qty)}</span></div>`).join('')}</div><div class="invoicebottom"><div><h3>Historial del pedido</h3><div class="history" style="margin-top:16px">${o.history.map(h=>`<div class="historyitem"><strong>${esc(h.text)}</strong><small>${esc(h.actor)} · ${datefmt(h.time)}</small></div>`).join('')}</div></div><div class="totals" style="padding-right:0"><div class="line"><span>Mercancía</span><span>${money(base)}</span></div>${o.discount?`<div class="line"><span>Descuento</span><span>− ${money(o.discount)}</span></div>`:''}${o.shipping?`<div class="line"><span>Envío simulado</span><span>${money(o.shipping)}</span></div>`:''}<div class="line total"><span>Total</span><span>${money(o.total)}</span></div>${role()==='vendedor'?`<small>Comisión proyectada: ${money(o.commission)} · no liquidada</small>`:''}</div></div>`;openDialog(id,body,(invoice?button('Ver factura','invoice',invoice.id,'light'):'')+(['vendedor','cliente'].includes(role())&&o.kind==='b2b'?button('Repetir pedido','repeat',id,'light'):'')+orderActions(o));$('#modal').dataset.kind='order';}
function clientsView(){return pagehead(role()==='aliado'?'Tu red de comercios':'Mis clientes','Tres cuentas de prueba · datos comerciales separados')+`<div class="clientgrid">${db.customers.map(c=>{const days=daysSince(c.last),open=db.orders.filter(o=>o.kind==='b2b'&&o.client===c.id&&!['entregado','rechazado','cancelado'].includes(o.status));return`<article class="panel clientcard"><div class="flex between"><span class="avatar">${c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span class="pill ${days>c.cadence?'orange':'green'}">${days>c.cadence?'Necesita seguimiento':'Cuenta activa'}</span></div><h2>${c.name}</h2><p>${icon('pin')} ${c.city}</p><p>${c.type}</p><div class="activity"><div class="flex between"><small>Último pedido</small><strong>${days} días</strong></div><div class="flex between" style="margin-top:10px"><small>Pendiente de pago</small><strong>${money(clientDebt(c.id))}</strong></div><div class="flex between" style="margin-top:10px"><small>Pedidos abiertos</small><strong>${open.length}</strong></div></div><div class="row">${button('Abrir cuenta','client',c.id,'primary grow')}${role()==='vendedor'?button(icon('plus'),'sellclient',c.id,'light','aria-label="Crear pedido"'):''}</div></article>`;}).join('')}</div>`;}
function clientDetail(id){const c=customer(id);if(!c||!['proveedor','vendedor','aliado'].includes(role()))return;const own=db.orders.filter(o=>o.client===id&&o.kind==='b2b');openDialog(c.name,`<div class="flex wrap"><span class="avatar">${c.name[0]}</span><div class="grow"><h2>${c.name}</h2><small>${c.city} · ${c.type}</small></div><span class="pill ${daysSince(c.last)>c.cadence?'orange':'green'}">${daysSince(c.last)} días sin pedir</span></div><div class="invoicecols"><div><small>Vendedor</small><p>Jesús Hipinto</p></div><div><small>Alianza</small><p>Alex Rodríguez</p></div><div><small>Cartera</small><p>${money(clientDebt(id))}</p></div></div><h3>Pedidos de la cuenta</h3><div class="mt">${compactOrders(own)}</div><h3 class="mt">Notas y seguimiento</h3><div class="history mt">${db.notes.filter(n=>n.client===id).map(n=>`<div class="historyitem"><strong>${esc(n.text)}</strong><small>${n.actor} · ${datefmt(n.date)} ${n.next?'· siguiente: '+n.next:''}</small></div>`).join('')||'<small>No hay notas registradas.</small>'}</div>`,button('Registrar seguimiento','note',id,'light')+(role()==='vendedor'?button('Preparar pedido','sellclient',id):''));}
function followupView(){const due=db.customers.filter(c=>daysSince(c.last)>c.cadence);return pagehead('Mi próxima conversación.','Visitas, llamadas y compromisos de tus clientes.',button(icon('plus')+'Registrar seguimiento','note',db.cart.client))+`<div class="dashboard"><div class="stack"><div class="panel"><div class="panelhead"><h2>Fuera de frecuencia</h2><span class="pill orange">${due.length} negocios</span></div>${due.map(c=>taskRow(c.name,daysSince(c.last)+' días sin pedido · '+c.city,'note',c.id,'Registrar','clock')).join('')}</div><div class="panel"><div class="panelhead"><h2>Próximos compromisos</h2></div>${db.notes.filter(n=>n.next).map(n=>`<div class="task">${icon('pin')}<div class="grow"><h3>${customer(n.client)?.name}</h3><small>${esc(n.text)}</small><p style="font-size:10px;margin-top:5px;color:var(--mut)">${n.next} · ${esc(n.actor)}</p></div>${button('Abrir','client',n.client,'light small')}</div>`).join('')}</div></div><div class="panel pad"><h2>Bitácora</h2><div class="history mt">${db.notes.map(n=>`<div class="historyitem"><strong>${customer(n.client)?.name}</strong><p style="font-size:12px;margin:5px 0">${esc(n.text)}</p><small>${datefmt(n.date)} · ${esc(n.actor)}</small></div>`).join('')}</div></div></div>`;}
function noteForm(id){const c=customer(id)||db.customers[0];openDialog('Registrar seguimiento',`<form id="note-form" class="formgrid"><label class="field full">Cliente<select name="client">${db.customers.map(x=>`<option value="${x.id}" ${c.id===x.id?'selected':''}>${x.name}</option>`).join('')}</select></label><label class="field">Tipo de contacto<select name="channel"><option>Visita presencial</option><option>Llamada</option><option>Mensaje</option><option>Nota interna</option></select></label><label class="field">Próximo contacto<input name="next" type="date" value="2026-09-15"></label><label class="field full">Qué acordamos<textarea name="text" required placeholder="Productos de interés, objeciones o compromiso…"></textarea></label><div class="field full"><button class="btn primary" type="submit">Guardar seguimiento</button></div></form>`);}
function walletView(){const list=scopedInvoices(),pending=list.filter(i=>balance(i)>0),late=pending.filter(overdue);return pagehead(role()==='cliente'?'Mis facturas y pagos':'Cartera de clientes','Cuentas de prueba · no son documentos fiscales')+stats([[money(pending.reduce((s,i)=>s+balance(i),0)),'Saldo pendiente',pending.length+' cuentas abiertas','wallet'],[money(late.reduce((s,i)=>s+balance(i),0)),'Vencido',late.length+' cuentas','clock'],[money(pending.filter(i=>!overdue(i)).reduce((s,i)=>s+balance(i),0)),'Por vencer','Siguiente cobro','order'],[list.flatMap(i=>i.payments).filter(p=>p.status==='pendiente').length,'Abonos por revisar','Validación del proveedor','check']])+`<div class="orderlist">${list.map(i=>`<div class="panel orderrow"><div><div class="flex wrap"><h3>${i.id} · ${customer(i.client).name}</h3>${invoiceState(i)}</div><small>Pedido ${i.order} · vence ${datefmt(i.due)}</small>${i.payments.some(p=>p.status==='pendiente')?'<span class="pill blue" style="margin-top:8px">Abono pendiente de revisión</span>':''}</div><div><div class="amount">${money(balance(i))}</div><small>Saldo de ${money(i.total)}</small></div><div class="actioncol">${button('Ver factura','invoice',i.id,'light small')}</div></div>`).join('')||empty('No hay cuentas registradas.','','wallet')}</div>`;}
function invoiceDetail(id){const i=scopedInvoices().find(x=>x.id===id);if(!i)return;const o=db.orders.find(x=>x.id===i.order);activeProduct='';openDialog('Factura de prueba',`<div class="invoicetop"><div><div class="logo">${wordmark()}</div><p class="eyebrow" style="margin-top:10px">Sin validez fiscal</p></div><div style="text-align:right"><h1>${i.id}</h1>${invoiceState(i)}<p style="font-size:10px;margin-top:8px">Emitida ${datefmt(i.issued)}</p></div></div><div class="invoicecols"><div><small>Emisor de prueba</small><p>Dukes · Daniela</p><p>Pedido ${i.order}</p></div><div><small>Cliente</small><p>${customer(i.client).name}</p><p>${customer(i.client).city}</p></div><div><small>Fecha de vencimiento</small><p>${datefmt(i.due)}</p><p>Moneda: COP</p></div></div><div class="invoiceLines"><div class="il header"><span>Concepto</span><span>Cant.</span><span>Precio</span><span>Importe</span></div>${o.lines.map(l=>`<div class="il"><span>${esc(l.title)}<small style="display:block;font-size:9px">${esc(l.code)}</small></span><span>${l.qty}</span><span>${money(l.unit)}</span><span>${money(l.qty*l.unit)}</span></div>`).join('')}</div><div class="invoicebottom"><div><small>No corresponde a una factura electrónica DIAN. Valores y pagos simulados para revisar el flujo.</small><h3 class="mt">Abonos</h3>${i.payments.map(p=>`<div class="minirow"><span style="font-size:12px">${money(p.amount)}<small style="display:block;font-size:10px">${datefmt(p.date)} · ${esc(p.method)}</small></span>${p.status==='validado'?'<span class="pill green">Validado</span>':role()==='proveedor'?button('Validar','validatepayment',i.id,'light small',`data-payment="${p.id}"`):'<span class="pill orange">En revisión</span>'}</div>`).join('')||'<p class="muted" style="font-size:12px;margin-top:8px">Sin abonos registrados.</p>'}</div><div class="totals"><div class="line"><span>Mercancía</span><span>${money(o.lines.reduce((sum,l)=>sum+l.qty*l.unit,0))}</span></div>${o.discount?`<div class="line"><span>Descuento acordado</span><span>− ${money(o.discount)}</span></div>`:''}<div class="line"><span>Total factura</span><span>${money(i.total)}</span></div><div class="line"><span>Abonos validados</span><span>${money(i.paid)}</span></div><div class="line total"><span>Saldo</span><span>${money(balance(i))}</span></div></div></div>`,button('Imprimir / guardar PDF','print','','light')+(role()==='cliente'&&balance(i)>0?button('Registrar abono de prueba','payment',id):''));$('#modal').dataset.kind='invoice';}
function paymentForm(id){const i=scopedInvoices().find(x=>x.id===id);if(!i||role()!=='cliente')return;openDialog('Abono de prueba · '+id,`<form id="payment-form" data-id="${id}" class="formgrid"><div class="notice field full">Este registro no mueve dinero. El proveedor debe validar el abono antes de descontarlo del saldo.</div><label class="field">Valor<input name="amount" type="number" min="1" max="${balance(i)}" value="${Math.min(50000,balance(i))}" required></label><label class="field">Medio<select name="method"><option>Transferencia de prueba</option><option>Efectivo de prueba</option></select></label><label class="field full">Referencia<input name="ref" maxlength="80" placeholder="Comprobante de prueba"></label><div class="field full"><button type="submit" class="btn primary">Registrar para revisión</button></div></form>`);}
function validatePayment(invoiceId,pid){if(role()!=='proveedor')return;const i=db.invoices.find(x=>x.id===invoiceId),p=i?.payments.find(x=>x.id===pid);if(!p||p.status!=='pendiente')return;if(p.amount>balance(i)){toast('El abono excede el saldo actual. Revisa el registro.');return;}p.status='validado';p.validatedBy=actor();i.paid+=p.amount;audit('Abono validado '+money(p.amount)+' · '+i.id);notify(i.client,'Abono validado · '+i.id,'Nuevo saldo: '+money(balance(i)),'cartera');save();render();invoiceDetail(invoiceId);toast('Abono validado en la prueba');}
function teamView(){return pagehead(role()==='aliado'?'Relaciones comerciales':'Vendedores y alianzas','Perfiles separados por relación comercial.',role()==='proveedor'?button(icon('plus')+'Preparar invitación','invite'):'')+`<div class="dashboard"><div class="stack"><div class="panel"><div class="panelhead"><h2>Vendedores</h2><span class="pill green">${db.team.filter(t=>t.kind==='vendedor'&&t.active).length} activos</span></div>${db.team.filter(t=>t.kind==='vendedor').map((t,i)=>`<div class="teamrow"><span class="avatar">${t.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div class="grow"><h3>${esc(t.name)}</h3><small>${esc(t.territory)} · ${t.email?'Invitación guardada, no enviada':'3 clientes asignados'}</small></div><div class="right">${role()==='proveedor'?button(t.active?'Activo':'Pausado','toggleteam',db.team.indexOf(t),'light small'):statusBadge('recibido')}</div></div>`).join('')}</div><div class="panel"><div class="panelhead"><h2>Socios estratégicos</h2><span class="pill blue">Alianzas</span></div>${db.team.filter(t=>t.kind==='aliado').map(t=>`<div class="teamrow"><span class="avatar">${t.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div class="grow"><h3>${esc(t.name)}</h3><small>${esc(t.territory)}</small></div><span class="pill blue">Socio estratégico</span></div>`).join('')}</div></div><div class="panel pad"><h2>Cuenta del proveedor</h2><div class="minirow"><small>Mayorista</small><strong>Dukes</strong></div><div class="minirow"><small>Administradora</small><strong>Daniela</strong></div><div class="minirow"><small>Catálogos incorporados</small><strong>10</strong></div><div class="minirow"><small>Membresía del mayorista</small><span class="pill orange">Por definir</span></div><div class="minirow"><small>Afiliación de tiendas</small><strong>Sin cuota</strong></div><div class="mt">${button('Dejar mensaje a Daniela','message','daniela','light full')}</div></div></div>`;}
function invitationForm(){if(role()!=='proveedor')return;openDialog('Preparar una invitación',`<form id="invite-form" class="formgrid"><label class="field full">Nombre<input name="name" required maxlength="80"></label><label class="field">Relación comercial<select name="kind"><option value="vendedor">Vendedor</option><option value="aliado">Socio estratégico</option></select></label><label class="field">Territorio<input name="territory" maxlength="100" required></label><label class="field full">Correo<input name="email" type="email" required></label><div class="notice field full">Se guarda como invitación de prueba. No se envía correo ni se crea una cuenta autenticada.</div><button class="btn primary" type="submit">Guardar invitación</button></form>`);}
function salesView(){if(role()==='cliente')return ordersView();const orders=scopedOrders().filter(o=>o.kind==='b2b'),done=orders.filter(o=>o.status==='entregado'),total=done.reduce((s,o)=>s+o.total,0);const week=[0,0,0,0,0,0,0];done.forEach(o=>{const bucket=6-Math.min(6,Math.floor(daysSince(o.createdAt)/7));week[bucket]+=o.total;});const max=Math.max(...week,1);return pagehead(role()==='aliado'?'Ventas de la alianza':'Ventas y territorios','Importes calculados a partir de los pedidos de prueba registrados.',button(icon('download')+'Exportar ventas','exportorders','','light'))+stats([[money(total),'Mercancía entregada',done.length+' pedidos completados','chart'],[money(done.length?total/done.length:0),'Pedido promedio','Solo pedidos entregados','order'],[new Set(done.map(o=>o.client)).size,'Clientes compradores','Cuentas con entregas','users'],[money(db.invoices.reduce((s,i)=>s+i.paid,0)),'Abonos validados','No equivale a beneficio','wallet']])+`<div class="dashboard"><div class="panel pad"><div class="flex between"><h2>Entregas por semana</h2><small>Últimas 7 semanas de la prueba</small></div><div class="chart">${week.map((v,i)=>`<div class="chartbar" style="height:${Math.max(2,v/max*110)}px"><em>${v?money(v):''}</em><span>S${i+1}</span></div>`).join('')}</div><div style="height:22px"></div></div><div class="panel"><div class="panelhead"><h2>Por territorio</h2></div>${db.customers.map(c=>`<div class="teamrow"><div class="grow"><h3>${c.city}</h3><small>${c.name}</small></div><strong>${money(done.filter(o=>o.client===c.id).reduce((s,o)=>s+o.total,0))}</strong></div>`).join('')}</div></div><div class="sectionhead"><h2>Detalle de ventas entregadas</h2><span class="pill">${done.length} ventas</span></div>${compactOrders(done)}`;}
function commissionsView(){const orders=scopedOrders().filter(o=>o.kind==='b2b'),done=orders.filter(o=>o.status==='entregado'),projected=done.reduce((s,o)=>s+o.commission,0),pending=orders.filter(o=>!['cancelado','rechazado','entregado'].includes(o.status));return pagehead('Mis comisiones.','Proyección de prueba · 8 % menos descuentos cedidos')+stats([[money(projected),'Sobre pedidos entregados','Pendiente de política y liquidación','wallet'],[money(pending.reduce((s,o)=>s+o.commission,0)),'En pedidos en proceso',pending.length+' pedidos activos','clock'],[money(orders.reduce((s,o)=>s+o.discount,0)),'Descuento cedido','Se descuenta de tu comisión','tag'],['Por acordar','Liquidación','Daniela define las condiciones','link']])+`<div class="panel"><div class="tablewrap"><table class="datatable"><thead><tr><th>Pedido</th><th>Cliente</th><th>Importe</th><th>Cedido</th><th>Proyección</th><th>Estado</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${o.id}</td><td>${customer(o.client).name}</td><td>${money(o.total)}</td><td>${money(o.discount)}</td><td><strong>${money(o.commission)}</strong></td><td>${statusBadge(o.status)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function promotionsView(){return pagehead('Promociones del mayorista.','Descuentos por referencia, con fecha de finalización.',button(icon('plus')+'Crear promoción','newpromo'))+`<div class="orderlist">${db.promos.map(p=>`<div class="panel orderrow"><div class="flex">${media(product(p.code),true,'listpicture')}<div><h3>${esc(p.title)}</h3><small>${esc(p.code)} · hasta ${datefmt(p.until+'T12:00:00')}</small></div></div><div><strong class="amount">−${p.percent}%</strong><p>${p.active?'<span class="pill green">Activa</span>':'<span class="pill">Pausada</span>'}</p></div><div>${button(p.active?'Pausar':'Activar','togglepromo',p.id,'light small')}</div></div>`).join('')||empty('No hay promociones activas.','Crea la primera sobre una referencia de tu catálogo.','tag')}</div>`;}
function promoForm(code=''){if(role()!=='proveedor')return;openDialog('Nueva promoción',`<form id="promo-form" class="formgrid"><label class="field full">Referencia<input name="code" list="skus" value="${esc(code)}" required><datalist id="skus">${allProducts().map(p=>`<option value="${esc(p.code)}">${esc(p.title)}</option>`).join('')}</datalist></label><label class="field full">Nombre de promoción<input name="title" value="Remate de septiembre" maxlength="90" required></label><label class="field">Descuento sobre precio base (%)<input name="percent" type="number" min="1" max="70" value="5" required></label><label class="field">Hasta<input name="until" type="date" value="2026-09-30" min="2026-09-14" required></label><div class="notice field full">Modifica la oferta mayorista de prueba. No cambia el precio público que cada tienda haya definido.</div><button class="btn primary" type="submit">Publicar promoción de prueba</button></form>`);}
function productForm(code=''){if(role()!=='proveedor')return;const p=product(code)||{code:'',title:'',base:0,category:'Juguetería grande',paca:null,dims:'',stock:null,active:true};activeProduct='';openDialog(code?'Editar '+esc(code):'Agregar un producto',`<form id="product-form" data-code="${esc(code)}" class="formgrid"><label class="field">Código / SKU<input name="code" value="${esc(p.code)}" ${code?'readonly':''} required maxlength="50" pattern="[A-Za-z0-9_+.-]+"></label><label class="field">Categoría<select name="category">${[...categories(),'Ropa'].map(c=>`<option ${p.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="field full">Nombre del producto<input name="title" value="${esc(p.title)}" required maxlength="150"></label><label class="field">Precio base de catálogo (COP)<input name="base" type="number" min="1" value="${p.base||''}" required></label><label class="field">Stock físico confirmado<input name="stock" type="number" min="${reserved(code)}" step="1" value="${p.stock??''}" placeholder="Vacío = por confirmar"></label><label class="field">Unidades por paca<input name="paca" type="number" min="1" step="1" value="${p.paca??''}"></label><label class="field">Medidas<input name="dims" maxlength="120" value="${esc(p.dims)}"></label><div class="filepick field full"><label class="field">Fotografía<input type="file" name="photo" accept="image/png,image/jpeg,image/webp"></label><small>PNG, JPG o WebP. Se conserva la proporción; no se estira el producto.</small>${p.image?`<div style="width:110px;margin-top:10px">${media(p,false)}</div>`:''}</div><label class="check field full"><input name="active" type="checkbox" ${p.active?'checked':''}>Referencia visible en el catálogo</label><div class="field full"><button type="submit" class="btn primary">Guardar producto</button></div></form>`);$('#modal').dataset.kind='form';}
async function uploadedImage(file){if(!file||!file.size)return null;if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Usa una imagen JPG, PNG o WebP.');if(file.size>12*1024*1024)throw Error('La imagen supera 12 MB.');const bitmap=await createImageBitmap(file),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.88);}
function syncView(){return pagehead('Actualizar sin rehacer el catálogo.','Importa las existencias y precios exportados por tu software.')+`<div class="dashboard"><section class="panel pad"><div class="flex between"><h2>Importar archivo CSV</h2>${icon('upload')}</div><p class="muted" style="font-size:12px;margin:10px 0 20px">Campos: <strong>sku</strong>, <strong>stock</strong> y <strong>precio</strong>. Se enlaza por la referencia exacta.</p><div class="filepick"><label class="field">Seleccionar archivo<input id="csv-file" type="file" accept=".csv,text/csv"></label></div><div class="row mt">${button('Descargar plantilla','csvtemplate','','light')}${button('Verificar archivo','previewcsv','','primary')}</div><div id="import-preview"></div></section><div class="stack"><div class="panel pad"><h2>Tu software actual</h2><div class="minirow"><small>Conexión automática</small><span class="pill orange">Sin conectar</span></div><div class="minirow"><small>Último archivo aplicado</small><strong>${db.imports.length?datefmt(db.imports[0].time):'Ninguno'}</strong></div><div class="minirow"><small>Stock que falta confirmar</small><strong>${allProducts().filter(p=>p.stock==null).length} referencias</strong></div><p class="muted" style="font-size:11px;margin-top:15px">El campo “Paca” indica empaque, no existencias. Los valores del PDF no se consideran inventario en tiempo real.</p></div><div class="panel pad"><h2>Historial de importaciones</h2><div class="history mt">${db.imports.map(i=>`<div class="historyitem"><strong>${esc(i.name)}</strong><small>${i.count} referencias · ${datefmt(i.time)}</small></div>`).join('')||'<small>Todavía no se han aplicado archivos.</small>'}</div></div></div></div>`;}
function download(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function parseCSV(text){text=text.replace(/^\ufeff/,'');const delimiter=(text.split(/\r?\n/,1)[0].match(/;/g)||[]).length>(text.split(/\r?\n/,1)[0].match(/,/g)||[]).length?';':',';let rows=[],row=[],val='',quoted=false;for(let i=0;i<text.length;i++){let ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){val+='"';i++;}else quoted=!quoted;}else if(ch===delimiter&&!quoted){row.push(val.trim());val='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(val.trim());if(row.some(Boolean))rows.push(row);row=[];val='';}else val+=ch;}row.push(val.trim());if(row.some(Boolean))rows.push(row);if(quoted)throw Error('Hay comillas sin cerrar en el CSV.');return rows;}
async function previewCSV(){const file=$('#csv-file')?.files[0];if(!file){toast('Selecciona un archivo CSV.');return;}if(file.size>3000000){toast('El archivo supera 3 MB.');return;}try{const rows=parseCSV(await file.text()),heads=(rows.shift()||[]).map(x=>norm(x)),si=heads.indexOf('sku'),qi=heads.indexOf('stock'),pi=heads.indexOf('precio');if(si<0||(qi<0&&pi<0))throw Error('Faltan sku y stock o precio en la cabecera.');const errors=[],updates=[],seen=new Set();rows.forEach((r,i)=>{const code=r[si],p=product(code);if(!p){errors.push('Fila '+(i+2)+': SKU no encontrado '+code);return;}if(seen.has(code)){errors.push('Fila '+(i+2)+': SKU repetido '+code);return;}seen.add(code);const up={code};if(qi>=0&&r[qi]!==''){let v=Number(r[qi]);if(!Number.isInteger(v)||v<reserved(code)){errors.push(code+': stock inválido o inferior al reservado');return;}up.stock=v;}if(pi>=0&&r[pi]!==''){let v=Number(r[pi]);if(!Number.isInteger(v)||v<=0){errors.push(code+': precio debe ser un entero positivo, sin separadores');return;}up.base=v;}if(Object.keys(up).length>1)updates.push(up);});importPreview={name:file.name,updates,errors};$('#import-preview').innerHTML=`<div class="formresult"><strong>${updates.length} referencias válidas</strong><p>${errors.length} errores</p>${errors.length?`<ul>${errors.slice(0,8).map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:''}<div class="mt">${button('Aplicar cambios','applycsv','','primary',errors.length||!updates.length?'disabled':'')}</div></div>`;}catch(e){toast(e.message);}}
function applyCSV(){if(role()!=='proveedor'||!importPreview||importPreview.errors.length||!importPreview.updates.length)return;importPreview.updates.forEach(({code,...u})=>{db.changes[code]={...db.changes[code],...u,stockOrigin:'importacion_de_prueba',updatedBy:actor(),updatedAt:iso(new Date())};});db.imports.unshift({name:importPreview.name,count:importPreview.updates.length,time:iso(new Date())});audit('Archivo de existencias aplicado: '+importPreview.name);notify('jesus','Catálogo actualizado',importPreview.updates.length+' referencias actualizadas.','catalogo');save();importPreview=null;render();toast('Catálogo actualizado desde el CSV de prueba');}
function myInventoryView(){const inv=db.retail[user]||{};return pagehead('Lo que tienes, lo que vendes.','Inventario y precio público de '+customer(user).name,button(icon('eye')+'Ver mi tienda','shop',user,'light'))+`<div class="panel"><div class="tablewrap"><table class="datatable"><thead><tr><th>Producto</th><th>Físico</th><th>Reservado</th><th>Precio público</th><th>Vitrina</th><th></th></tr></thead><tbody>${Object.entries(inv).map(([code,offer])=>{const p=product(code);if(!p)return'';return`<tr><td><div class="itemcell">${media(p,true)}<span><strong>${esc(p.title)}</strong><small>${esc(code)}</small></span></div></td><td>${offer.qty}</td><td>${retailReserved(user,code)}</td><td>${offer.price?money(offer.price):'Sin definir'}</td><td><button class="switch ${offer.published?'on':''}" data-a="toggleoffer" data-id="${esc(code)}" aria-label="${offer.published?'Ocultar':'Publicar'} ${esc(code)}"></button></td><td>${button('Editar','editoffer',code,'light small')}</td></tr>`;}).join('')}</tbody></table></div></div>`;}
function offerForm(code){if(role()!=='cliente')return;const offer=db.retail[user]?.[code],p=product(code);if(!offer||!p)return;openDialog('Editar en mi tienda',`<form id="offer-form" data-id="${esc(code)}" class="formgrid"><div class="flex field full">${media(p,true,'listpicture')}<div><strong>${esc(p.title)}</strong><small style="display:block">${esc(code)}</small></div></div><label class="field">Stock físico<input name="qty" type="number" min="${retailReserved(user,code)}" step="1" value="${offer.qty}" required></label><label class="field">Precio público (COP)<input name="price" type="number" min="1" step="1" value="${offer.price||''}" required></label><label class="check field full"><input name="published" type="checkbox" ${offer.published?'checked':''}>Mostrar en mi tienda pública</label><div class="field full"><button class="btn primary" type="submit">Guardar en mi tienda</button></div></form>`);}
function notificationView(){const notes=db.notifications.filter(n=>n.for===user);return pagehead('Tus notificaciones.','Movimientos dentro del entorno de prueba.',button('Marcar leídas','readall','','light'))+`<div class="panel">${notes.map(n=>`<div class="notification ${n.read?'':'unread'}"><div class="flex between"><h3>${esc(n.title)}</h3><small>${shortdate(n.time)}</small></div><p>${esc(n.body)}</p><div style="margin-top:10px">${button('Abrir','notification',n.id,'light small')}</div></div>`).join('')||empty('Estás al día.','','bell')}</div>`;}
function messageForm(to){openDialog('Dejar un mensaje',`<form id="message-form" data-to="${to}" class="stack"><label class="field">Para<input readonly value="${esc(NAMES[to])}"></label><label class="field">Mensaje<textarea name="text" required maxlength="1000" placeholder="Escribe tu consulta…"></textarea></label><small>Se registra como notificación de prueba. No se envía por WhatsApp ni correo.</small><button type="submit" class="btn primary">Guardar mensaje</button></form>`);}
function storefront(){return marketView();}
function retailCartDialog(){activeProduct='';openDialog('Mi bolsa',cartContent(true));$('#modal').dataset.kind='cart';$('#modal').dataset.retail='1';}
function checkoutForm(){return marketCheckout();}
function makeRetailOrder(f){const c=db.retailCart;if(!c.items.length)return;if(c.items.some(l=>l.qty>retailAvailable(c.client,l.code))){toast('La disponibilidad cambió. Revisa tu bolsa.');return;}const lines=c.items.map(l=>({code:l.code,title:product(l.code).title,qty:l.qty,unit:db.retail[c.client][l.code].price})),subtotal=lines.reduce((s,l)=>s+l.qty*l.unit,0),shipping=f.get('delivery')==='local'?6000:0,id='VT-'+db.nextOrder++;const o={id,kind:'retail',client:c.client,buyer:String(f.get('buyer')).trim(),delivery:f.get('delivery'),note:String(f.get('note')||''),lines,subtotal,total:subtotal+shipping,shipping,status:'recibido',createdAt:iso(new Date()),updatedAt:iso(new Date()),history:[{time:iso(new Date()),actor:String(f.get('buyer')).trim(),text:'Compra registrada en la tienda'}]};db.orders.unshift(o);notify(c.client,'Nueva venta local · '+id,o.buyer+' · '+money(o.total),'ventas');db.retailCart.items=[];save();render();openDialog('Tu pedido está registrado.',`<div style="text-align:center;padding:20px"><span class="avatar" style="margin:auto;width:55px;height:55px">${icon('check')}</span><h1 style="margin:20px 0 8px">${id}</h1><p>El comercio recibió tu pedido en este entorno de prueba.</p><p class="muted" style="font-size:12px;margin:10px 0">${lines.length} productos · ${money(o.total)}</p><span class="pill green">Pendiente de preparar</span><p style="font-size:10px;color:var(--mut);margin-top:20px">No se ha realizado ningún cobro o despacho real.</p></div>`,button('Seguir comprando','close','','primary'));}
function render(){if(screen==='tienda'){$('#app').innerHTML=storefront();return;}if(!user||!ROLES[user]){$('#app').innerHTML=accessView();return;}if(role()==='publico'){screen='tienda';$('#app').innerHTML=storefront();return;}if(!NAV[role()].some(n=>n[0]===screen)&&screen!=='notificaciones')screen=role()==='vendedor'?'catalogo':'inicio';let body='';switch(screen){case'inicio':body=dashboardView();break;case'catalogo':case'inventario':body=catalogView();break;case'pedidos':body=ordersView();break;case'clientes':body=clientsView();break;case'seguimiento':body=followupView();break;case'cartera':body=walletView();break;case'ventas':body=salesView();break;case'equipo':body=teamView();break;case'promociones':body=promotionsView();break;case'sincronizar':body=syncView();break;case'comisiones':body=commissionsView();break;case'miinventario':body=myInventoryView();break;case'notificaciones':body=notificationView();break;default:body=dashboardView();}$('#app').innerHTML=shell(body);}
function switchCartClient(id){if(!customer(id))return;db.drafts??={};db.drafts[db.cart.client]=JSON.parse(JSON.stringify(db.cart));db.cart=db.drafts[id]?JSON.parse(JSON.stringify(db.drafts[id])):{client:id,items:[],discount:0};save();}
function openShop(id=''){if(id&&customer(id)&&db.retailCart.client!==id){if(db.retailCart.items.length&&!confirm('La bolsa corresponde a otra tienda. ¿Vaciarla y cambiar de negocio?'))return;db.retailCart={client:id,items:[]};}else if(!id&&role()==='cliente'&&db.retailCart.client!==user){db.retailCart={client:user,items:[]};}filter='todos';query='';category='Todos';sort='featured';limit=24;save();closeDialog(true);go('tienda');}
function updateCatalogueOnly(){if($('#catalog-results'))$('#catalog-results').innerHTML=catalogueContent(screen==='tienda');}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-a]');if(!el||el.disabled)return;event.preventDefault();const a=el.dataset.a,id=el.dataset.id||'';try{switch(a){
 case'enter':closeDialog(true);changeRole(id);break;
 case'logout':if(closeDialog())go('acceso');break;
 case'menu':$('#shell')?.classList.toggle('menuopen');break;
 case'goto':filter='todos';query='';category='Todos';limit=24;go(id);break;
 case'close':closeDialog();break;
 case'notifications':go('notificaciones');break;
 case'notification':{const n=db.notifications.find(n=>n.id===id&&n.for===user);if(n){n.read=true;save();go(n.target);}break;}
 case'readall':db.notifications.filter(n=>n.for===user).forEach(n=>n.read=true);save();render();break;
 case'category':category=id;limit=24;render();break;
 case'more':limit+=24;updateCatalogueOnly();break;
 case'filter':filter=id;render();break;
 case'detail':showProduct(id);break;
 case'add':add(id);break;
 case'qplus':setQty(id,(db.cart.items.find(x=>x.code===id)?.qty||0)+1);break;
 case'qminus':setQty(id,(db.cart.items.find(x=>x.code===id)?.qty||0)-1);break;
 case'remove':setQty(id,0);break;
 case'cart':activeProduct='';openDialog('Tu pedido',cartContent());$('#modal').dataset.kind='cart';$('#modal').dataset.retail='0';break;
 case'send':makeOrder();break;
 case'order':orderDetail(id);break;
 case'transition':transition(id,el.dataset.to);break;
 case'repeat':{const o=scopedOrders().find(o=>o.id===id);if(!o)return;if(db.cart.items.length&&!confirm('¿Reemplazar el borrador actual con este pedido?'))return;switchCartClient(o.client);db.cart.items=o.lines.map(l=>({code:l.code,qty:l.qty}));db.cart.discount=0;save();closeDialog(true);go('catalogo');toast('Borrador creado con los precios actuales de la prueba');break;}
 case'client':clientDetail(id);break;
 case'sellclient':switchCartClient(id);closeDialog(true);go('catalogo');break;
 case'note':noteForm(id);break;
 case'invoice':invoiceDetail(id);break;
 case'payment':paymentForm(id);break;
 case'validatepayment':validatePayment(id,el.dataset.payment);break;
 case'print':window.print();break;
 case'newproduct':productForm();break;
 case'editproduct':productForm(id);break;
 case'newpromo':promoForm(id);break;
 case'togglepromo':if(role()==='proveedor'){const p=db.promos.find(x=>x.id===id);p.active=!p.active;audit('Promoción '+(p.active?'activada':'pausada')+' · '+p.title);save();render();}break;
 case'invite':invitationForm();break;
 case'toggleteam':if(role()==='proveedor'){const t=db.team[Number(id)];if(t){t.active=!t.active;save();render();}}break;
 case'message':messageForm(id);break;
 case'favorite':db.favorites=db.favorites.includes(id)?db.favorites.filter(c=>c!==id):[...db.favorites,id];save();if(activeProduct)showProduct(id);else updateCatalogueOnly();break;
 case'previewcsv':await previewCSV();break;
 case'applycsv':applyCSV();break;
 case'csvtemplate':download('plantilla-inventario.csv','sku,stock,precio\nT-DK-1698,500,2200\nJ-RZ023,154,30100\n','text/csv;charset=utf-8');break;
 case'export':download('surtiva-copia-pruebas.json',JSON.stringify(db,null,2),'application/json');break;
 case'exportorders':{const rows=[['pedido','cliente','estado','total_cop','fecha'],...scopedOrders().map(o=>[o.id,customer(o.client)?.name,o.status,o.total,o.createdAt])];download('surtiva-ventas-prueba.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');break;}
 case'reset':if(confirm('¿Reiniciar todas las operaciones de prueba en este navegador?')){db=seed();save();render();toast('Prueba reiniciada');}break;
 case'moreaccounts':openDialog('Otros negocios de prueba',db.customers.slice(1).map(c=>`<button class="identity" data-a="enter" data-id="${c.id}"><span class="avatar">${c.name[0]}</span><span><span class="name">${c.name}</span><span class="sub">${c.city}</span></span><span class="arrow">${icon('arrow')}</span></button>`).join(''));break;
 case'editoffer':offerForm(id);break;
 case'toggleoffer':if(role()==='cliente'){const off=db.retail[user]?.[id];if(!off)return;if(!off.published&&(!off.price||off.qty<=0)){toast('Define precio y existencias antes de publicar.');return;}off.published=!off.published;save();render();toast(off.published?'Producto publicado en la vitrina de prueba':'Producto oculto de la vitrina');}break;
 case'shop':openShop(id);break;
 case'shopall':filter='todos';category='Todos';query='';limit=24;render();$('#shopcatalog')?.scrollIntoView({behavior:'smooth'});break;
 case'shopgifts':filter='todos';category='Juguetería grande';query='';limit=24;render();$('#shopcatalog')?.scrollIntoView({behavior:'smooth'});break;
 case'shopoffers':filter='remates';category='Todos';query='';render();$('#shopcatalog')?.scrollIntoView({behavior:'smooth'});break;
 case'shopfavorites':publicBudget=0;filter='favoritos';category='Todos';query='';render();$('#shopcatalog')?.scrollIntoView({behavior:'smooth'});break;
 case'retailadd':add(id,true);render();if(activeProduct)showProduct(id);break;
 case'retailcart':retailCartDialog();break;
 case'rqplus':setQty(id,(db.retailCart.items.find(x=>x.code===id)?.qty||0)+1,true);break;
 case'rqminus':setQty(id,(db.retailCart.items.find(x=>x.code===id)?.qty||0)-1,true);break;
 case'checkout':checkoutForm();break;
 }}catch(e){console.error(e);toast('No se pudo completar la acción. '+e.message);}});
document.addEventListener('input',e=>{if(e.target.id==='q'){query=e.target.value;limit=24;updateCatalogueOnly();}if(e.target.closest('#modal form'))$('#modal').dataset.dirty='1';});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.qty){setQty(t.dataset.qty,t.value,t.dataset.retail==='1');return;}if(t.id==='category'){category=t.value;limit=24;render();}if(t.id==='sort'){sort=t.value;updateCatalogueOnly();}if(t.id==='discount'){if(role()!=='vendedor')return;db.cart.discount=Math.max(0,Math.min(8,Number(t.value)||0));save();updateCatalogAndCart();}if(t.id==='cartclient'){switchCartClient(t.value);render();}if(t.id==='shopcity'){if(db.retailCart.items.length&&!confirm('¿Vaciar la bolsa y cambiar a la tienda de esta ciudad?')){t.value=db.retailCart.client;return;}db.retailCart={client:t.value,items:[]};save();category='Todos';query='';render();}});
document.addEventListener('submit',async e=>{const form=e.target;if(!form.id)return;e.preventDefault();const f=new FormData(form);const submit=form.querySelector('[type="submit"]');try{if(submit)submit.disabled=true;
 if(form.id==='note-form'){const text=String(f.get('text')).trim();if(!text)throw Error('Escribe lo que acordaron.');db.notes.unshift({id:'N-'+Date.now(),client:f.get('client'),text:String(f.get('channel'))+': '+text,date:iso(new Date()),next:f.get('next'),actor:actor()});audit('Seguimiento registrado · '+customer(f.get('client')).name);save();closeDialog(true);render();toast('Seguimiento guardado');}
 if(form.id==='message-form'){const text=String(f.get('text')).trim();if(!text)throw Error('Escribe un mensaje.');notify(form.dataset.to,'Mensaje de '+actor(),text,'notificaciones');save();closeDialog(true);render();toast('Mensaje guardado como notificación de prueba');}
 if(form.id==='payment-form'){const i=scopedInvoices().find(x=>x.id===form.dataset.id);if(!i||role()!=='cliente')throw Error('Factura no accesible.');const value=Number(f.get('amount')),waiting=i.payments.filter(p=>p.status==='pendiente').reduce((s,p)=>s+p.amount,0);if(!Number.isInteger(value)||value<=0||value>balance(i)-waiting)throw Error('El valor supera el saldo libre de abonos pendientes.');i.payments.push({id:'AB-'+Date.now(),amount:value,status:'pendiente',date:iso(new Date()),method:f.get('method'),ref:String(f.get('ref')||'')});notify('daniela','Abono por validar · '+i.id,customer(i.client).name+' · '+money(value),'cartera');save();closeDialog(true);render();invoiceDetail(i.id);toast('Abono enviado a revisión dentro de la prueba');}
 if(form.id==='product-form'){if(role()!=='proveedor')throw Error('Perfil no autorizado.');const original=form.dataset.code,code=String(f.get('code')).trim();if(!original&&product(code))throw Error('La referencia ya existe.');const base=Number(f.get('base')),stock=String(f.get('stock')).trim()===''?null:Number(f.get('stock'));if(!Number.isInteger(base)||base<=0)throw Error('Precio inválido.');if(stock!=null&&(!Number.isInteger(stock)||stock<reserved(code)))throw Error('Stock inválido o menor que las unidades reservadas.');const title=String(f.get('title')).trim();if(!title)throw Error('Escribe el nombre del producto.');const im=await uploadedImage(f.get('photo'));const changes={title,base,price:base,category:f.get('category'),stock,stockOrigin:'edicion_de_prueba',dims:String(f.get('dims')||'').trim(),paca:f.get('paca')?Number(f.get('paca')):null,active:f.has('active'),updatedAt:iso(new Date()),updatedBy:actor()};if(im){changes.image=im;changes.thumb=im;}if(stock>0)changes.sourceUnavailable=false;if(original)db.changes[code]={...db.changes[code],...changes};else db.custom.push({code,id:code,name:title,nameOriginal:title,source:'Alta manual',sourcePage:null,sourceFile:'Creado en el portal de prueba',image:im||'',thumb:im||'',sourceUnavailable:false,...changes});audit((original?'Producto actualizado ':'Producto creado ')+code);notify('jesus','Catálogo actualizado',title,'catalogo');save();closeDialog(true);render();toast('Producto guardado en el catálogo de prueba');}
 if(form.id==='promo-form'){if(role()!=='proveedor')return;const code=String(f.get('code')).trim(),p=product(code),percent=Number(f.get('percent')),until=String(f.get('until'));if(!p)throw Error('No se encuentra esa referencia.');if(percent<1||percent>70)throw Error('Descuento no válido.');if(new Date(until+'T23:59:59')<TODAY)throw Error('La fecha ya pasó.');db.promos.unshift({id:'PROM-'+Date.now(),code,percent,until,title:String(f.get('title')).trim(),active:true});notify('jesus','Nueva promoción',p.title+' · '+percent+' %','catalogo');db.customers.forEach(c=>notify(c.id,'Nueva promoción',p.title+' · '+percent+' %','catalogo'));save();closeDialog(true);render();toast('Promoción publicada en el catálogo de prueba');}
 if(form.id==='invite-form'){if(role()!=='proveedor')return;db.team.push({name:String(f.get('name')).trim(),kind:f.get('kind'),territory:String(f.get('territory')).trim(),email:String(f.get('email')).trim(),active:false});save();closeDialog(true);render();toast('Invitación guardada. No se envió correo.');}
 if(form.id==='offer-form'){if(role()!=='cliente')return;const code=form.dataset.id,off=db.retail[user]?.[code];if(!off)return;const qty=Number(f.get('qty')),price=Number(f.get('price'));if(!Number.isInteger(qty)||qty<retailReserved(user,code))throw Error('No puedes bajar de las unidades reservadas.');if(!Number.isInteger(price)||price<=0)throw Error('Precio público inválido.');db.retail[user][code]={...off,qty,price,published:f.has('published')};save();closeDialog(true);render();toast('Precio e inventario actualizados en tu vitrina');}
 if(form.id==='checkout-form'){makeRetailOrder(f);}
 }catch(err){console.error(err);toast(err.message);}finally{if(submit)submit.disabled=false;}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
window.addEventListener('hashchange',()=>{screen=location.hash.slice(1).split('?')[0]||'tienda';filter='todos';query='';category='Todos';limit=24;render();});
window.addEventListener('storage',e=>{if(e.key==='surtiva.demo.v1'&&e.newValue){try{const next=JSON.parse(e.newValue);if(next.version===6){db=next;render();}}catch{}}});
// Initial render is performed once by arranque.js after the public interface is loaded.
