import {esc,money,safeImage} from './commerce-ui.js';
export function orderNext(o,distributor='Distribuidor'){
 if(o.status==='cancelado'||o.status==='rechazado')return {label:'Pedido cerrado',who:'Sin acciones pendientes'};
 if(o.status==='entregado')return {label:'Entrega confirmada',who:'Compra completada'};
 if(o.status==='despachado')return {label:'Confirmar entrega',who:'Comercio / distribuidor'};
 if(o.status==='preparando')return {label:'Preparar y despachar',who:distributor};
 if(o.approval_status==='changes_requested')return {label:'Ajustar pedido',who:'Vendedor / comercio'};
 if(o.availability_status==='partial')return {label:'Resolver faltantes',who:distributor+' / Surtiva'};
 if(o.availability_status==='requested')return {label:'Confirmar disponibilidad',who:distributor};
 if(o.approval_status!=='approved')return {label:'Revisar y autorizar',who:'Surtiva'};
 if(o.availability_status!=='confirmed')return {label:'Confirmar disponibilidad',who:distributor};
 return {label:'Iniciar preparación',who:distributor};
}
export function orderProgress(o){
 const steps=[['Revisión Surtiva',o.approval_status==='approved'],['Disponibilidad',o.availability_status==='confirmed'],['Preparación',['preparando','despachado','entregado'].includes(o.status)],['Despacho',['despachado','entregado'].includes(o.status)],['Entrega',o.status==='entregado']];
 return `<ol class="order-progress">${steps.map(([label,done],i)=>`<li class="${done?'done':''}"><span>${done?'✓':i+1}</span>${label}</li>`).join('')}</ol>`;
}
export function orderCards(list,{orgName=()=>''}={}){return `<div class="order-board">${list.map(o=>{const next=orderNext(o,orgName(o.organization_id)||'Distribuidor');return `<button class="order-ticket" data-action="order" data-id="${o.id}"><div><b>${esc(o.number)}</b><small>${new Date(o.created_at).toLocaleDateString('es-CO')} · ${esc(orgName(o.organization_id))}</small></div><strong>${money(o.total)}</strong><span class="order-next-label">${esc(next.label)} <span>↗</span></span><small>Turno de ${esc(next.who)}</small></button>`;}).join('')}</div>`;}
export const orderLabels={authorize:'Autorizar y enviar al distribuidor',request_availability:'Consultar disponibilidad',request_changes:'Solicitar ajustes',confirm_availability:'Confirmar existencias',edit:'Editar pedido',assign:'Asignar responsable',prepare:'Iniciar preparación',ship:'Confirmar despacho',deliver:'Confirmar entrega',cancel:'Cancelar pedido',note:'Añadir seguimiento'};
export function orderDetail(d,readonly=false){const o=d.order,next=orderNext(o,d.distributor),actions=readonly?[]:d.actions;
 return `<div class="order-workspace"><div class="order-context"><div><small>CLIENTE</small><b>${esc(d.customer)}</b></div><div><small>DISTRIBUIDOR</small><b>${esc(d.distributor)}</b></div><div><small>RESPONSABLE</small><b>${esc(d.responsible||d.seller||'Sin persona asignada')}</b></div></div>${orderProgress(o)}<section class="order-next"><div><small>SIGUIENTE PASO · ${esc(next.who)}</small><h3>${esc(next.label)}</h3></div><strong>${money(o.total)}</strong></section><div class="order-actions">${actions.filter(a=>!['note','assign','cancel'].includes(a)).map(a=>`<button class="btn ${['authorize','prepare','ship','deliver','confirm_availability'].includes(a)?'primary':'light'}" data-action="order-operation" data-operation="${a}">${esc(orderLabels[a])}</button>`).join('')}</div><div class="order-lines">${d.items.map(i=>`<article><img src="${safeImage(i.image)}" alt="" width="64" height="64" loading="lazy"><div><b>${esc(i.title)}</b><small>${esc(i.sku)} · ${i.quantity} × ${money(i.unitPrice)}</small></div><strong>${money(i.quantity*i.unitPrice)}</strong></article>`).join('')}</div><div class="toolbar">${actions.filter(a=>['assign','note','cancel'].includes(a)).map(a=>`<button class="btn light small" data-action="order-operation" data-operation="${a}">${esc(orderLabels[a])}</button>`).join('')}</div><h3>Historial compartido</h3><div class="order-history">${d.events.map(e=>`<article><span></span><div><b>${esc(e.description)}</b><small>${new Date(e.at).toLocaleString('es-CO')} · ${esc(e.actor)}</small>${e.details?.note?`<p>${esc(e.details.note)}</p>`:''}${e.details?.name?`<p>${esc(e.details.name)}</p>`:''}${e.details?.before?`<details><summary>Ver cambio de referencias y cantidades</summary><p>Antes: ${e.details.before.map(l=>`${esc(l.title)} × ${l.quantity}`).join(' · ')}</p><p>Después: ${e.details.after.map(l=>`${esc(l.title)} × ${l.quantity}`).join(' · ')}</p></details>`:''}</div></article>`).join('')}</div><small class="order-version">Versión ${o.revision} · ${['aprobacion','recibido'].includes(o.status)?'Las ediciones requieren una nueva revisión.':'La preparación ya comenzó; coordina cambios con el responsable.'}</small></div>`;
}
