const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(value)||0);
const date=value=>value?new Date(value).toLocaleDateString('es-CO'):'—';
const brand='<span class="brandword">surtiva<span>✳</span></span>';
const roles={distribuidor:'Distribuidor',vendedor:'Vendedor',comercio:'Comercio',aliado:'Punto de cumplimiento'};
const states={aprobacion:'Por aprobar',recibido:'Recibido',preparando:'En preparación',despachado:'En camino',entregado:'Entregado',cancelado:'Cancelado',rechazado:'Rechazado',pendiente:'Pendiente',aprobada:'Aprobada',rechazada:'Rechazada'};
const sections=[['inicio','Resumen',null],['catalogo','Catálogo','catalog.read'],['inventario','Inventario','inventory.manage'],['clientes','Clientes','customers.read'],['pedidos','Pedidos','orders.read'],['vendedores','Vendedores','team.read'],['proveedores','Proveedores','suppliers.read'],['seguimiento','Seguimiento','followups.manage'],['comisiones','Comisiones','commissions.read'],['cartera','Cartera','receivables.read'],['miinventario','Inventario del comercio','retail.manage'],['ventas','Ventas locales','retail.manage'],['cumplimiento','Cumplimiento','fulfillment.read']];
const tableFor={catalogo:'products',inventario:'inventory',clientes:'customers',pedidos:'orders',vendedores:'sellers',proveedores:'suppliers',seguimiento:'followups',comisiones:'commissions',cartera:'receivables',miinventario:'retail_inventory',ventas:'local_sales',cumplimiento:'fulfillment_records'};
sections.push(['puntos','Puntos de cumplimiento','fulfillment.read']);tableFor.puntos='fulfillment_points';
const manager=()=>session?.isAdmin||role()==='distribuidor';
let session=null,organization='',rows=[],offset=0,cart=[],refreshing=null,renderVersion=0,orderRequestKey=crypto.randomUUID();
const route=()=>location.hash.slice(1).split('?')[0]||'portada';
const membership=()=>session?.memberships.find(m=>m.organization_id===organization);
const currentOrg=()=>session?.organizations.find(o=>o.id===organization);
const role=()=>session?.isAdmin?'admin':membership()?.role_id;
const can=permission=>!permission||session?.isAdmin||session?.permissions.some(p=>p.role_id===role()&&p.permission_id===permission);
function notify(message){const box=document.querySelector('#toast');box.textContent=message;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),5000);}
async function api(path,{method='GET',body,retry=true}={}) {
 const response=await fetch('/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 if(response.status===401&&retry&&!path.startsWith('auth/')) {
  try {refreshing ||= api('auth/refresh',{method:'POST',body:{},retry:false}).finally(()=>refreshing=null);await refreshing;return api(path,{method,body,retry:false});}
  catch {session=null;organization='';cart=[];}
 }
 const result=await response.json().catch(()=>({error:'No se pudo contactar el servicio.'}));
 if(!response.ok){const error=new Error(result.error||'No se pudo completar la operación.');error.status=response.status;throw error;}return result;
}
const scoped=path=>path+(path.includes('?')?'&':'?')+'organization='+encodeURIComponent(organization);
const data=(table,extra='')=>api(scoped('data/'+table+extra));
async function allData(table){const result=[];for(let start=0;;start+=100){const page=await data(table,'?offset='+start);result.push(...page);if(page.length<100)break;if(start>=100000)throw Error('Demasiados registros para esta vista.');}return result;}
function header(){return `<header class="public-header"><a href="#portada" aria-label="Surtiva, inicio">${brand}</a><nav aria-label="Acceso"><a class="btn light" href="#solicitar">Solicitar acceso</a><a class="btn primary" href="#ingresar">Ingresar</a></nav></header>`;}
function landing(){return header()+`<main id="contenido" class="public-main"><section class="platform-hero"><div><span class="mk-eyebrow">UNA RED. MÁS OPORTUNIDADES.</span><h1>Tu red comercial,<br><em>conectada.</em></h1><p>Une catálogo, pedidos y operación en un mismo lugar. Surtiva conecta a quienes distribuyen, venden y abastecen los negocios de cada región.</p><div class="mk-herobuttons"><a href="#solicitar" class="btn primary">Solicitar acceso ↗</a><a href="#ingresar" class="btn light">Ingresar</a></div></div><div class="hero-network"><b>surtiva<span>✳</span></b>${[['Distribuidores','Tu organización, tus productos y tu equipo.'],['Vendedores','Relaciones comerciales que crecen.'],['Comercios','Abastece y organiza tu negocio.'],['Puntos de cumplimiento','Cada pedido, en las manos correctas.']].map(([title,subtitle],i)=>`<div class="network-item"><span class="network-index">0${i+1}</span><div>${title}<small>${subtitle}</small></div></div>`).join('')}<p>Cada empresa conserva el control de su información.</p></div></section><section class="profile-section"><span class="mk-eyebrow">UN ESPACIO PARA CADA PARTE DE LA RED</span><h2>Tu negocio tiene un lugar aquí.</h2><div class="profile-grid">${[['Distribuidores','Organiza productos, inventario, pedidos, vendedores, clientes y proveedores.'],['Vendedores','Consulta tu catálogo habilitado, acompaña a tus clientes y sigue tus pedidos y comisiones.'],['Comercios','Reúne compras, pedidos, cartera, inventario y ventas de tu negocio.'],['Aliados y puntos de cumplimiento','Coordina los pedidos asignados, el stock comprometido y los despachos.']].map(([title,description],i)=>`<article class="profile-card"><span>0${i+1}</span><h3>${title}</h3><p>${description}</p></article>`).join('')}</div></section></main><footer class="public-footer">Surtiva · Una red comercial que crece contigo.</footer>`;}
function authPage(register=false){return header()+`<main id="contenido" class="auth-page"><section class="auth-intro"><span class="mk-eyebrow">TU PRÓXIMO PASO</span><h1>${register?'Conectemos<br>tu negocio.':'Bienvenido<br>a tu red.'}</h1><p>${register?'Cuéntanos quién eres y cómo participas. Revisaremos tu solicitud antes de habilitar tu espacio de trabajo.':'Ingresa con tu cuenta aprobada para acceder a la información de tu organización.'}</p></section><section class="auth-form"><h2>${register?'Solicitar acceso':'Ingresar'}</h2><form id="${register?'register':'login'}">${register?'<label class="field">Nombre completo<input name="name" autocomplete="name" maxlength="100" required></label><label class="field">Organización o negocio<input name="organization" autocomplete="organization" maxlength="120" required></label><label class="field">Perfil solicitado<select name="role" required><option value="">Selecciona tu perfil</option>'+Object.entries(roles).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')+'</select></label>':''}<label class="field">Correo electrónico<input type="email" name="email" autocomplete="email" maxlength="254" required></label><label class="field">Contraseña<input type="password" name="password" autocomplete="${register?'new-password':'current-password'}" ${register?'minlength="12"':''} maxlength="128" required></label>${register?'<small>Usa al menos 12 caracteres. Recibirás un correo para verificar tu dirección. Tu acceso necesita aprobación.</small>':''}<div class="form-feedback" role="status" aria-live="polite"></div><button class="btn primary" type="submit">${register?'Enviar solicitud':'Ingresar'}</button><a class="secondary-link" href="#${register?'ingresar':'solicitar'}">${register?'Ya tengo una cuenta':'Solicitar una cuenta'}</a></form></section></main>`;}
function pending(){const rejected=session?.request?.status==='rechazada';return `<header class="public-header"><a href="#portada">${brand}</a><button class="btn light" data-action="logout">Cerrar sesión</button></header><main id="contenido" class="pending"><span class="pill orange">${rejected?'Solicitud revisada':'Acceso pendiente'}</span><h1>${rejected?'Tu solicitud no fue aprobada.':'Tu solicitud está en revisión.'}</h1><p>${rejected?'Por ahora tu cuenta no tiene acceso a una organización.':'La verificación de correo y la aprobación de Surtiva son necesarias para habilitar tu espacio.'}</p><button class="btn primary" data-action="refresh-session">Consultar estado</button></main>`;}
function shell(content,page){return `<div class="shell"><aside class="sidebar"><a class="logo" href="#portada">${brand}</a><div class="workspace"><strong>${session.isAdmin?'Administración Surtiva':esc(roles[role()])}</strong><label class="scope-label" for="organization">ORGANIZACIÓN</label><select id="organization" class="tenant-select" aria-label="Organización">${session.organizations.map(o=>`<option value="${o.id}" ${o.id===organization?'selected':''}>${esc(o.name)}${o.is_example?' · Ejemplo':''}</option>`).join('')}</select>${currentOrg()?.is_example?'<span class="pill orange">Datos de ejemplo</span>':''}</div><nav class="navlist workspace-nav" aria-label="Área comercial">${session.isAdmin?`<a class="navitem ${page==='red'?'active':''}" href="#red">Toda la red</a><a class="navitem ${page==='solicitudes'?'active':''}" href="#solicitudes">Solicitudes de acceso</a><a class="navitem ${page==='usuarios'?'active':''}" href="#usuarios">Usuarios y permisos</a>`:''}${sections.filter(s=>can(s[2])&&(organization||s[0]==='inicio')).map(([id,title])=>`<a class="navitem ${id===page?'active':''}" href="#${id}">${title}</a>`).join('')}</nav><div class="sidebarfooter"><p class="platform-profile">${esc(session.user.name)}<br>${esc(session.user.email)}</p><button class="btn light full" data-action="logout">Cerrar sesión</button></div></aside><main class="main" id="contenido"><header class="topbar"><button class="btn light mobile-toggle" data-action="menu" aria-label="Abrir menú">☰</button><strong>${esc(currentOrg()?.name||'Red Surtiva')}</strong><span class="pill">${session.isAdmin?'Administrador Surtiva':esc(roles[role()])}</span></header><div class="content">${content}</div></main></div>`;}
const title=(heading,subtitle='')=>`<h1 class="section-title">${heading}</h1>${subtitle?`<p class="scope-note">${subtitle}</p>`:''}`;
function dashboard(){return title('Tu espacio comercial.',currentOrg()?.is_example?'Este es el escenario de ejemplo de '+esc(currentOrg().name)+'.':'La información disponible corresponde a tu organización y tus asignaciones.')+`<div class="workspace-cards">${sections.filter(([id,,permission])=>id!=='inicio'&&can(permission)).map(([id,label])=>`<a class="workspace-card" href="#${id}"><b>${label}</b><p>Consultar ${label.toLowerCase()} ↗</p></a>`).join('')}</div>`;}
const badge=value=>`<span class="pill ${['entregado','aprobada'].includes(value)?'green':'orange'}">${esc(states[value]||value)}</span>`;
const table=(headers,body)=>`<div class="panel tablewrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}"><div class="empty-state">Todavía no hay registros disponibles en este espacio.</div></td></tr>`}</tbody></table></div>`;
const productName=p=>`<div class="table-product">${p.image&&/^assets\/productos\/[a-zA-Z0-9_.-]+$/.test(p.image)?`<img class="table-image" src="/${esc(p.image)}" alt="" loading="lazy">`:''}<span><strong>${esc(p.title)}</strong><small>${esc(p.sku)}</small></span></div>`;
function tableView(page,list){
 if(page==='puntos')return table(['Punto','Ciudad'],list.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.city||'—')}</td></tr>`).join(''));
 if(page==='catalogo')return table(['Producto','Categoría','Precio base',''],list.map(p=>`<tr><td>${productName(p)}</td><td>${esc(p.category)}</td><td>${money(p.price)}<small>Precio por volumen al pedir</small></td><td>${can('orders.create')&&p.active?`<button class="btn light small" data-action="add-product" data-id="${p.id}">Agregar</button>`:badge(p.active?'Habilitado':'Inactivo')}</td></tr>`).join(''));
 if(page==='inventario')return table(['Producto','Físico','Comprometido',''],list.map(p=>`<tr><td>${esc(p.productTitle||p.product_id)}</td><td>${p.quantity??'Por confirmar'}</td><td>${p.reserved}</td><td><button class="btn light small" data-action="edit-stock" data-id="${p.product_id}">Actualizar</button></td></tr>`).join(''));
 if(page==='clientes')return table(['Cliente','Ciudad',''],list.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.city||'—')}</td><td>${can('followups.manage')?`<button class="btn light small" data-action="followup" data-id="${c.id}">Seguimiento</button>`:''}</td></tr>`).join(''));
 if(page==='pedidos')return table(['Pedido','Fecha','Total','Estado',''],list.map(o=>`<tr><td>${esc(o.number)}${o.is_example?'<small>Ejemplo</small>':''}</td><td>${date(o.created_at)}</td><td>${money(o.total)}</td><td>${badge(o.status)}</td><td><button class="btn light small" data-action="order" data-id="${o.id}">Ver pedido</button></td></tr>`).join(''));
 if(page==='vendedores'||page==='proveedores')return table(['Nombre',page==='vendedores'?'Territorio':'Contacto'],list.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.territory||r.contact||'—')}</td></tr>`).join(''));
 if(page==='comisiones')return table(['Pedido','Comisión','Estado'],list.map(r=>`<tr><td>${esc(r.orderNumber||r.order_id)}</td><td>${money(r.amount)}</td><td>${esc(r.status)}</td></tr>`).join(''));
 if(page==='seguimiento')return table(['Cliente','Nota','Próximo contacto'],list.map(r=>`<tr><td>${esc(r.customerName||r.customer_id)}</td><td>${esc(r.note)}</td><td>${date(r.next_date)}</td></tr>`).join(''));
 if(page==='cartera')return table(['Documento','Vencimiento','Total','Saldo'],list.map(r=>`<tr><td>${esc(r.number)}</td><td>${date(r.due_date)}</td><td>${money(r.total)}</td><td>${money(r.total-r.paid)}</td></tr>`).join(''));
 if(page==='miinventario')return table(['Producto','Unidades','Precio local'],list.map(r=>`<tr><td>${esc(r.productTitle||r.product_id)}</td><td>${r.quantity}</td><td>${money(r.price)}</td></tr>`).join(''));
 if(page==='ventas')return table(['Fecha','Venta','Total'],list.map(r=>`<tr><td>${date(r.created_at)}</td><td>${esc(r.id.slice(0,8))}</td><td>${money(r.total)}</td></tr>`).join(''));
 if(page==='cumplimiento')return table(['Pedido','Stock comprometido','Despacho','Estado de pago','Conciliación'],list.map(r=>`<tr><td>${esc(r.orderNumber||r.order_id)}</td><td>${esc(r.committed_stock.map(l=>`${l.sku||l.title||l.productId}: ${l.quantity}`).join(', '))}</td><td>${esc(r.dispatch_reference||'Pendiente')}</td><td>${esc(r.payment_status)}</td><td>${esc(r.reconciliation_status)}</td></tr>`).join(''));
 if(page==='usuarios')return table(['Usuario','Rol','Estado',''],list.map(r=>`<tr><td>${esc(r.user_id)}</td><td>${esc(roles[r.role_id])}</td><td>${r.active?'Activo':'Revocado'}</td><td><button class="btn light small" data-action="membership" data-id="${r.id}">${r.active?'Revocar':'Activar'}</button></td></tr>`).join(''));
 return '';
}
async function enrich(page,list){
 if(['inventario','miinventario'].includes(page)){const products=await allData('products');return list.map(r=>({...r,productTitle:products.find(p=>p.id===r.product_id)?.title}));}
 if(['comisiones','cumplimiento'].includes(page)){const orders=await allData('orders');return list.map(r=>({...r,orderNumber:orders.find(o=>o.id===r.order_id)?.number}));}
 if(page==='seguimiento'){const customers=await allData('customers');return list.map(r=>({...r,customerName:customers.find(c=>c.id===r.customer_id)?.name}));}
 return list;
}
async function render(){
 const version=++renderVersion,page=route();modal.close();
 if(page==='portada'){app.innerHTML=landing();return;}
 if(['ingresar','acceso','solicitar'].includes(page)){app.innerHTML=authPage(page==='solicitar');return;}
 app.innerHTML='<div class="boot"><b>surtiva<span>✳</span></b><p>Verificando acceso…</p></div>';
 try {
  session=await api('session');if(version!==renderVersion)return;
  if(!session.isAdmin&&!session.memberships.length){app.innerHTML=pending();return;}
  if(!session.organizations.some(o=>o.id===organization))organization=session.organizations[0]?.id||'';
  if(page==='pendiente'){location.hash=session.isAdmin?'red':'inicio';return;}
  let content='';
  if(page==='red'&&session.isAdmin)content=title('Toda la red.','Dukes es una organización dentro de Surtiva. Cada organización conserva sus datos y permisos.')+`<div class="workspace-cards">${session.organizations.map(o=>`<button class="workspace-card" data-action="select-org" data-id="${o.id}"><b>${esc(o.name)}</b><p>${esc(o.kind)}${o.is_example?' · Ejemplo':''}</p></button>`).join('')||'<p>No hay organizaciones activas. Aprueba una solicitud para crear la primera.</p>'}</div>`;
  else if(page==='solicitudes'&&session.isAdmin){rows=await api('admin/requests');content=title('Solicitudes de acceso.','La aprobación define organización, rol y asignaciones. El correo debe estar verificado.')+`<div class="panel">${rows.map(r=>`<article class="access-row"><div><h3>${esc(r.profiles?.name||'Solicitante')}</h3><p>${esc(r.organization_name)} · ${esc(roles[r.requested_role])}</p>${badge(r.status)}</div>${r.status==='pendiente'?`<button class="btn primary small" data-action="review" data-id="${r.id}">Revisar solicitud</button>`:''}</article>`).join('')||'<div class="empty-state">No hay solicitudes.</div>'}</div>`;}
  else if(page==='inicio')content=organization?dashboard():title('Tu red está lista para crecer.','Revisa las solicitudes para incorporar organizaciones.');
  else if((page==='usuarios'&&session.isAdmin)||sections.some(s=>s[0]===page&&can(s[2]))){
   if(!organization)throw Error('Primero selecciona o crea una organización.');
   const raw=await data(page==='usuarios'?'memberships':tableFor[page],'?offset='+offset);const enriched=await enrich(page,raw);if(version!==renderVersion)return;rows=enriched;
   content=title(page==='usuarios'?'Usuarios y permisos.':sections.find(s=>s[0]===page)?.[1]+'.',page==='cumplimiento'?'Solo pedidos y movimientos de tus puntos asignados. Los pagos y conciliaciones son registros; no se procesan pagos.':page==='comisiones'?'Proyecciones según la política de tu organización. Sin procesamiento de pagos.':'Información de '+esc(currentOrg().name)+'.')+`<div class="toolbar"><label>Buscar en esta página <input id="search" type="search" placeholder="Escribe para filtrar"></label>${page==='catalogo'&&can('orders.create')?`<button class="btn primary" data-action="cart">Revisar pedido (${cart.length})</button>`:''}</div><div id="data-list">${tableView(page,rows)}</div><div class="toolbar"><span class="data-summary">${rows.length} registros · Página ${offset/100+1}</span><div><button class="btn light small" data-action="previous" ${offset===0?'disabled':''}>Anterior</button> <button class="btn light small" data-action="next" ${raw.length<100?'disabled':''}>Siguiente</button></div></div>`;
   content+=managementTools(page);
  } else content=title('Sección no disponible.','Tu cuenta no tiene permiso para acceder a esta sección.')+'<a class="btn primary" href="#inicio">Volver a mi espacio</a>';
  if(version===renderVersion)app.innerHTML=shell(content,page);
 } catch(error){if(version!==renderVersion)return;if(error.status===401){session=null;app.innerHTML=authPage(false);}else app.innerHTML=header()+`<main id="contenido" class="pending"><h1>No pudimos cargar tu espacio.</h1><p>${esc(error.message)}</p><button class="btn primary" data-action="refresh-session">Intentar nuevamente</button></main>`;}
}
function dialog(titleText,body){modal.innerHTML=`<div class="dialoghead"><h2>${esc(titleText)}</h2><button class="btn light small" data-action="close" aria-label="Cerrar">✕</button></div><div class="dialogbody">${body}<div class="form-feedback" role="status" aria-live="polite"></div></div>`;modal.showModal();}
function managementTools(page){const kinds={catalogo:['product','Agregar producto'],clientes:['customer','Agregar cliente'],vendedores:['seller','Agregar vendedor'],proveedores:['supplier','Agregar proveedor'],puntos:['point','Agregar punto']};return `<div class="toolbar">${manager()&&kinds[page]?`<button class="btn primary" data-action="create-entity" data-kind="${kinds[page][0]}">${kinds[page][1]}</button>`:''}${manager()&&page==='catalogo'&&rows.length?'<button class="btn light" data-action="catalog-access">Administrar catálogo habilitado</button>':''}${manager()&&page==='pedidos'&&rows.length?'<button class="btn light" data-action="assign-point">Asignar punto de cumplimiento</button>':''}${page==='miinventario'&&rows.length?'<button class="btn light" data-action="retail-edit">Editar inventario local</button><button class="btn primary" data-action="retail-sale">Registrar venta local</button>':''}</div>`;}
async function entityDialog(kind){let extra='';if(kind==='customer'){const sellers=await allData('sellers');extra=`<label>Ciudad<input name="city" maxlength="120"></label><label>Vendedor asignado<select name="sellerId"><option value="">Sin asignar</option>${sellers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label>`;}if(kind==='seller')extra='<label>Territorio<input name="territory" maxlength="120"></label>';if(kind==='point')extra='<label>Ciudad<input name="city" maxlength="120"></label>';if(kind==='supplier')extra='<label>Contacto<input name="contact" maxlength="200"></label>';if(kind==='product')extra='<label>SKU<input name="sku" maxlength="50" required></label><label>Categoría<input name="category" maxlength="120" required></label><label>Precio base COP<input name="price" type="number" step="0.01" min="0.01" required></label>';dialog('Agregar registro',`<form id="entity" data-kind="${kind}"><label>Nombre<input name="name" maxlength="150" required></label>${extra}<button class="btn primary" type="submit">Guardar</button></form>`);}
async function catalogDialog(){const [sellers,customers]=await Promise.all([allData('sellers'),allData('customers')]);dialog('Catálogo habilitado',`<form id="catalog-access"><label>Producto de esta página<select name="productId">${rows.map(p=>`<option value="${p.id}">${esc(p.sku)} · ${esc(p.title)}</option>`).join('')}</select></label><label>Perfil y asignación<select name="entity" required><option value="">Selecciona una cuenta</option>${sellers.map(s=>`<option value="vendedor:${s.id}">Vendedor · ${esc(s.name)}</option>`).join('')}${customers.map(c=>`<option value="comercio:${c.id}">Comercio · ${esc(c.name)}</option>`).join('')}</select></label><label>Acceso<select name="enabled"><option value="true">Habilitar producto</option><option value="false">Revocar acceso al producto</option></select></label><button class="btn primary" type="submit">Guardar permiso</button></form>`);}
async function assignDialog(){const points=await allData('fulfillment_points');dialog('Asignar cumplimiento',`<form id="assign-point"><label>Pedido<select name="id" required><option value="">Selecciona un pedido</option>${rows.filter(o=>['aprobacion','recibido','preparando'].includes(o.status)).map(o=>`<option value="${o.id}">${esc(o.number)}</option>`).join('')}</select></label><label>Punto de cumplimiento<select name="pointId" required><option value="">Selecciona un punto</option>${points.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><button class="btn primary" type="submit">Asignar</button></form>`);}
function retailDialog(sale=false){dialog(sale?'Registrar venta local':'Editar inventario local',`<form id="${sale?'retail-sale':'retail-edit'}" data-key="${crypto.randomUUID()}"><label>Producto<select name="item" required>${rows.map(r=>`<option value="${r.customer_id}:${r.product_id}">${esc(r.productTitle||r.product_id)} · ${r.quantity} unidades</option>`).join('')}</select></label><label>${sale?'Unidades vendidas':'Existencias físicas'}<input name="quantity" type="number" min="${sale?1:0}" step="1" required></label>${sale?'<p class="scope-note">El total se calcula con el precio local vigente y descuenta inventario. No procesa ningún pago.</p>':'<label>Precio local COP<input name="price" type="number" min="0.01" step="0.01" required></label>'}<button class="btn primary" type="submit">Guardar</button></form>`);}
function transitions(order){const r=role()==='admin'?'distribuidor':role();if(order.status==='aprobacion')return r==='comercio'?['recibido','rechazado']:['vendedor','distribuidor'].includes(r)?['cancelado']:[];if(order.status==='recibido'&&r==='distribuidor')return ['preparando','cancelado'];if(order.status==='preparando')return r==='distribuidor'?['despachado','cancelado']:r==='aliado'?['despachado']:[];if(order.status==='despachado'&&['comercio','distribuidor'].includes(r))return ['entregado'];return [];}
async function orderDialog(id){const order=rows.find(r=>r.id===id);const [lines,events]=await Promise.all([data('order_lines','?order='+id),data('order_events','?order='+id)]);dialog(order.number,`<p>${badge(order.status)}</p>${lines.map(l=>`<div class="order-line"><span>${esc(l.title)} × ${l.quantity}</span><b>${money(l.quantity*l.unit_price)}</b></div>`).join('')}<div class="toolbar"><strong>Total ${money(order.total)}</strong></div><div class="toolbar">${transitions(order).map(state=>`<button class="btn primary small" data-action="transition" data-id="${id}" data-status="${state}">${esc(states[state])}</button>`).join('')}</div><h3>Seguimiento del pedido</h3>${events.map(e=>`<p class="data-summary">${date(e.created_at)} · ${esc(states[e.description]||e.description)}</p>`).join('')}`);}
async function cartDialog(){if(!cart.length){notify('Agrega productos al pedido.');return;}const customers=role()==='comercio'?[]:await allData('customers');dialog('Revisar pedido',`<form id="create-order">${role()==='comercio'?'':`<label>Cliente<select name="customerId" required><option value="">Selecciona un cliente</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>`}${cart.map(p=>`<label>${esc(p.title)}<input type="number" name="qty-${p.id}" min="1" max="99999" step="1" value="${p.quantity}" required></label>`).join('')}<p class="scope-note">El precio final se calcula según las cantidades y el catálogo vigente. ${role()==='vendedor'?'El cliente deberá aprobar el pedido.':''}</p><button class="btn primary" type="submit">Registrar pedido</button><button class="btn light" type="button" data-action="clear-cart">Vaciar pedido</button></form>`);}
async function approvalEntities(){const form=document.querySelector('#review-access');if(!form)return;const org=form.organizationId.value,r=form.role.value;const holder=form.querySelector('#entity-holder');holder.innerHTML='';form.querySelector('#new-org').hidden=!!org;
 if(!org||r==='distribuidor')return;
 const table=r==='vendedor'?'sellers':r==='comercio'?'customers':'fulfillment_points';
 const entities=await api('data/'+table+'?organization='+encodeURIComponent(org));
 if(!modal.open||form.organizationId.value!==org||form.role.value!==r)return;
 holder.innerHTML=`<label>${r==='vendedor'?'Vendedor':r==='comercio'?'Cuenta comercial':'Punto de cumplimiento'}<select name="entityId" required><option value="">Selecciona una asignación</option>${entities.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></label>`;
}
async function reviewDialog(id){const request=rows.find(r=>r.id===id);dialog('Revisar acceso',`<p class="scope-note">${esc(request.profiles?.name||'Solicitante')} · ${esc(request.organization_name)}</p><form id="review-access" data-id="${id}"><label>Organización<select name="organizationId"><option value="">Crear un distribuidor nuevo</option>${session.organizations.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}</select></label><label id="new-org">Nombre de nueva organización<input name="organizationName" maxlength="120" value="${esc(request.organization_name)}"></label><label>Rol aprobado<select name="role">${Object.entries(roles).map(([value,label])=>`<option value="${value}" ${value===request.requested_role?'selected':''}>${label}</option>`).join('')}</select></label><div id="entity-holder"></div><small>Para vendedor, comercio o aliado, selecciona una organización existente y su entidad comercial.</small><button class="btn primary" name="decision" value="aprobar" type="submit">Aprobar acceso</button><button class="btn light" name="decision" value="rechazar" type="submit" formnovalidate>Rechazar solicitud</button></form>`);}
document.addEventListener('click',async event=>{
 if(event.target.closest('[href="#contenido"]')){event.preventDefault();const main=document.querySelector('#contenido');main?.setAttribute('tabindex','-1');main?.focus();return;}
 const button=event.target.closest('[data-action]');if(!button)return;const {action,id}=button.dataset;button.disabled=true;
 try {
  if(action==='logout'){await api('auth/logout',{method:'POST',body:{}});session=null;organization='';cart=[];rows=[];location.hash='portada';}
  if(action==='refresh-session')await render();
  if(action==='menu')document.querySelector('.shell').classList.toggle('mobile-open');
  if(action==='close')modal.close();
  if(action==='next'||action==='previous'){offset=Math.max(0,offset+(action==='next'?100:-100));await render();}
  if(action==='select-org'){organization=id;cart=[];offset=0;location.hash='inicio';}
  if(action==='add-product'){const product=rows.find(p=>p.id===id),existing=cart.find(p=>p.id===id);if(existing)existing.quantity++;else cart.push({...product,quantity:1});orderRequestKey=crypto.randomUUID();notify('Producto agregado al pedido');await render();}
  if(action==='cart')await cartDialog();
  if(action==='clear-cart'){cart=[];orderRequestKey=crypto.randomUUID();modal.close();await render();}
  if(action==='order')await orderDialog(id);
  if(action==='transition'){await api(scoped('orders/status'),{method:'POST',body:{id,status:button.dataset.status}});modal.close();await render();notify('Pedido actualizado');}
  if(action==='edit-stock'){const row=rows.find(r=>r.product_id===id);dialog('Actualizar existencias',`<form id="stock" data-id="${id}"><label>Cantidad física<input name="quantity" type="number" step="1" min="${row.reserved}" value="${row.quantity??''}" required></label><small>No puede ser inferior al stock comprometido.</small><button class="btn primary" type="submit">Guardar existencias</button></form>`);}
  if(action==='followup'){const customer=rows.find(r=>r.id===id);dialog('Seguimiento · '+customer.name,`<form id="followup" data-id="${id}" data-seller="${customer.seller_id||''}"><label>Nota<textarea name="note" maxlength="2000" required></textarea></label><label>Próximo contacto<input name="nextDate" type="date"></label><button class="btn primary" type="submit">Guardar seguimiento</button></form>`);}
  if(action==='review')await reviewDialog(id);
  if(action==='create-entity')await entityDialog(button.dataset.kind);
  if(action==='catalog-access')await catalogDialog();
  if(action==='assign-point')await assignDialog();
  if(action==='retail-edit'||action==='retail-sale')retailDialog(action==='retail-sale');
  if(action==='membership'){const row=rows.find(r=>r.id===id);await api('admin/membership',{method:'POST',body:{id,enabled:!row.active}});await render();}
 }catch(error){if(modal.open)modal.querySelector('.form-feedback').innerHTML=`<p class="form-message error">${esc(error.message)}</p>`;else notify(error.message);}finally{button.disabled=false;}
});
document.addEventListener('submit',async event=>{
 event.preventDefault();const form=event.target,fields=Object.fromEntries(new FormData(form)),button=event.submitter,feedback=form.querySelector('.form-feedback')||modal.querySelector('.form-feedback');
 if(button)button.disabled=true;if(feedback)feedback.innerHTML='';
 try{
  if(form.id==='register'){const result=await api('auth/register',{method:'POST',body:fields});form.reset();feedback.innerHTML=`<p class="form-message">${esc(result.message)}</p>`;}
  if(form.id==='login'){await api('auth/login',{method:'POST',body:fields});session=await api('session');organization='';location.hash=session.isAdmin?'red':'inicio';await render();}
  if(form.id==='create-order'){const items=cart.map(p=>({productId:p.id,quantity:Number(fields['qty-'+p.id])}));await api(scoped('orders'),{method:'POST',body:{customerId:membership()?.customer_id||fields.customerId,items,requestKey:orderRequestKey}});cart=[];orderRequestKey=crypto.randomUUID();modal.close();location.hash='pedidos';notify('Pedido registrado');}
  if(form.id==='stock'){await api(scoped('inventory'),{method:'PATCH',body:{productId:form.dataset.id,quantity:Number(fields.quantity)}});modal.close();await render();notify('Inventario actualizado');}
  if(form.id==='followup'){await api(scoped('followups'),{method:'POST',body:{...fields,customerId:form.dataset.id,sellerId:form.dataset.seller}});modal.close();notify('Seguimiento guardado');}
  if(form.id==='review-access'){await api('admin/review',{method:'POST',body:{...fields,requestId:form.dataset.id,decision:button.value}});modal.close();await render();notify('Solicitud revisada');}
  if(form.id==='entity'){await api(scoped('entities'),{method:'POST',body:{kind:form.dataset.kind,payload:fields}});modal.close();await render();notify('Registro creado');}
  if(form.id==='catalog-access'){const [entityKind,entityId]=fields.entity.split(':');await api(scoped('catalog/access'),{method:'POST',body:{productId:fields.productId,entityKind,entityId,enabled:fields.enabled==='true'}});modal.close();notify('Permiso de catálogo actualizado');}
  if(form.id==='assign-point'){await api(scoped('orders/assign'),{method:'POST',body:fields});modal.close();await render();notify('Punto asignado');}
  if(form.id==='retail-edit'||form.id==='retail-sale'){const [customerId,productId]=fields.item.split(':');if(form.id==='retail-edit')await api(scoped('retail'),{method:'PATCH',body:{customerId,productId,quantity:Number(fields.quantity),price:Number(fields.price)}});else await api(scoped('retail/sale'),{method:'POST',body:{customerId,items:[{productId,quantity:Number(fields.quantity)}],requestKey:form.dataset.key}});modal.close();await render();notify('Operación local registrada');}
 }catch(error){if(feedback)feedback.innerHTML=`<p class="form-message error">${esc(error.message)}</p>`;else notify(error.message);}finally{if(button)button.disabled=false;}
});
document.addEventListener('change',event=>{
 if(event.target.id==='organization'){organization=event.target.value;cart=[];rows=[];offset=0;orderRequestKey=crypto.randomUUID();render();}
 if(event.target.closest('#review-access')&&['organizationId','role'].includes(event.target.name))approvalEntities().catch(error=>notify(error.message));
});
document.addEventListener('input',event=>{if(event.target.id==='search'){const query=event.target.value.toLocaleLowerCase('es');document.querySelector('#data-list').innerHTML=tableView(route(),rows.filter(r=>Object.values(r).some(v=>String(v).toLocaleLowerCase('es').includes(query))));}});
window.addEventListener('hashchange',()=>{offset=0;render();window.scrollTo(0,0);});
window.addEventListener('pageshow',event=>{if(event.persisted)render();});
render();
