import {createOrderWorkspace} from './order-workspace.js';
import {orderCards} from './order-ui.js';
import {originalPhoto} from './product-photos.js';
import {invitationFlow} from './invitation.js';
import {entranceMarkup} from './entrance.js';
import {createReadCache} from './request-cache.js';
const reads=createReadCache();
import {authenticate,accessToken,supabase} from './auth.js';
import {readAuthReturn,authMessage,cleanAuthReturn} from './auth-return.js';
import {dashboardMarkup,catalogMarkup,scanMarkup,crmMarkup,icons} from './workspace-ui.js';
import {categoryGallery,categoryBanners,installImageRecovery} from './catalog-ui.js';
import {brand,animateBrand} from './brand.js';
import {visitWorkspace,handoffLocked,showHandoffLock} from './visits.js';
installImageRecovery();
let catalogMeta={categories:[],suppliers:[],total:0,hasMore:false},catalogLoad=0,catalogTimer;
let authNotice='';
let recoveryEmail='';
let workspaceMode=false,reviewState=null,catalogProducts=[],catalogFilters={query:'',category:'',supplier:'',sort:'discovery',limit:24},crmProspects=[],crmAgents=[],radarClients=[];
const ownerMode=()=>session?.isAdmin&&!workspaceMode&&!reviewState;
const reviewing=()=>!!reviewState;
const orgName=id=>session?.organizations.find(o=>o.id===id)?.name||catalogProducts.find(p=>p.organization_id===id)?.supplier_name||'Proveedor';
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(value)||0);
const date=value=>value?new Date(value).toLocaleDateString('es-CO'):'—';
const roles={distributor_admin:'Distribuidor',seller:'Vendedor',merchant:'Comercio',fulfillment_partner:'Aliado de cumplimiento'};
const states={pending:'Pendiente',active:'Activo',suspended:'Suspendido',rejected:'Rechazado',aprobacion:'Por aprobar',recibido:'Recibido',preparando:'En preparación',despachado:'En camino',entregado:'Entregado',cancelado:'Cancelado',rechazado:'Rechazado',pendiente:'Pendiente',aprobada:'Aprobada',rechazada:'Rechazada'};
const sections=[['inicio','Inicio',null],['catalogo','Catálogo','catalog.read'],['inventario','Inventario','inventory.manage'],['clientes','Clientes','customers.read'],['pedidos','Pedidos','orders.read'],['vendedores','Vendedores','team.read'],['proveedores','Proveedores','suppliers.read'],['seguimiento','Seguimiento','followups.manage'],['comisiones','Comisiones','commissions.read'],['cartera','Cartera','receivables.read'],['miinventario','Inventario del comercio','retail.manage'],['ventas','Ventas locales','retail.manage'],['cumplimiento','Cumplimiento','fulfillment.read']];
const tableFor={catalogo:'products',inventario:'inventory',clientes:'clients',pedidos:'orders',vendedores:'sellers',proveedores:'suppliers',seguimiento:'followups',comisiones:'commissions',cartera:'invoices',miinventario:'retail_inventory',ventas:'local_sales',cumplimiento:'fulfillment_records'};
sections.push(['invitaciones','Invitaciones','team.read']);tableFor.invitaciones='invitations';
sections.push(['puntos','Puntos de cumplimiento','fulfillment.read']);tableFor.puntos='fulfillment_nodes';
const manager=()=>!reviewing()&&(session?.isAdmin||role()==='distributor_admin');
let session=null,organization='',rows=[],offset=0,cart=[],refreshing=null,renderVersion=0,orderRequestKey=crypto.randomUUID();
const route=()=>location.hash.slice(1).split('?')[0]||'portada';
const inviteToken=()=>new URLSearchParams(location.search).get('invite')||'';
const membership=()=>session?.memberships.find(m=>m.organization_id===organization);
const currentOrg=()=>session?.organizations.find(o=>o.id===organization);
const role=()=>reviewState?.role||(session?.isAdmin?'admin':membership()?.role_id);
const pendingInvite=()=>session?.accountStatus==='pending'&&session?.request?.status==='pending'&&!!session?.request?.invitation_id;
const can=permission=>!permission||(pendingInvite()&&permission==='catalog.read')||(!reviewing()&&session?.isAdmin)||session?.permissions.some(p=>p.role_id===role()&&p.permission_id===permission);
const invitation=invitationFlow({api,root:app,token:inviteToken,onComplete:async()=>{reads.clear();session=await api('session');history.replaceState(null,'','/#catalogo');await render();}});
const orderFlow=createOrderWorkspace({api,dialog,notify,readonly:reviewing,refresh:()=>render(true)});
const visits=visitWorkspace({api,allData,session:()=>session,organization:()=>organization,role,readonly:reviewing,dialog,notify,render,clearCache:()=>reads.clear()});
function notify(message){const box=document.querySelector('#toast');box.textContent=message;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),5000);}
async function api(path,options={}) {
 const method=options.method||'GET';
 if(method!=='GET'||path.startsWith('auth/')){reads.clear();return request(path,options);}
 const token=await accessToken();
 try{return await reads.read((token||'anonymous')+':'+path,()=>request(path,options));}
 catch(error){if([401,403].includes(error.status)){reads.clear();if(error.status===401)session=null;}throw error;}
}
async function request(path,{method='GET',body,retry=true}={}) {
 if(reviewing()&&method!=='GET'&&!path.startsWith('auth/'))throw Error('Estás revisando un perfil. Vuelve a Surtiva para hacer cambios.');
 if(path.startsWith('auth/'))return authenticate(path.slice(5),body);
 const token=['config','health','invitation/open'].includes(path)?null:await accessToken();
 if(!token&&!['config','health','invitation/open'].includes(path)){const error=Error('Ingresa para continuar.');error.status=401;throw error;}
 const response=await fetch('/api/'+path,{method,credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(path.startsWith('invitations')?50000:15000),headers:{...(token?{Authorization:'Bearer '+token}:{}),...(method==='GET'?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});
 if(response.status===401&&path!=='invitation/open'&&retry&&!path.startsWith('auth/')) {
  try {refreshing ||= api('auth/refresh',{method:'POST',body:{},retry:false}).finally(()=>refreshing=null);await refreshing;return request(path,{method,body,retry:false});}
  catch {session=null;organization='';cart=[];}
 }
 const result=await response.json().catch(()=>({error:'No se pudo contactar el servicio.'}));
 if(!response.ok){const error=new Error(result.error||'No se pudo completar la operación.');error.status=response.status;throw error;}return result;
}
const scoped=path=>path+(path.includes('?')?'&':'?')+'organization='+encodeURIComponent(organization);
const data=(table,extra='')=>{
 if(table==='products'&&(!ownerMode()||reviewing()))return api('catalog'+(extra||'?')+(extra?'&':'')+'published='+reviewing());
 if(reviewing()){
  if(!reviewState.member)return reviewState.organization?api('data/'+table+(extra||'?')+(extra?'&':'')+'organization='+encodeURIComponent(reviewState.organization)):Promise.resolve([]);
  return api('admin/review-data?resource='+table+'&membership='+reviewState.member+extra.replace('?','&'));
 }
 return ownerMode()?api('admin/data/'+table+extra):api(scoped('data/'+table+extra));
};
async function allData(table){const result=[],size=ownerMode()||table==='products'?500:100;for(let start=0;;start+=size){const page=await data(table,'?offset='+start+'&limit='+size);result.push(...page);if(page.length<size)break;if(start>=100000)throw Error('Demasiados registros para esta vista.');}return result;}
function header(showRequest=true){return `<header class="public-header"><a href="#portada" aria-label="Surtiva, inicio">${brand}</a><nav aria-label="Acceso">${showRequest?'<a class="btn light" href="#solicitar">Solicitar acceso</a>':''}<a class="btn primary" href="#ingresar">Ingresar ↗</a></nav></header>`;}
function landing(){return entranceMarkup();}
function authPage(register=false){return `<header class="public-header auth-header"><a href="#portada" aria-label="SURTIVA, inicio">${brand}</a><a class="auth-back" href="#portada">← Volver</a></header>`+`<main id="contenido" class="auth-page"><section class="auth-intro"><span class="mk-eyebrow">MÁS SURTIDO. MÁS NEGOCIO.</span><h1>${register?'Tu negocio tiene<br>un lugar aquí.':'Qué bueno<br>tenerte de vuelta.'}</h1><img class="auth-photo" src="/assets/productos/j-6628.webp" alt="Surtido para tu negocio" width="384" height="384"></section><section class="auth-form"><h2>${register?'Solicitar acceso':'Ingresar'}</h2><form id="${register?'register':'login'}">${register?'<label class="field">Nombre completo<input name="name" autocomplete="name" maxlength="100" required></label><label class="field">Organización o negocio<input name="organization" autocomplete="organization" maxlength="120" required></label><label class="field">Perfil solicitado<select name="role" required><option value="">Selecciona tu perfil</option>'+Object.entries(roles).filter(([value])=>value!=='fulfillment_partner'||(inviteToken()&&new URLSearchParams(location.search).get('profile')===value)).map(([value,label])=>`<option value="${value}" ${new URLSearchParams(location.search).get('profile')===value?'selected':''}>${label}</option>`).join('')+'</select></label>':''}<label class="field">Correo electrónico<input type="email" name="email" autocomplete="email" maxlength="254" required></label><label class="field">Contraseña<input type="password" name="password" autocomplete="${register?'new-password':'current-password'}" ${register?'minlength="12"':''} maxlength="128" required></label>${register?'<small>Usa al menos 12 caracteres. Recibirás un correo para verificar tu dirección. Tu acceso necesita aprobación.</small>':''}<div class="form-feedback" role="status" aria-live="polite">${authNotice?`<p class="form-message">${esc(authNotice)}</p>`:''}</div><button class="btn primary" type="submit">${register?'Enviar solicitud':'Ingresar'}</button><a class="secondary-link" href="#${register?'ingresar':'solicitar'}">${register?'Ya tengo una cuenta':'Solicitar una cuenta'}</a>${register?'':'<a class="secondary-link" href="#recuperar">Olvidé mi contraseña</a><a class="secondary-link" href="#confirmar-correo">Reenviar confirmación de correo</a>'}</form></section></main>`;}
function pending(){if(session?.accountStatus==='suspended')return header()+'<main id="contenido" class="pending"><span class="pill orange">Acceso suspendido</span><h1>Tu organización o membresía está suspendida.</h1><p>Contacta a la administración de Surtiva para revisar el estado de tu acceso.</p><button class="btn light" data-action="logout">Cerrar sesión</button><button class="btn primary" data-action="refresh-session">Consultar estado</button></main>';const rejected=session?.accountStatus==='rejected'||session?.request?.status==='rejected';return `<header class="public-header"><a href="#portada">${brand}</a><button class="btn light" data-action="logout">Cerrar sesión</button></header><main id="contenido" class="pending"><span class="pill orange">${rejected?'Solicitud revisada':'Acceso pendiente'}</span><h1>${rejected?'Tu solicitud no fue aprobada.':'Tu solicitud está en revisión.'}</h1><p>${rejected?'Por ahora tu cuenta no tiene acceso a una organización.':'La verificación de correo y la aprobación de Surtiva son necesarias para habilitar tu espacio.'}</p>${pendingInvite()?'<a class="btn primary" href="#catalogo">Explorar catálogo</a><a class="secondary-link" href="#nueva-clave">Guardar mi contraseña</a>':''}<button class="btn light" data-action="refresh-session">Consultar estado</button></main>`;}
function shell(content,page){
 const owner=ownerMode(),review=reviewing();
 const ownerSections=[['red','Mi gestión'],['visitas','Visitas comerciales'],['catalogo','Catálogo central'],['pedidos','Control de ventas'],['radar','Radar de clientes'],['prospeccion','Prospección'],['clientes','Clientes y comercios'],['vendedores','Equipo de ventas'],['agentes','Agentes y responsables'],['seguimiento','Seguimientos'],['cartera','Cartera'],['proveedores','Proveedores'],['inventario','Inventarios'],['organizaciones','Organizaciones'],['solicitudes','Solicitudes'],['usuarios','Usuarios'],['perfiles','Revisar perfiles']];
 const nav=owner?ownerSections:sections.filter(x=>can(x[2])).map(([id,label])=>[id,role()==='merchant'&&id==='clientes'?'Mis proveedores':label]);
 return '<div class="shell restored-shell"><button class="menu-scrim" data-action="close-menu" aria-label="Cerrar menú" tabindex="-1"></button><aside class="sidebar" id="workspace-sidebar"><button class="menu-close" data-action="close-menu" aria-label="Cerrar menú">✕</button><a class="logo" href="#'+(session.isAdmin?'red':'inicio')+'" '+(session.isAdmin?'data-action="owner-home"':'')+'>'+brand+'</a>'+(!owner&&!review&&session.organizations.length>1?'<select id="organization" class="tenant-select" aria-label="Organización">'+session.organizations.map(o=>'<option value="'+o.id+'" '+(o.id===organization?'selected':'')+'>'+esc(o.name)+'</option>').join('')+'</select>':'')+'<nav class="navlist workspace-nav" aria-label="Área comercial">'+nav.map(([id,label])=>'<a class="navitem '+(page===id?'active':'')+'" href="#'+id+'"><span aria-hidden="true">'+(icons[id]||'·')+'</span>'+label+'</a>').join('')+'</nav></aside><main class="main" id="contenido"><header class="topbar"><button class="btn light mobile-toggle" data-action="menu" aria-label="Abrir menú" aria-expanded="false" aria-controls="workspace-sidebar">☰</button><strong>'+esc((owner?ownerSections:nav).find(x=>x[0]===page)?.[1]||'Resumen')+'</strong><div class="topbar-actions"><button class="account-avatar" data-action="account" aria-label="Abrir mi perfil">'+avatarMarkup()+'</button></div></header>'+(review?'<div class="review-banner"><strong>Revisión · '+esc(roles[role()])+'</strong><span>'+(reviewState.member?'Datos y permisos del usuario seleccionado. Solo lectura.':reviewState.organization?'Datos reales de la organización. Revisión de distribuidor en solo lectura.':'Vista sin usuario asignado: muestra el estado vacío real de este perfil.')+'</span><button class="btn light small" data-action="owner-home">Salir de revisión</button></div>':'')+'<div class="content">'+content+'</div></main>'+mobileNav(page)+'</div>';
}
function mobileNav(page){return '<nav class="mobile-bottom-nav" aria-label="Navegación móvil"><a href="#'+(ownerMode()?'red':'inicio')+'" '+(['red','inicio'].includes(page)?'aria-current="page"':'')+'><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m3 10 9-7 9 7v10H3Z M9 20v-7h6v7"/></svg>Inicio</a><a href="#catalogo" '+(page==='catalogo'?'aria-current="page"':'')+'><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>Catálogo</a>'+(can('orders.read')?'<a href="#pedidos" '+(page==='pedidos'?'aria-current="page"':'')+'><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 3h9l4 4v14H6Z M14 3v5h5 M9 12h7 M9 16h7"/></svg>Pedidos</a>':'')+'<button data-action="menu" aria-label="Más secciones"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="4" cy="12" r="1.2"/><circle cx="12" cy="12" r="1.2"/><circle cx="20" cy="12" r="1.2"/></svg>Más</button></nav>';}
function avatarMarkup(){const picture=session?.user.avatarUrl;return picture&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(picture)?'<img src="'+picture+'" alt="">':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg>';}
function accountDialog(){setMenu(false);dialog('Mi perfil','<div class="account-details"><div class="account-avatar large">'+avatarMarkup()+'</div><h3>'+esc(session.user.name)+'</h3><p>'+esc(session.user.email)+'</p><small>'+esc(session.isAdmin?'Administrador de Surtiva':roles[role()])+'</small></div><form id="profile-photo"><label>Foto de perfil<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><small>JPG, PNG o WebP · máximo 5 MB</small><button class="btn primary">Guardar foto</button></form><hr><a class="btn light" href="#nueva-clave">Guardar o cambiar contraseña</a><button class="btn light" data-action="logout">Cerrar sesión</button>');}
async function saveProfilePhoto(file){
 if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Selecciona una imagen JPG, PNG o WebP de hasta 5 MB.');
 const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=canvas.height=64;const side=Math.min(bitmap.width,bitmap.height);canvas.getContext('2d').drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,64,64);bitmap.close();
 let photo=canvas.toDataURL('image/jpeg',.5);if(photo.length>3000)photo=canvas.toDataURL('image/jpeg',.2);if(photo.length>3000)throw Error('Prueba con una foto más sencilla.');const client=await supabase();const {error}=await client.auth.updateUser({data:{avatar_url:photo}});if(error)throw Error('No se pudo guardar la foto. Intenta nuevamente.');reads.clear();session=await api('session');modal.close();await render();notify('Foto guardada');
}
const title=(heading,subtitle='')=>`<h1 class="section-title">${heading}</h1>${subtitle?`<p class="scope-note">${subtitle}</p>`:''}`;
async function dashboard(){
 const keys=[['orders','orders.read'],['clients','customers.read'],['sellers','team.read'],['invoices','receivables.read'],['followups','followups.manage'],['commissions','commissions.read'],['local_sales','retail.manage']];
 const bundle=Object.fromEntries(await Promise.all(keys.map(async([key,permission])=>[key,can(permission)&&(!ownerMode()||key!=='local_sales')?await allData(key):[]])));
 if(can('catalog.read'))bundle.productCount=(await api('catalog/browse?limit=1&published='+reviewing())).catalogTotal;
 return dashboardMarkup(bundle,{owner:ownerMode(),role:role(),name:currentOrg()?.name,orgName,readonly:reviewing()});
}
async function loadCatalogPage(append=false){
 const ticket=++catalogLoad;
 const params=new URLSearchParams({...catalogFilters,limit:24,offset:append?catalogProducts.length:0,published:reviewing()});
 const response=await api('catalog/browse?'+params);
 if(ticket!==catalogLoad)return false;
 catalogMeta=response;catalogProducts=append?[...catalogProducts,...response.products]:response.products;rows=catalogProducts;return true;
}
async function catalogPage(){
 await loadCatalogPage();
 return '<div class="catalog-heading"><div><h1>Catálogos</h1></div>'+(!reviewing()&&(session.isAdmin||['seller','distributor_admin'].includes(role()))?'<button class="btn light small" data-action="visit-pick">Mostrar a un comercio</button>':'')+'</div><div class="catalog-searchbar" '+(!catalogFilters.category&&!catalogFilters.query?'data-category-entry':'')+'><label class="catalog-search"><span class="sr-only">Buscar productos</span><input id="catalog-query" type="search" placeholder="Buscar por producto o referencia" value="'+esc(catalogFilters.query)+'"></label><label class="catalog-order sort-order"><span class="sr-only">Ordenar</span><select id="catalog-sort">'+[['discovery','Descubrir'],['low','Menor precio'],['high','Mayor precio'],['name','Nombre A–Z']].map(([v,n])=>'<option value="'+v+'" '+(catalogFilters.sort===v?'selected':'')+'>'+n+'</option>').join('')+'</select></label>'+(catalogMeta.suppliers.length>1?'<label class="catalog-order">Proveedor<select id="catalog-supplier"><option value="">Todos</option>'+catalogMeta.suppliers.map(s=>'<option value="'+s.id+'" '+(s.id===catalogFilters.supplier?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label>':'')+'</div><div id="catalog-categories">'+categoryStrip()+'</div><div id="catalog-results" aria-live="polite">'+catalogResults()+'</div>'+(!reviewing()&&can('orders.create')?'<button class="catalog-cart-bar" '+(!cart.length?'hidden':'')+' data-action="cart">Revisar pedido ('+cart.length+')</button>':'')+(!reviewing()?managementTools('catalogo'):'');
}
function categoryStrip(){return (!catalogFilters.category&&!catalogFilters.query?categoryBanners(catalogMeta.categories,'workspace'):'')+categoryGallery(catalogMeta.categories,catalogFilters.category||(catalogFilters.query?'Resultados':''),'workspace');}
function catalogResults(){if(!catalogFilters.category&&!catalogFilters.query)return '';return '<div class="catalog-section-title"><h2>'+esc(catalogFilters.query?'Resultados de búsqueda':catalogFilters.category||'Resultados')+'</h2>'+(catalogFilters.query?'<button class="text-button" data-action="category" data-category="">Volver a categorías</button>':'')+'</div>'+catalogMarkup(catalogProducts,{serverPage:true,total:catalogMeta.total,hasMore:catalogMeta.hasMore,limit:catalogProducts.length,orgName,canOrder:can('orders.create'),readonly:reviewing()});}
async function refreshCatalog(append=false){
 const area=document.querySelector('#catalog-results');if(!area)return;
 area.setAttribute('aria-busy','true');
 try{if(await loadCatalogPage(append)&&route()==='catalogo'){
 area.innerHTML=catalogResults();document.querySelector('#catalog-categories').innerHTML=categoryStrip();document.querySelector('.catalog-searchbar')?.toggleAttribute('data-category-entry',!catalogFilters.category&&!catalogFilters.query);
 }}catch(error){notify(error.message);}finally{area.removeAttribute('aria-busy');}
}
function productDialog(id){const p=catalogProducts.find(p=>p.id===id);if(!p)return;dialog(p.title,'<div class="product-detail-restored">'+(p.image&&/^assets\/productos\/[a-zA-Z0-9_.-]+$/.test(p.image)?'<a class="photo-zoom" href="'+esc(originalPhoto(p.image)||'/'+p.image)+'" target="_blank" rel="noopener" aria-label="Ampliar fotografía"><img src="'+esc(originalPhoto(p.image)||'/'+p.image)+'" alt="'+esc(p.title)+'"></a>':'')+'<div><span class="mk-eyebrow">'+esc(orgName(p.organization_id))+'</span><h2>'+esc(p.title)+'</h2><p>'+esc(p.sku)+' · '+esc(p.category)+'</p><strong class="detail-price">'+money(p.price)+'</strong><p>Desde 48 unidades. Precio por unidad según la cantidad:</p><div class="volume-prices">'+[[1,1.27],[3,1.18],[6,1.13],[12,1.08],[24,1.03],[48,1]].map(([qty,factor])=>'<span>'+qty+'+ unidades<strong>'+money(Math.round(p.price*factor))+'</strong></span>').join('')+'</div><dl><dt>Medidas</dt><dd>'+esc(p.dimensions||'Por confirmar')+'</dd><dt>Presentación</dt><dd>'+esc(p.pack_size||'Por confirmar')+'</dd><dt>Disponibilidad</dt><dd>'+(p.active?'Consultar inventario confirmado':'Referencia inactiva')+'</dd></dl>'+(!reviewing()&&can('orders.create')&&p.active?'<button class="btn primary" data-action="add-product" data-id="'+p.id+'">Agregar al pedido</button>':'')+(manager()&&(ownerMode()||p.organization_id===organization)?'<button class="btn light" data-action="edit-product" data-id="'+p.id+'">Editar ficha</button>':'')+'</div></div>');}

const badge=value=>`<span class="pill ${['entregado','active'].includes(value)?'green':'orange'}">${esc(states[value]||value)}</span>`;
const table=(headers,body)=>`<div class="panel tablewrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}"><div class="empty-state">Todavía no hay registros disponibles en este espacio.</div></td></tr>`}</tbody></table></div>`;
const productName=p=>`<div class="table-product">${p.image&&/^assets\/productos\/[a-zA-Z0-9_.-]+$/.test(p.image)?`<img class="table-image" src="/${esc(p.image)}" alt="" loading="lazy">`:''}<span><strong>${esc(p.title)}</strong><small>${esc(p.sku)}</small></span></div>`;
const scopeLabel=r=>ownerMode()&&r.organization_id?'<small>'+esc(orgName(r.organization_id))+'</small>':'';
function tableView(page,list){
 if(!list.length)return emptyView(page);
 if(page==='puntos')return table(['Punto','Ciudad'],list.map(r=>`<tr><td>${esc(r.name)}${scopeLabel(r)}</td><td>${esc(r.city||'—')}</td></tr>`).join(''));
 if(page==='catalogo')return table(['Producto','Categoría','Precio base',''],list.map(p=>`<tr><td>${productName(p)}</td><td>${esc(p.category)}</td><td>${money(p.price)}<small>Precio por volumen al pedir</small></td><td>${can('orders.create')&&p.active?`<button class="btn light small" data-action="add-product" data-id="${p.id}">Agregar</button>`:badge(p.active?'Habilitado':'Inactivo')}</td></tr>`).join(''));
 if(page==='inventario')return table(['Producto','Físico','Comprometido',''],list.map(p=>`<tr><td>${esc(p.productTitle||p.product_id)}</td><td>${p.quantity??'Por confirmar'}</td><td>${p.reserved}</td><td>${!reviewing()?`<button class="btn light small" data-action="edit-stock" data-id="${p.product_id}">Actualizar</button>`:''}</td></tr>`).join(''));
 if(page==='clientes')return table(['Cliente','Ciudad',''],list.map(c=>`<tr><td>${esc(role()==='merchant'?c.distributor_name||c.name:c.name)}${scopeLabel(c)}</td><td>${esc(c.city||'—')}</td><td>${!reviewing()&&can('followups.manage')&&c.seller_id?`<button class="btn light small" data-action="followup" data-id="${c.id}">Seguimiento</button>`:''}${manager()?` <button class="btn light small" data-action="assign-seller" data-id="${c.id}">Asignar vendedor</button>`:''}</td></tr>`).join(''));
 if(page==='pedidos')return orderCards(list,{orgName});
 if(page==='vendedores'||page==='proveedores')return table(['Nombre',page==='vendedores'?'Territorio':'Contacto'],list.map(r=>`<tr><td>${esc(r.name)}${scopeLabel(r)}</td><td>${esc(r.territory||r.contact||'—')}</td></tr>`).join(''));
 if(page==='comisiones')return table(['Pedido','Comisión','Estado'],list.map(r=>`<tr><td>${esc(r.orderNumber||r.order_id)}</td><td>${money(r.amount)}</td><td>${esc(r.status)}</td></tr>`).join(''));
 if(page==='seguimiento')return table(['Cliente','Nota','Próximo contacto'],list.map(r=>`<tr><td>${esc(r.customerName||r.customer_id)}</td><td>${esc(r.note)}</td><td>${date(r.next_date)}</td></tr>`).join(''));
 if(page==='cartera')return table(['Documento','Vencimiento','Total','Saldo'],list.map(r=>`<tr><td>${esc(r.number)}</td><td>${date(r.due_date)}</td><td>${money(r.total)}</td><td>${money(r.total-r.paid)}</td></tr>`).join(''));
 if(page==='miinventario')return table(['Producto','Unidades','Precio local'],list.map(r=>`<tr><td>${esc(r.productTitle||r.product_id)}</td><td>${r.quantity}</td><td>${money(r.price)}</td></tr>`).join(''));
 if(page==='ventas')return table(['Fecha','Venta','Total'],list.map(r=>`<tr><td>${date(r.created_at)}</td><td>${esc(r.id.slice(0,8))}</td><td>${money(r.total)}</td></tr>`).join(''));
 if(page==='cumplimiento')return table(['Pedido','Stock comprometido','Despacho','Estado de pago','Conciliación'],list.map(r=>`<tr><td>${esc(r.orderNumber||r.order_id)}</td><td>${esc(r.committed_stock.map(l=>`${l.sku||l.title||l.productId}: ${l.quantity}`).join(', '))}</td><td>${esc(r.dispatch_reference||'Pendiente')}</td><td>${esc(r.payment_status)}</td><td>${esc(r.reconciliation_status)}</td></tr>`).join(''));
 if(page==='invitaciones')return table(['Nombre','Correo','Perfil','Estado','Vence'],list.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.email)}</td><td>${esc(roles[i.role_id])}</td><td>${badge(i.status==='pending'&&new Date(i.expires_at)<new Date()?'Vencida':i.status)}</td><td>${date(i.expires_at)}</td></tr>`).join(''));
 if(page==='usuarios')return table(['Usuario','Rol','Estado',''],list.map(r=>`<tr><td>${esc(r.profiles?.name||r.user_id)}</td><td>${esc(roles[r.role_id]||'Administrador maestro de Surtiva')}</td><td>${badge(r.status)}</td><td><button class="btn light small" data-action="membership" data-id="${r.id}">${r.status==='active'?'Suspender':'Activar'}</button></td></tr>`).join(''));
 return '';
}
async function enrich(page,list){
 if(['inventario','miinventario'].includes(page)){const products=await allData('products');return list.map(r=>({...r,productTitle:products.find(p=>p.id===r.product_id)?.title}));}
 if(['comisiones','cumplimiento'].includes(page)){const orders=await allData('orders');return list.map(r=>({...r,orderNumber:orders.find(o=>o.id===r.order_id)?.number}));}
 if(page==='seguimiento'){const customers=await allData('clients');return list.map(r=>({...r,customerName:customers.find(c=>c.id===r.customer_id)?.name}));}
 return list;
}
async function render(quiet=false){
 if(handoffLocked()){showHandoffLock(app,render);return;}
 const version=++renderVersion,page=route();modal.close();setMenu(false);
 if(page==='unirme'||(inviteToken()&&page==='solicitar')){await invitation.render();return;}
 if(page==='confirmar-correo'){app.innerHTML=confirmationPage();checkConfiguration(version);return;}
 if(page==='activar-administrador'){app.innerHTML=ownerActivationPage();checkConfiguration(version);return;}
 if(page==='verificar-recuperacion'){app.innerHTML=recoveryCodePage();checkConfiguration(version);return;}
 if(['recuperar','nueva-clave'].includes(page)){app.innerHTML=recoveryPage(page==='nueva-clave');checkConfiguration(version);return;}
 if(page!=='catalogo')document.body.classList.remove('catalog-presentation');
 if(page==='portada'){app.innerHTML=landing();return;}
 if(['ingresar','acceso','solicitar'].includes(page)){app.innerHTML=authPage(page==='solicitar');checkConfiguration(version);return;}
 if(session&&!quiet){
  const area=app.querySelector('.content');
  const loading='<div class="route-loading" role="status"><span></span>Cargando sección…</div>';
  if(area){area.innerHTML=loading;const currentLink=app.querySelector('.navitem[href="#'+page+'"]');if(currentLink)app.querySelector('.topbar>strong').textContent=currentLink.textContent.trim();app.querySelectorAll('.navitem').forEach(a=>a.classList.toggle('active',a.hash==='#'+page));}
  else app.innerHTML=shell(loading,page);
 }else if(!session)app.innerHTML='<div class="boot">'+brand+'<p>Abriendo tu espacio…</p></div>';
 try {
  session=await api('session');if(version!==renderVersion)return;
  if(!session.isAdmin&&!session.memberships.length){if(pendingInvite()&&page==='catalogo'){app.innerHTML=shell('<div class="review-banner"><span>Estamos revisando tu acceso. Mientras tanto, explora el catálogo.</span></div>'+await catalogPage(),page);}else app.innerHTML=pending();return;}
  if(!session.isAdmin)session.organizations=session.organizations.filter(o=>o.status==='active'&&session.memberships.some(m=>m.organization_id===o.id));
  if(!ownerMode()&&!reviewing()&&!session.organizations.some(o=>o.id===organization))organization=session.organizations.find(o=>o.kind!=='plataforma')?.id||session.organizations[0]?.id||'';
  if(page==='pendiente'){location.hash=session.isAdmin?'red':'inicio';return;}
  let content='';
  if(page==='red'&&session.isAdmin){workspaceMode=false;reviewState=null;content=await dashboard();}
  else if(page==='organizaciones'&&session.isAdmin)content=network();
  else if(page==='perfiles'&&session.isAdmin)content=await profileReviewPage();
  else if(page==='radar'&&ownerMode()){const [clients,orders,followups]=await Promise.all(['clients','orders','followups'].map(allData));radarClients=clients;content=scanMarkup(clients,orders,followups,orgName);}
  else if(page==='prospeccion'&&ownerMode()){[crmProspects,crmAgents]=await Promise.all(['prospects','commercial_agents'].map(allData));content=crmMarkup(crmProspects,crmAgents);}
  else if(page==='agentes'&&ownerMode())content=await agentsPage();
  else if(page==='catalogo'&&can('catalog.read'))content=await catalogPage();
  else if(page==='solicitudes'&&session.isAdmin){const requests=await api('admin/requests');if(version!==renderVersion)return;rows=requests;content=title('Solicitudes de acceso.','La aprobación define organización, rol y asignaciones. El correo debe estar verificado.')+`<div class="panel">${rows.map(r=>`<article class="access-row"><div><h3>${esc(r.profiles?.name||'Solicitante')}</h3><p>${esc(r.organization_name)} · ${esc(roles[r.requested_role])}</p>${badge(r.status)}</div>${r.status==='pending'?`<button class="btn primary small" data-action="review" data-id="${r.id}">Revisar solicitud</button>`:''}</article>`).join('')||'<div class="empty-state">No hay solicitudes.</div>'}</div>`;}
  else if((page==='inicio'&&role()==='seller')||(page==='visitas'&&(session.isAdmin||['seller','distributor_admin'].includes(role()))))content=await visits.page();
  else if(page==='inicio')content=(organization||reviewing()||ownerMode())?await dashboard():title('Tu red está lista para crecer.','Revisa las solicitudes para incorporar organizaciones.');
  else if(page==='clientes'&&(session.isAdmin||role()==='seller'||role()==='distributor_admin'))content=await visits.page();
  else if((page==='usuarios'&&session.isAdmin)||sections.some(s=>s[0]===page&&can(s[2]))){
   if(!organization&&!ownerMode()&&!reviewing())throw Error('Primero selecciona o crea una organización.');
   const raw=await data(page==='usuarios'?'memberships':tableFor[page],'?offset='+offset);const enriched=await enrich(page,raw);if(version!==renderVersion)return;rows=enriched;
   content=title(page==='usuarios'?'Usuarios y permisos.':sections.find(s=>s[0]===page)?.[1]+'.',page==='cumplimiento'?'Solo pedidos y movimientos de tus puntos asignados. Los pagos y conciliaciones son registros; no se procesan pagos.':page==='comisiones'?'Proyecciones según la política de tu organización. Sin procesamiento de pagos.':ownerMode()?'Datos de toda la red · cada registro conserva su organización.':'Información de '+esc(currentOrg()?.name)+'.')+`<div class="toolbar"><label>Buscar en esta página <input id="search" type="search" placeholder="Escribe para filtrar"></label>${page==='catalogo'&&can('orders.create')?`<button class="btn primary" data-action="cart">Revisar pedido (${cart.length})</button>`:''}</div><div id="data-list">${tableView(page,rows)}</div><div class="toolbar"><span class="data-summary">${rows.length} registros · Página ${offset/100+1}</span><div><button class="btn light small" data-action="previous" ${offset===0?'disabled':''}>Anterior</button> <button class="btn light small" data-action="next" ${raw.length<100?'disabled':''}>Siguiente</button></div></div>`;
   content+=managementTools(page);
  } else content=title('Sección no disponible.','Tu cuenta no tiene permiso para acceder a esta sección.')+'<a class="btn primary" href="#inicio">Volver a mi espacio</a>';
  if(version===renderVersion){app.innerHTML=shell(content,page);setMenu(false);}
 } catch(error){if(version!==renderVersion)return;if(error.status===401){session=null;app.innerHTML=authPage(false);checkConfiguration(version);}else {const message='<div class="empty-state"><h2>No pudimos cargar esta sección.</h2><p>'+esc(error.name==='TimeoutError'?'La conexión tardó demasiado. Puedes seguir navegando o volver a intentar.':error.message)+'</p><button class="btn primary" data-action="refresh-session">Reintentar</button></div>';app.innerHTML=session?shell(message,page):header()+message;}}
}
async function checkConfiguration(version){try{const health=await api('health');if(version!==renderVersion||health.configured)return;const form=app.querySelector('.auth-form form');if(form){form.querySelector('.form-feedback').innerHTML='<p class="form-message">Estamos habilitando el acceso a Surtiva. El registro y el ingreso todavía no están disponibles.</p>';form.querySelector('button[type="submit"]').disabled=true;}}catch{/* The server still fails closed if configuration cannot be checked. */}}
function dialog(titleText,body){modal.innerHTML=`<div class="dialoghead"><h2>${esc(titleText)}</h2><button class="btn light small" data-action="close" aria-label="Cerrar">✕</button></div><div class="dialogbody">${body}<div class="form-feedback" role="status" aria-live="polite"></div></div>`;modal.showModal();}
function managementTools(page){
 if(reviewing())return '';
 if(!rows.length)return '';
 const invitations={vendedores:['seller','Invitar vendedor'],clientes:['merchant','Invitar comercio'],puntos:['fulfillment_partner','Invitar aliado'],invitaciones:['seller','Crear invitación']};
 const entities={catalogo:['product','Agregar producto'],proveedores:['supplier','Agregar proveedor']};
 return '<div class="toolbar">'+(manager()&&(ownerMode()||currentOrg()?.kind==='distribuidor')&&invitations[page]&&(page!=='puntos'||session.isAdmin)?'<button class="btn primary" data-action="invite" data-role="'+invitations[page][0]+'">'+invitations[page][1]+'</button>':'')+(manager()&&entities[page]?'<button class="btn primary" data-action="create-entity" data-kind="'+entities[page][0]+'">'+entities[page][1]+'</button>':'')+(manager()&&!ownerMode()&&page==='catalogo'?'<button class="btn light" data-action="catalog-access">Administrar catálogo habilitado</button>':'')+(manager()&&page==='pedidos'?'<button class="btn light" data-action="assign-point">Asignar punto de cumplimiento</button>':'')+(page==='miinventario'?'<button class="btn light" data-action="retail-edit">Editar inventario local</button><button class="btn primary" data-action="retail-sale">Registrar venta local</button>':'')+'</div>';
}
function emptyView(page){
 const copy={vendedores:['Aún no tienes vendedores','Invita a una persona a tu equipo. Podrá ingresar después de verificar su correo y recibir aprobación.','invite','seller','Invitar vendedor'],clientes:['Aún no tienes comercios','Vincula una organización comercial mediante una invitación y aprobación.','invite','merchant','Agregar primer comercio'],puntos:['Aún no tienes aliados de cumplimiento','Invita a un aliado para coordinar los pedidos que le asignes.','invite','fulfillment_partner','Invitar aliado'],proveedores:['Aún no tienes proveedores','Registra el primer proveedor de tu organización.','create-entity','supplier','Agregar proveedor'],catalogo:['Tu catálogo está vacío',manager()?'Agrega productos para comenzar a recibir pedidos.':'Tu distribuidor todavía no ha habilitado productos para tu cuenta.','create-entity','product','Agregar producto'],pedidos:['Aún no hay pedidos',role()==='fulfillment_partner'?'Aquí aparecerán únicamente los pedidos que te asignen.':'Los pedidos registrados aparecerán aquí con su estado y seguimiento.'],inventario:['Aún no hay inventario','Agrega productos y confirma sus existencias antes de preparar pedidos.'],miinventario:['Tu inventario local está vacío','Las compras entregadas se incorporarán aquí. Después podrás registrar tus ventas locales.'],ventas:['Aún no hay ventas locales','Registra una venta desde tu inventario local cuando tengas existencias.'],cartera:['No hay facturas pendientes','Aquí consultarás los documentos de tus pedidos entregados.'],comisiones:['Aún no hay comisiones','Se generarán con tus pedidos según la política de tu organización.'],seguimiento:['Aún no hay seguimientos','Abre uno de tus clientes para registrar una nota y el próximo contacto.'],cumplimiento:['No hay despachos asignados','Los compromisos de stock y despachos aparecerán al asignarte pedidos.'],invitaciones:['Aún no has enviado invitaciones','Crea un enlace para compartir con la persona que quieres incorporar.','invite','seller','Crear invitación'],usuarios:['Esta organización aún no tiene usuarios','Aprueba una solicitud para asignar la primera membresía.']};
 const [heading,detail,action,value,label]=copy[page]||['Sin resultados','No encontramos registros con este filtro.'];
 const button=manager()&&(ownerMode()||currentOrg()?.kind==='distribuidor')&&action&&(value!=='fulfillment_partner'||session.isAdmin)?'<button class="btn primary" data-action="'+action+'" data-'+(action==='invite'?'role':'kind')+'="'+value+'">'+label+'</button>':'';
 const link=page==='pedidos'&&can('orders.create')?'<a class="btn primary" href="#catalogo">Explorar catálogo</a>':page==='ventas'?'<a class="btn primary" href="#miinventario">Ver inventario local</a>':page==='seguimiento'?'<a class="btn primary" href="#clientes">Ver clientes</a>':'';
 return '<section class="empty-state panel"><h2>'+heading+'</h2><p>'+detail+'</p>'+button+link+'</section>';
}
function recoveryCodePage(){return header()+`<main id="contenido" class="auth-page"><section class="auth-intro"><h1>Verifica tu recuperación.</h1><p>Introduce el código del correo más reciente. Después podrás elegir una nueva contraseña.</p></section><section class="auth-form"><h2>Código de recuperación</h2><form id="verify-recovery"><label class="field">Correo electrónico<input name="email" type="email" autocomplete="email" maxlength="254" value="${esc(recoveryEmail)}" required></label><label class="field">Código del correo<input name="token" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" minlength="6" maxlength="10" required></label><div class="form-feedback" role="status" aria-live="polite">${authNotice?`<p class="form-message">${esc(authNotice)}</p>`:''}</div><button class="btn primary" type="submit">Verificar código</button><a class="secondary-link" href="#recuperar">Solicitar otro correo</a><a class="secondary-link" href="#ingresar">Volver al ingreso</a></form></section></main>`;}
function ownerActivationPage(){return header()+'<main id="contenido" class="auth-page"><section class="auth-intro"><span class="mk-eyebrow">PROPIETARIO DE SURTIVA</span><h1>Administrador maestro.</h1><p>Administra toda la red: organizaciones, usuarios, permisos y operaciones. Tu cuenta pertenece a Surtiva y conserva acceso global.</p></section><section class="auth-form"><h2>Activar mi cuenta maestra</h2><form id="register-owner"><label class="field">Nombre completo<input name="name" autocomplete="name" maxlength="100" required></label><label class="field">Correo del propietario<input name="email" type="email" autocomplete="email" maxlength="254" required></label><label class="field">Contraseña<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></label><small>Usa al menos 12 caracteres. El acceso maestro se activa al verificar el correo autorizado del propietario.</small><div class="form-feedback" role="status" aria-live="polite"></div><button class="btn primary" type="submit">Activar administración maestra</button><a class="secondary-link" href="#ingresar">Ya tengo una cuenta</a></form></section></main>';}
function confirmationPage(){return header()+'<main id="contenido" class="auth-page"><section class="auth-intro"><h1>Verifica tu correo.</h1><p>Solicita un nuevo enlace para la cuenta que ya registraste. Usa el correo más reciente y ábrelo en este mismo navegador.</p></section><section class="auth-form"><h2>Reenviar confirmación</h2><form id="resend"><label class="field">Correo electrónico<input name="email" type="email" autocomplete="email" maxlength="254" required></label><div class="form-feedback" role="status" aria-live="polite">'+(authNotice?'<p class="form-message">'+esc(authNotice)+'</p>':'')+'</div><button class="btn primary" type="submit">Enviar nuevo enlace</button><a href="#ingresar">Ya verifiqué mi correo: ingresar</a></form></section></main>';}
function recoveryPage(change=false){return header()+'<main id="contenido" class="auth-page"><section class="auth-intro"><h1>'+ (change?'Elige tu nueva contraseña.':'Recupera tu acceso.')+'</h1><p>Tu organización y tus permisos se conservan.</p></section><section class="auth-form"><form id="'+(change?'password':'recover')+'">'+(change?'<label class="field">Nueva contraseña<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label>':'<label class="field">Correo electrónico<input name="email" type="email" autocomplete="email" required></label>')+'<div class="form-feedback" role="status">'+(authNotice?'<p class="form-message">'+esc(authNotice)+'</p>':'')+'</div><button class="btn primary" type="submit">'+(change?'Guardar contraseña':'Enviar correo de recuperación')+'</button><a href="#ingresar">Volver al ingreso</a></form></section></main>';}
function invitationDialog(selected){dialog('Invitar a tu red','<form id="invitation">'+organizationField()+'<label>Nombre de la persona o negocio<input name="name" maxlength="100" required></label><label>Correo de quien recibirá acceso<input name="email" type="email" maxlength="254" required></label><label>Perfil<select name="role">'+Object.entries(roles).filter(([r])=>r!=='distributor_admin'&&(r!=='fulfillment_partner'||session.isAdmin)).map(([r,label])=>'<option value="'+r+'" '+(r===selected?'selected':'')+'>'+label+'</option>').join('')+'</select></label><p class="scope-note">Obtendrás un enlace válido durante 7 días para compartir. El acceso requiere correo verificado y aprobación de Surtiva.</p><button class="btn primary" type="submit">Crear enlace de invitación</button></form>');}
function network(){return title('Organizaciones de la red.','Administración de empresas y estados; tu gestión global permanece en Mi gestión.')+table(['Organización','Tipo','Estado','Plan',''],session.organizations.map(o=>'<tr><td>'+esc(o.name)+(o.is_test?'<small>Organización de prueba</small>':'')+'</td><td>'+esc(o.kind)+'</td><td>'+badge(o.status)+'</td><td>'+esc(o.plan_code)+'</td><td><button class="btn light small" data-action="select-org" data-id="'+o.id+'">Gestionar organización</button> '+(o.kind!=='plataforma'?'<button class="btn light small" data-action="org-status" data-id="'+o.id+'">Cambiar estado</button>':'')+'</td></tr>').join(''));}
function organizationField(){return ownerMode()?'<label>Proveedor responsable<select name="organizationContext" required><option value="">Selecciona para esta operación</option>'+session.organizations.filter(o=>o.kind==='distribuidor'&&o.status==='active'&&!o.is_test).map(o=>'<option value="'+o.id+'">'+esc(o.name)+'</option>').join('')+'</select></label>':'';}
async function profileReviewPage(){workspaceMode=false;reviewState=null;return title('Revisar perfiles.','Tu misma cuenta maestra. Revisa cada experiencia sin compartir contraseñas ni cambiar tus permisos.')+'<div class="profile-review-grid">'+Object.entries(roles).map(([value,label])=>'<article class="panel work-panel"><span class="mk-eyebrow">ESPACIO DE TRABAJO</span><h2>'+label+'</h2><p>'+({distributor_admin:'Catálogo, inventario, pedidos y equipo de su organización.',seller:'Clientes asignados, catálogo habilitado y seguimiento.',merchant:'Compras, cartera, inventario y ventas locales.',fulfillment_partner:'Pedidos asignados, despacho y conciliación.'}[value])+'</p><button class="btn primary" data-action="review-profile" data-role="'+value+'">Revisar '+label.toLowerCase()+' ↗</button></article>').join('')+'</div>';}
async function beginReview(chosen){
 const members=await allData('memberships');
 const matches=members.filter(m=>m.role_id===chosen&&m.status==='active'&&session.organizations.some(o=>o.id===m.organization_id&&o.status==='active'));
 dialog('Revisar '+roles[chosen],'<form id="review-profile-form"><input type="hidden" name="role" value="'+chosen+'"><label>Cuenta a revisar<select name="member"><option value="">Vista de perfil sin cuenta asignada</option>'+(chosen==='distributor_admin'?session.organizations.filter(o=>o.kind==='distribuidor'&&o.status==='active'&&!o.is_test).map(o=>'<option value="org:'+o.id+'" data-org="'+o.id+'" selected>'+esc(o.name)+' · vista de organización</option>').join(''):'')+matches.map(m=>'<option value="'+m.id+'" data-org="'+m.organization_id+'">'+esc(orgName(m.organization_id))+' · '+esc(m.profiles?.name||m.user_id.slice(0,8))+'</option>').join('')+'</select></label><p class="scope-note">'+(matches.length?'Las cuentas activas muestran sus datos reales bajo sus políticas de acceso.':chosen==='distributor_admin'?'Puedes revisar el catálogo y la operación real de un distribuidor, aunque aún no tenga un usuario activo.':'Todavía no hay usuarios activos con este perfil. Puedes revisar su estructura y estados vacíos; los datos aparecerán cuando apruebes cuentas y asignaciones.')+'</p><button class="btn primary">Abrir perfil</button></form>');
}
async function openSelectedReview(fields){
 const selected=document.querySelector('#review-profile-form select').selectedOptions[0];
 reviewState={role:fields.role,member:fields.member?.startsWith('org:')?null:fields.member||null,organization:fields.member?.startsWith('org:')?selected.dataset.org:null};workspaceMode=false;
 organization=selected.dataset.org||session.organizations.find(o=>o.kind===({merchant:'comercio',fulfillment_partner:'cumplimiento'}[fields.role]||'distribuidor')&&!o.is_test)?.id||'';
 cart=[];catalogFilters={query:'',category:'',supplier:'',sort:'discovery',limit:24};modal.close();location.hash='inicio';await render();
}
async function agentsPage(){crmAgents=await allData('commercial_agents');return '<div class="workspace-heading"><div><span class="mk-eyebrow">EQUIPO EXTENDIDO</span><h1>Agentes y responsables</h1><p>Asigna oportunidades a personas o agentes digitales. La ejecución actual es manual; no se envían mensajes ni se ejecutan agentes automáticamente.</p></div><button class="btn primary" data-action="agent-new">+ Registrar responsable</button></div><div class="profile-review-grid">'+crmAgents.map(a=>'<article class="panel work-panel"><span class="pill">'+(a.kind==='human'?'Persona':'Agente digital · ejecución manual')+'</span><h2>'+esc(a.name)+'</h2><p>'+esc(a.instructions)+'</p><a class="btn light" href="#prospeccion">Ver oportunidades</a></article>').join('')+(crmAgents.length?'':'<section class="panel quiet-state"><h3>Define quién atiende cada oportunidad</h3><p>Registra un responsable y asígnalo desde Prospección.</p></section>')+'</div>';}
function agentDialog(){dialog('Registrar responsable','<form id="agent"><label>Nombre<input name="name" maxlength="150" required></label><label>Tipo<select name="kind"><option value="human">Persona</option><option value="digital">Agente digital · coordinación manual</option></select></label><label>Instrucciones de trabajo<textarea name="instructions" maxlength="2000" required></textarea></label><p class="scope-note">Este registro organiza asignaciones; no activa servicios externos.</p><button class="btn primary">Guardar responsable</button></form>');}
async function prospectDialog(id){
 if(!crmAgents.length)crmAgents=await allData('commercial_agents');const p=crmProspects.find(p=>p.id===id)||{};
 const options=(values,current)=>values.map(([v,label])=>'<option value="'+v+'" '+(current===v?'selected':'')+'>'+label+'</option>').join('');
 dialog(p.id?'Actualizar oportunidad':'Registrar prospecto','<form id="prospect"><input type="hidden" name="id" value="'+(p.id||'')+'"><label>Negocio o cliente<input name="name" value="'+esc(p.name)+'" maxlength="150" required></label><div class="form-two"><label>Ciudad<input name="city" value="'+esc(p.city)+'" maxlength="120" required></label><label>Contacto<input name="contact" value="'+esc(p.contact)+'" maxlength="200" required></label></div><div class="form-two"><label>Canal<select name="channel">'+options(['visita','telefono','whatsapp','referido','web','otro'].map(v=>[v,v]),p.channel)+'</select></label><label>Etapa<select name="status">'+options(['nuevo','contactado','visita','propuesta','ganado','descartado'].map(v=>[v,v]),p.status)+'</select></label></div><label>Responsable<select name="agentId"><option value="">Sin asignar</option>'+crmAgents.map(a=>'<option value="'+a.id+'" '+(p.agent_id===a.id?'selected':'')+'>'+esc(a.name)+'</option>').join('')+'</select></label><div class="form-two"><label>Próximo contacto<input type="date" name="nextDate" value="'+esc(p.next_date||'')+'"></label><label>Valor estimado COP<input type="number" name="estimatedValue" min="0" step="0.01" value="'+(Number(p.estimated_value)||0)+'"></label></div><label>Notas<textarea name="notes" maxlength="2000">'+esc(p.notes)+'</textarea></label><button class="btn primary">Guardar oportunidad</button></form>');
}
async function assignSellerDialog(client){const sellers=(await allData('sellers')).filter(s=>s.organization_id===client.organization_id);dialog('Asignar responsable a '+client.name,'<form id="assign-seller" data-id="'+client.id+'"><label>Vendedor<select name="sellerId" required><option value="">Selecciona un vendedor</option>'+sellers.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join('')+'</select></label><p class="scope-note">'+(sellers.length?'El seguimiento quedará asociado a este responsable.':'Invita primero un vendedor desde Equipo de ventas.')+'</p><button class="btn primary" '+(!sellers.length?'disabled':'')+'>Guardar asignación</button></form>');}
async function entityDialog(kind){let extra='';if(kind==='customer'){const sellers=await allData('sellers');extra=`<label>Ciudad<input name="city" maxlength="120"></label><label>Vendedor asignado<select name="sellerId"><option value="">Sin asignar</option>${sellers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label>`;}if(kind==='seller')extra='<label>Territorio<input name="territory" maxlength="120"></label>';if(kind==='point')extra='<label>Ciudad<input name="city" maxlength="120"></label>';if(kind==='supplier')extra='<label>Contacto<input name="contact" maxlength="200"></label>';if(kind==='product')extra='<label>SKU<input name="sku" maxlength="50" required></label><label>Categoría<input name="category" maxlength="120" required></label><label>Precio base COP<input name="price" type="number" step="0.01" min="0.01" required></label>';dialog('Agregar registro',`<form id="entity" data-kind="${kind}">${organizationField()}<label>Nombre<input name="name" maxlength="150" required></label>${extra}<button class="btn primary" type="submit">Guardar</button></form>`);}
async function catalogDialog(){const [sellers,customers]=await Promise.all([allData('sellers'),allData('clients')]);dialog('Catálogo habilitado',`<form id="catalog-access"><label>Producto de esta página<select name="productId">${rows.map(p=>`<option value="${p.id}">${esc(p.sku)} · ${esc(p.title)}</option>`).join('')}</select></label><label>Perfil y asignación<select name="entity" required><option value="">Selecciona una cuenta</option>${sellers.map(s=>`<option value="seller:${s.id}">Vendedor · ${esc(s.name)}</option>`).join('')}${customers.map(c=>`<option value="merchant:${c.id}">Comercio · ${esc(role()==='merchant'?c.distributor_name||c.name:c.name)}</option>`).join('')}</select></label><label>Acceso<select name="enabled"><option value="true">Habilitar producto</option><option value="false">Revocar acceso al producto</option></select></label><button class="btn primary" type="submit">Guardar permiso</button></form>`);}
async function assignDialog(){const orders=rows.filter(o=>['aprobacion','recibido','preparando'].includes(o.status));if(!orders.length){dialog('Asignar cumplimiento','<p>No hay pedidos pendientes de asignación.</p>');return;}dialog('Seleccionar pedido','<form id="choose-fulfillment"><label>Pedido<select name="id" required>'+orders.map(o=>'<option value="'+o.id+'">'+esc(o.number)+' · '+esc(orgName(o.organization_id))+'</option>').join('')+'</select></label><button class="btn primary">Ver puntos disponibles</button></form>');}
async function fulfillmentDialog(id){const order=rows.find(o=>o.id===id);if(ownerMode())organization=order.organization_id;const points=await api(scoped('data/fulfillment_nodes'));if(!points.length){dialog('Sin puntos vinculados','<p>Esta organización aún no tiene puntos de cumplimiento vinculados. Revisa sus alianzas antes de asignar el pedido.</p>');return;}dialog('Asignar cumplimiento · '+order.number,'<form id="assign-point"><input type="hidden" name="id" value="'+id+'"><label>Punto de cumplimiento<select name="pointId" required>'+points.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('')+'</select></label><button class="btn primary">Asignar</button></form>');}
function retailDialog(sale=false){dialog(sale?'Registrar venta local':'Editar inventario local',`<form id="${sale?'retail-sale':'retail-edit'}" data-key="${crypto.randomUUID()}"><label>Producto<select name="item" required>${rows.map(r=>`<option value="${r.customer_id}:${r.product_id}">${esc(r.productTitle||r.product_id)} · ${r.quantity} unidades</option>`).join('')}</select></label><label>${sale?'Unidades vendidas':'Existencias físicas'}<input name="quantity" type="number" min="${sale?1:0}" step="1" required></label>${sale?'<p class="scope-note">El total se calcula con el precio local vigente y descuenta inventario. No procesa ningún pago.</p>':'<label>Precio local COP<input name="price" type="number" min="0.01" step="0.01" required></label>'}<button class="btn primary" type="submit">Guardar</button></form>`);}
async function orderDialog(id){await orderFlow.open(id);}
async function cartDialog(){if(cart.length&&ownerMode())organization=cart[0].organization_id;if(!cart.length){notify('Agrega productos al pedido.');return;}const customers=(await allData('clients')).filter(c=>c.organization_id===cart[0].organization_id);if(!customers.length){dialog('Completa la vinculación comercial','<p class="scope-note">Aún no tienes una cuenta comercial vinculada a '+esc(orgName(cart[0].organization_id))+'. Conservamos tu selección. El administrador debe vincular el comercio y su vendedor antes de registrar el pedido.</p><a class="btn primary" href="#clientes">Ver cuentas comerciales</a>');return;}dialog('Revisar pedido',`<form id="create-order">${`<label>${role()==='merchant'?'Cuenta de compra':'Cliente'}<select name="customerId" required><option value="">Selecciona un cliente</option>${customers.map(c=>`<option value="${c.id}">${esc(role()==='merchant'?c.distributor_name||c.name:c.name)}</option>`).join('')}</select></label>`}${cart.map(p=>`<label>${esc(p.title)}<input type="number" name="qty-${p.id}" min="1" max="99999" step="1" value="${p.quantity}" required></label>`).join('')}<p class="scope-note">El precio final se calcula según las cantidades y el catálogo vigente. ${role()==='seller'?'Surtiva revisa y autoriza; el distribuidor confirma disponibilidad.':''}</p><button class="btn primary" type="submit">Registrar pedido</button><button class="btn light" type="button" data-action="clear-cart">Vaciar pedido</button></form>`);}
async function approvalEntities(){
 const form=document.querySelector('#review-access');if(!form)return;
 const chosen=form.elements.role.value,selected=form.elements.organizationId.value;
 const kind=chosen==='merchant'?'comercio':chosen==='fulfillment_partner'?'cumplimiento':'distribuidor';
 form.elements.organizationId.innerHTML=(chosen==='seller'?'<option value="">Selecciona un distribuidor</option>':'<option value="">Crear organización independiente</option>')+session.organizations.filter(o=>o.kind===kind&&o.status==='active').map(o=>'<option value="'+o.id+'">'+esc(o.name)+'</option>').join('');
 if([...form.elements.organizationId.options].some(o=>o.value===selected))form.elements.organizationId.value=selected;
 form.querySelector('#new-org').hidden=!!form.elements.organizationId.value||chosen==='seller';
 form.elements.organizationId.required=chosen==='seller';
}
async function reviewDialog(id){const request=rows.find(r=>r.id===id);dialog('Revisar acceso', '<p class="scope-note">'+esc(request.profiles?.name||'Solicitante')+' · '+esc(request.organization_name)+'</p><form id="review-access" data-id="'+id+'"><label>Rol aprobado<select name="role">'+Object.entries(roles).map(([value,label])=>'<option value="'+value+'" '+(value===request.requested_role?'selected':'')+'>'+label+'</option>').join('')+'</select></label><label>Organización<select name="organizationId"></select></label><label id="new-org">Nombre de organización<input name="organizationName" maxlength="120" value="'+esc(request.organization_name)+'"></label><p class="scope-note">Comercios y aliados tienen organización propia. Los vendedores pertenecen a un distribuidor. Una invitación vincula la relación comercial al aprobar.</p><button class="btn primary" name="decision" value="aprobar" type="submit">Aprobar acceso</button><button class="btn light" name="decision" value="rechazar" type="submit" formnovalidate>Rechazar solicitud</button></form>');await approvalEntities();}

document.addEventListener('click',async event=>{
 if(event.target.closest('[href="#contenido"]')){event.preventDefault();const main=document.querySelector('#contenido');main?.setAttribute('tabindex','-1');main?.focus();return;}
 const button=event.target.closest('[data-action]');if(!button)return;const {action,id}=button.dataset;button.disabled=true;
 if(reviewing()&&!['owner-home','logout','menu','close-menu','account','category','present','close','previous','next','product-detail','catalog-more','order'].includes(action)){notify('Vista de revisión: vuelve a tu gestión para hacer cambios.');button.disabled=false;return;}
 if(ownerMode()){const row=rows.find(r=>r.id===id||r.product_id===id);if(row?.organization_id)organization=row.organization_id;}
 try {
  if(await orderFlow.action(action,button))return;
  if(await visits.action(action,button))return;
  if(action==='account')accountDialog();
  if(action==='logout'){workspaceMode=false;reviewState=null;await api('auth/logout',{method:'POST',body:{}});session=null;organization='';cart=[];rows=[];location.hash='portada';await render();}
  if(action==='owner-home'){workspaceMode=false;reviewState=null;organization='';cart=[];location.hash='red';await render();}
  if(action==='review-profile')await beginReview(button.dataset.role);
  if(action==='product-detail')productDialog(id);
  if(action==='edit-product'){const p=catalogProducts.find(p=>p.id===id);organization=p.organization_id;modal.close();dialog('Editar producto · '+p.sku,'<form id="edit-product" data-id="'+p.id+'"><label>Nombre<input name="title" maxlength="200" value="'+esc(p.title)+'" required></label><label>Categoría<input name="category" maxlength="120" value="'+esc(p.category)+'" required></label><label>Precio base COP<input name="price" type="number" min="0" step="0.01" value="'+p.price+'" required></label><label>Estado<select name="active"><option value="true" '+(p.active?'selected':'')+'>Activo</option><option value="false" '+(!p.active?'selected':'')+'>Inactivo</option></select></label><button class="btn primary">Guardar producto</button></form>');}
  if(action==='catalog-more')await refreshCatalog(true);
  if(action==='prospect-new'||action==='prospect-edit')await prospectDialog(id);
  if(action==='agent-new')agentDialog();
  if(action==='radar-followup'){const client=radarClients.find(c=>c.id===id);rows=[client];organization=client.organization_id;if(!client.seller_id){await assignSellerDialog(client);return;}dialog('Seguimiento · '+client.name,'<form id="followup" data-id="'+client.id+'" data-seller="'+client.seller_id+'"><label>Nota<textarea name="note" maxlength="2000" required></textarea></label><label>Próximo contacto<input name="nextDate" type="date" required></label><button class="btn primary">Guardar seguimiento</button></form>');}
  if(action==='present'){document.body.classList.toggle('catalog-presentation');button.setAttribute('aria-pressed',String(document.body.classList.contains('catalog-presentation')));button.textContent=document.body.classList.contains('catalog-presentation')?'Salir de presentación':'Modo presentación';}
  if(action==='category'){catalogFilters.category=button.dataset.category||'';catalogFilters.query='';document.querySelector('#catalog-query').value='';await refreshCatalog();if(catalogFilters.category)document.querySelector('.catalog-breadcrumb')?.scrollIntoView({block:'start',behavior:'instant'});else window.scrollTo({top:0,behavior:'instant'});}
  if(action==='refresh-session'){reads.clear();await render();}
  if(action==='menu')setMenu(!document.querySelector('.shell')?.classList.contains('mobile-open'));
  if(action==='close-menu')setMenu(false,true);
  if(action==='close')modal.close();
  if(action==='next'||action==='previous'){offset=Math.max(0,offset+(action==='next'?100:-100));await render();}
  if(action==='select-org'){workspaceMode=true;reviewState=null;organization=id;cart=[];offset=0;location.hash='inicio';}
  if(action==='add-product'){modal.close();const product=catalogProducts.find(p=>p.id===id);if(cart.length&&cart[0].organization_id!==product.organization_id)throw Error('Completa el pedido actual antes de comprar a otro distribuidor.');const existing=cart.find(p=>p.id===id);if(existing)existing.quantity++;else cart.push({...product,quantity:1});orderRequestKey=crypto.randomUUID();notify('Producto agregado al pedido');const cartButton=document.querySelector('[data-action=cart]');if(cartButton){cartButton.hidden=false;cartButton.textContent='Revisar pedido ('+cart.length+')';}}
  if(action==='cart')await cartDialog();
  if(action==='clear-cart'){cart=[];orderRequestKey=crypto.randomUUID();modal.close();await render();}
  if(action==='order')await orderDialog(id);
  if(action==='transition'){await api(scoped('orders/status'),{method:'POST',body:{id,status:button.dataset.status}});modal.close();await render();notify('Pedido actualizado');}
  if(action==='edit-stock'){const row=rows.find(r=>r.product_id===id);dialog('Actualizar existencias',`<form id="stock" data-id="${id}"><label>Cantidad física<input name="quantity" type="number" step="1" min="${row.reserved}" value="${row.quantity??''}" required></label><small>No puede ser inferior al stock comprometido.</small><button class="btn primary" type="submit">Guardar existencias</button></form>`);}
  if(action==='followup'){const customer=rows.find(r=>r.id===id);dialog('Seguimiento · '+customer.name,`<form id="followup" data-id="${id}" data-seller="${customer.seller_id||''}"><label>Nota<textarea name="note" maxlength="2000" required></textarea></label><label>Próximo contacto<input name="nextDate" type="date"></label><button class="btn primary" type="submit">Guardar seguimiento</button></form>`);}
  if(action==='invite')invitationDialog(button.dataset.role);
  if(action==='copy-invitation'){const input=modal.querySelector('#invitation-link');await navigator.clipboard.writeText(input.value);notify('Enlace copiado');}
  if(action==='org-status'){const org=session.organizations.find(o=>o.id===id);dialog('Estado de '+org.name,'<form id="org-status" data-id="'+id+'"><label>Estado<select name="status">'+['pending','active','suspended','rejected'].map(status=>'<option value="'+status+'" '+(org.status===status?'selected':'')+'>'+states[status]+'</option>').join('')+'</select></label><p class="scope-note">Solo una organización activa permite acceso a su operación.</p><button class="btn primary" type="submit">Guardar estado</button></form>');}
  if(action==='review')await reviewDialog(id);
  if(action==='assign-seller'){const sellers=(await allData('sellers')).filter(s=>s.organization_id===organization);dialog('Asignar vendedor',`<form id="assign-seller" data-id="${id}"><label>Vendedor<select name="sellerId"><option value="">Sin asignar</option>${sellers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><p class="scope-note">La asignación se usará para los próximos pedidos y seguimientos.</p><button class="btn primary" type="submit">Guardar asignación</button></form>`);}
  if(action==='create-entity')await entityDialog(button.dataset.kind);
  if(action==='catalog-access')await catalogDialog();
  if(action==='assign-point')await assignDialog();
  if(action==='retail-edit'||action==='retail-sale')retailDialog(action==='retail-sale');
  if(action==='membership'){const row=rows.find(r=>r.id===id);await api('admin/membership',{method:'POST',body:{id,enabled:!row.active}});await render();}
 }catch(error){if(modal.open)modal.querySelector('.form-feedback').innerHTML=`<p class="form-message error">${esc(error.message)}</p>`;else notify(error.message);}finally{button.disabled=false;}
});
document.addEventListener('submit',async event=>{
 event.preventDefault();if(event.target.id==='complete-invitation'){await invitation.submit(event.target);return;}const form=event.target,fields=Object.fromEntries(new FormData(form)),button=event.submitter,feedback=form.querySelector('.form-feedback')||modal.querySelector('.form-feedback');
 if(button)button.disabled=true;if(feedback)feedback.innerHTML='';
 try{
  if(await orderFlow.submit(form))return;
  if(await visits.submit(form,fields))return;
  if(ownerMode()&&fields.organizationContext)organization=fields.organizationContext;
  if(form.id==='profile-photo')await saveProfilePhoto(fields.photo);
  if(form.id==='edit-product'){await api(scoped('products'),{method:'PATCH',body:{id:form.dataset.id,title:fields.title,category:fields.category,price:Number(fields.price),active:fields.active==='true'}});modal.close();await render();notify('Producto actualizado');}
  if(form.id==='prospect'){await api('admin/prospects',{method:fields.id?'PATCH':'POST',body:fields});modal.close();await render();notify('Prospecto guardado');}
  if(form.id==='agent'){await api('admin/agents',{method:'POST',body:fields});modal.close();await render();notify('Responsable registrado');}
  if(form.id==='review-profile-form'){await openSelectedReview(fields);}
  if(form.id==='register-owner'){const result=await api('auth/register-owner',{method:'POST',body:fields});form.reset();feedback.innerHTML='<p class="form-message">'+esc(result.message)+'</p><a href="#confirmar-correo">Necesito otro enlace de confirmación</a>';}
  if(form.id==='register'){const result=await api('auth/register',{method:'POST',body:{...fields,invitationToken:inviteToken()}});form.reset();feedback.innerHTML=`<p class="form-message">${esc(result.message)}</p><a href="#confirmar-correo">Necesito otro enlace de confirmación</a>`;}
  if(form.id==='login'){workspaceMode=false;reviewState=null;await api('auth/login',{method:'POST',body:fields});if(inviteToken()){location.hash='unirme';await invitation.render();return;}session=await api('session');organization='';location.hash=session.isAdmin?'red':'inicio';await render();}
  if(form.id==='create-order'){const items=cart.map(p=>({productId:p.id,quantity:Number(fields['qty-'+p.id])}));await api(scoped('orders'),{method:'POST',body:{customerId:fields.customerId,items,requestKey:orderRequestKey}});cart=[];orderRequestKey=crypto.randomUUID();modal.close();location.hash='pedidos';notify('Pedido registrado');}
  if(form.id==='stock'){await api(scoped('inventory'),{method:'PATCH',body:{productId:form.dataset.id,quantity:Number(fields.quantity)}});modal.close();await render();notify('Inventario actualizado');}
  if(form.id==='followup'){await api(scoped('followups'),{method:'POST',body:{...fields,customerId:form.dataset.id,sellerId:form.dataset.seller}});modal.close();notify('Seguimiento guardado');}
  if(form.id==='review-access'){await api('admin/review',{method:'POST',body:{...fields,requestId:form.dataset.id,decision:button.value}});modal.close();await render();notify('Solicitud revisada');}
  if(form.id==='invitation'){const result=await api(scoped('invitations'),{method:'POST',body:fields});const link=location.origin+'/?invite='+encodeURIComponent(result.token)+'#unirme';dialog('Invitación lista','<p>'+esc(result.delivery==='accepted'?'El servicio de correo aceptó la invitación para '+fields.email+'.':result.deliveryReason==='over_email_send_rate_limit'?'Se alcanzó el límite de envío de correos. Comparte el enlace para que la persona pueda continuar.':'El servicio de correo no pudo enviar la invitación. Puedes compartir este enlace directamente.')+'</p><label>Enlace personal · válido 7 días<input id="invitation-link" readonly value="'+esc(link)+'"></label><button class="btn primary" data-action="copy-invitation">Copiar enlace</button><p class="scope-note">'+(result.directAccess?'La persona entra desde el enlace y completa sus datos. No tiene que registrarse de nuevo.':'Esta persona ya tiene una cuenta: entrará con ella para aceptar.')+' El acceso para operar queda pendiente de tu revisión.</p>');}
  if(form.id==='org-status'){await api('admin/status',{method:'POST',body:{kind:'organization',id:form.dataset.id,status:fields.status}});modal.close();await render();notify('Estado actualizado');}
  if(form.id==='resend'){const result=await api('auth/resend',{method:'POST',body:fields});feedback.innerHTML='<p class="form-message">'+esc(result.message)+'</p>';}
  if(form.id==='recover'){const result=await api('auth/recover',{method:'POST',body:fields});recoveryEmail=fields.email.trim();feedback.innerHTML='<p class="form-message">'+esc(result.message)+'</p><a class="secondary-link" href="#verificar-recuperacion">Introducir código del correo</a>';}
  if(form.id==='verify-recovery'){await api('auth/verify-recovery',{method:'POST',body:fields});form.reset();recoveryEmail='';authNotice='';location.hash='nueva-clave';notify('Código verificado. Elige tu nueva contraseña.');}
  if(form.id==='password'){await api('auth/password',{method:'POST',body:fields});await api('auth/logout',{method:'POST',body:{}});location.hash='ingresar';notify('Contraseña actualizada. Ingresa de nuevo.');}
  if(form.id==='entity'){await api(scoped('entities'),{method:'POST',body:{kind:form.dataset.kind,payload:fields}});modal.close();await render();notify('Registro creado');}
  if(form.id==='catalog-access'){const [entityKind,entityId]=fields.entity.split(':');await api(scoped('catalog/access'),{method:'POST',body:{productId:fields.productId,entityKind,entityId,enabled:fields.enabled==='true'}});modal.close();notify('Permiso de catálogo actualizado');}
  if(form.id==='choose-fulfillment')await fulfillmentDialog(fields.id);
  if(form.id==='assign-point'){await api(scoped('orders/assign'),{method:'POST',body:fields});modal.close();await render();notify('Punto asignado');}
  if(form.id==='assign-seller'){await api(scoped('clients/assign'),{method:'POST',body:{id:form.dataset.id,sellerId:fields.sellerId}});modal.close();await render();notify('Vendedor asignado');}
  if(form.id==='retail-edit'||form.id==='retail-sale'){const [customerId,productId]=fields.item.split(':');if(form.id==='retail-edit')await api(scoped('retail'),{method:'PATCH',body:{customerId,productId,quantity:Number(fields.quantity),price:Number(fields.price)}});else await api(scoped('retail/sale'),{method:'POST',body:{customerId,items:[{productId,quantity:Number(fields.quantity)}],requestKey:form.dataset.key}});modal.close();await render();notify('Operación local registrada');}
 }catch(error){if(feedback)feedback.innerHTML=`<p class="form-message error">${esc(error.message)}</p>`;else notify(error.message);}finally{if(button)button.disabled=false;}
});
document.addEventListener('change',event=>{
 if(['catalog-supplier','catalog-sort'].includes(event.target.id)){catalogFilters[event.target.id.replace('catalog-','')]=event.target.value;refreshCatalog();}

 if(event.target.id==='organization'){organization=event.target.value;cart=[];rows=[];offset=0;orderRequestKey=crypto.randomUUID();render();}
 if(event.target.closest('#review-access')&&['organizationId','role'].includes(event.target.name))approvalEntities().catch(error=>notify(error.message));
});
function setMenu(open,restore=false){
 const shell=app.querySelector('.shell');if(!shell)return;
 shell.classList.toggle('mobile-open',open);document.body.classList.toggle('menu-is-open',open);
 shell.querySelector('.sidebar').inert=matchMedia('(max-width:760px)').matches&&!open;
 shell.querySelector('.mobile-toggle')?.setAttribute('aria-expanded',String(open));
 if(open)shell.querySelector('.menu-close')?.focus();else if(restore)shell.querySelector('.mobile-toggle')?.focus();
}
document.addEventListener('click',event=>{if(event.target.closest('.sidebar a[href]'))setMenu(false);},true);
matchMedia('(max-width:760px)').addEventListener('change',()=>setMenu(false));
document.addEventListener('keydown',event=>{
 if(event.key==='Escape')setMenu(false,true);
 if(event.key==='Tab'&&document.body.classList.contains('menu-is-open')){
  const nodes=[...document.querySelectorAll('.sidebar a,.sidebar button,.sidebar select')].filter(el=>el.getClientRects().length&&!el.disabled);
  const first=nodes[0],last=nodes.at(-1);
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
 }
});
document.addEventListener('input',event=>{if(event.target.id==='catalog-query'){catalogFilters.query=event.target.value;clearTimeout(catalogTimer);catalogTimer=setTimeout(()=>refreshCatalog(),280);return;}if(event.target.id==='search'){const query=event.target.value.toLocaleLowerCase('es');document.querySelector('#data-list').innerHTML=tableView(route(),rows.filter(r=>Object.values(r).some(v=>String(v).toLocaleLowerCase('es').includes(query))));}});
window.addEventListener('hashchange',()=>{authNotice='';offset=0;render();window.scrollTo(0,0);});
window.addEventListener('pageshow',event=>{if(event.persisted)render();});
window.addEventListener('focus',()=>{reads.clear();});
let orderWatch='',watchingOrders=false;
async function watchOrders(){
 if(watchingOrders||!session||reviewing()||handoffLocked()||document.hidden||modal.open||document.body.classList.contains('menu-is-open')||!['inicio','visitas','pedidos'].includes(route())||!can('orders.read')||document.activeElement?.matches('input,textarea,select'))return;
 watchingOrders=true;try{const list=await request(ownerMode()?'admin/data/orders':scoped('data/orders'));const next=JSON.stringify(list.map(o=>[o.id,o.status,o.total,o.revision]));if(orderWatch&&next!==orderWatch){reads.clear();await render(true);notify('Tus pedidos se actualizaron');}orderWatch=next;}catch{}finally{watchingOrders=false;}
}
setInterval(watchOrders,20000);

async function start(){
 animateBrand();
 const returned=readAuthReturn(location.href);
 if(returned){
  let page=returned.recovery?'nueva-clave':inviteToken()?'unirme':'ingresar';
  if(returned.error){authNotice=authMessage(returned.error);page=inviteToken()?'unirme':returned.recovery?'recuperar':'confirmar-correo';}
  else try{const client=await supabase();const {error}=await client.auth.initialize();if(error){authNotice=authMessage(error);page=returned.recovery?'recuperar':'ingresar';}else if(!returned.recovery)authNotice='Enlace procesado. Ingresa para consultar el estado de tu cuenta.';}catch(error){authNotice=error.message;page='ingresar';}
  history.replaceState(null,'',cleanAuthReturn(location.href,page));
 }
 if(inviteToken()&&!returned&&['portada','solicitar'].includes(route()))history.replaceState(null,'',location.pathname+location.search+'#unirme');
 await render();
 watchOrders();
}
start();





document.addEventListener('click',e=>{const button=e.target.closest('[data-invitation]');if(button)invitation.click(button);});
