import QRCode from 'qrcode';
import {esc,money,icon} from './commerce-ui.js';
export function visitWorkspace({api,allData,session,organization,role,readonly,dialog,notify,render,clearCache}){
 const sourceData=allData;allData=async table=>{if(!session()?.preview||!session()?.isAdmin)return sourceData(table);const result=[];for(let offset=0;;offset+=500){const page=await api('admin/data/'+table+'?test=true&limit=500&offset='+offset);result.push(...page);if(page.length<500)return result;}};
 let clients=[],orders=[],followups=[],lastAccess=null;
 const scope=(path,org)=>path+'?organization='+encodeURIComponent(org);
 const allowed=()=>!readonly()&&(session()?.isAdmin||['seller','distributor_admin'].includes(role()));
 async function page(){
  [clients,orders,followups]=await Promise.all(['clients','orders','followups'].map(allData));
  const today=new Date().toISOString().slice(0,10),due=followups.filter(f=>f.next_date&&f.next_date<=today).length;
  const ordered=[...clients].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));
  return `<section class="visit-workspace"><div class="visit-heading"><span>EN LA CALLE, TODO A MANO</span><h1>Vamos a vender.</h1><p>${clients.length?'Tus comercios, su próximo pedido y lo que sigue.':'Tu próxima relación comercial empieza con una visita.'}</p></div><div class="visit-actions"><button data-action="visit-new" ${allowed()?'':'disabled'}>${icon('person')}<b>Nuevo comercio</b><small>Acceso en cuatro datos</small></button><a href="#catalogo">${icon('search')}<b>Buscar producto</b><small>Encuentra el surtido</small></a><button data-action="visit-pick" ${allowed()?'':'disabled'}>${icon('bag')}<b>Nuevo pedido</b><small>Elige un comercio</small></button><button data-action="visit-pick" ${allowed()?'':'disabled'}>${icon('share')}<b>Compartir catálogo</b><small>QR o enlace privado</small></button></div><div class="visit-status"><a href="#pedidos"><b>${orders.filter(o=>['recibido','aprobacion','preparando','despachado'].includes(o.status)).length}</b> pedidos en curso ${icon('arrow')}</a><a href="#seguimiento"><b>${due}</b> contactos pendientes ${icon('arrow')}</a></div><div class="visit-list-heading"><h2>Mis comercios</h2><label>${icon('search')}<input id="visit-find" type="search" placeholder="Buscar negocio o ciudad" aria-label="Buscar comercio"></label></div><div class="visit-clients">${ordered.map(clientCard).join('')||`<div class="visit-empty"><h2>El primer comercio lo cambia todo</h2><p>Registra negocio, contacto, celular y ciudad. Se lleva su catálogo al escanear el QR.</p><button class="btn primary" data-action="visit-new" ${allowed()?'':'disabled'}>Preregistrar comercio</button></div>`}</div>${clients.length?`<section class="visit-opportunities"><h2>La próxima conversación</h2>${clients.filter(c=>orders.some(o=>o.customer_id===c.id&&o.status==='entregado'&&Date.now()-new Date(o.created_at).getTime()>30*86400000)&&!orders.some(o=>o.customer_id===c.id&&Date.now()-new Date(o.created_at).getTime()<30*86400000)).slice(0,5).map(c=>`<button data-action="visit-client" data-id="${c.id}"><b>${esc(c.name)}</b><span>Hace más de 30 días de su última compra · revisar reposición ${icon('arrow')}</span></button>`).join('')||'<p>Con las primeras compras aparecerán aquí oportunidades de reposición.</p>'}</section>`:''}</section>`;
 }
 function clientCard(c){const pending=orders.filter(o=>o.customer_id===c.id&&['recibido','aprobacion','preparando','despachado'].includes(o.status));return `<article class="visit-client" data-search="${esc((c.name+' '+c.city).toLowerCase())}"><span class="visit-avatar">${esc(c.name.slice(0,1))}</span><div><h3>${esc(c.name)}</h3><p>${esc(c.city||'Sin ciudad')} ${c.contact_name?'· '+esc(c.contact_name):''}</p><small>${pending.length?pending.length+' pedidos en curso':'Listo para su próximo pedido'}</small></div><button class="btn light small" data-action="visit-client" data-id="${c.id}">Abrir ${icon('arrow')}</button></article>`;}
 function orgOptions(){return session().organizations.filter(o=>o.kind==='distribuidor'&&o.status==='active'&&(session().preview?o.is_test:!o.is_test));}
 function newDialog(){if(!allowed())return;const orgs=orgOptions();dialog('Nuevo comercio',`<form id="visit-register">${session().isAdmin?`<label>Proveedor / distribuidor<select name="organizationId" required>${orgs.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}</select></label>`:`<input type="hidden" name="organizationId" value="${organization()}">`}<label>Nombre del negocio<input name="name" maxlength="120" autocomplete="organization" placeholder="Ej. Variedades El Sol" required></label><label>Nombre de contacto<input name="contact" maxlength="100" autocomplete="name" required></label><div class="visit-form-row"><label>Celular<input name="phone" type="tel" inputmode="tel" autocomplete="tel" pattern="[+0-9 ()-]{7,24}" minlength="7" maxlength="24" required></label><label>Municipio / ciudad<input name="city" autocomplete="address-level2" maxlength="100" required></label></div><p class="visit-hint">Sin correo ni contraseña. Tendrá acceso únicamente a su catálogo y pedidos.</p><button class="btn primary" type="submit">Crear comercio y su acceso ${icon('arrow')}</button></form>`);}
 async function accessResult(access){lastAccess=access;const link=location.origin+'/c/#'+access.token;dialog('Comercio listo',`<div class="visit-access"><span class="visit-success">${icon('check')}</span><h3>${esc(access.name)}</h3><p>Escanea y empieza a elegir productos.</p><canvas id="visit-qr" aria-label="QR de acceso privado al catálogo"></canvas><div class="visit-access-actions"><a class="btn primary" href="${link}" target="_blank" rel="noopener noreferrer">Abrir catálogo ${icon('arrow')}</a><button class="btn light" data-action="visit-copy">Copiar enlace</button><a class="btn light" href="https://wa.me/?text=${encodeURIComponent('Hola, aquí tienes el catálogo de Surtiva para '+access.name+'. Puedes elegir productos y enviarnos tu pedido: '+link)}" target="_blank" rel="noopener noreferrer">Compartir por WhatsApp</a><button class="btn light" data-action="visit-present">Mostrar en esta tablet</button></div><small>Enlace privado · puedes revocarlo desde el comercio. Caduca en 90 días.</small></div>`);await QRCode.toCanvas(document.querySelector('#visit-qr'),link,{width:236,margin:3,errorCorrectionLevel:'M',color:{dark:'#0c2036',light:'#ffffff'}});}
 async function clientDialog(id){if(!clients.length)clients=await allData('clients');const c=clients.find(c=>c.id===id);if(!c)throw Error('Comercio no encontrado');
  const accesses=allowed()?await api(scope('commercial/accesses',c.organization_id)+'&client='+c.id):[];
  dialog(c.name,`<div class="visit-client-summary"><p>${esc(c.contact_name||'')} · ${esc(c.city||'')}</p>${c.phone?`<a href="tel:${esc(c.phone.replace(/[^+0-9]/g,''))}">${esc(c.phone)}</a>`:''}</div><div class="visit-access-actions"><button class="btn primary" data-action="visit-share" data-id="${c.id}" ${allowed()?'':'disabled'}>Mostrar / compartir catálogo ${icon('share')}</button><button class="btn light" data-action="visit-share" data-id="${c.id}" ${allowed()?'':'disabled'}>Preparar un pedido ${icon('bag')}</button><a href="#pedidos" class="btn light" data-action="close">Ver pedidos</a></div>${allowed()&&c.seller_id?`<button class="btn light small" data-action="visit-followup" data-id="${c.id}">Registrar seguimiento</button>`:''}${allowed()&&(session().isAdmin||role()==='distributor_admin')?`<button class="btn light small" data-action="visit-assign" data-id="${c.id}">Asignar responsable</button>`:''}<h3 class="visit-subtitle">Enlaces de este comercio</h3>${accesses.map(a=>`<article class="visit-link"><div><b>${a.status==='active'?'Activo':'Revocado'} ${new Date(a.expires_at)<new Date()?'· Caducado':''}</b><small>${a.last_access_at?'Última visita: '+new Date(a.last_access_at).toLocaleDateString('es-CO'):'Aún no ha abierto el catálogo'} · ${a.access_count} visitas</small></div>${a.status==='active'?`<button class="btn light small" data-action="visit-revoke" data-id="${a.id}" data-client="${c.id}" data-org="${c.organization_id}">Revocar</button>`:''}</article>`).join('')||'<p class="visit-hint">Crea un enlace para compartir el catálogo con este negocio.</p>'}`);
 }
 async function shareDialog(id){const c=clients.find(c=>c.id===id);if(!c)throw Error('Comercio no encontrado');const list=(await allData('products')).filter(p=>p.organization_id===c.organization_id&&p.active);dialog('Catálogo para '+c.name,`<form id="visit-share-form" data-client="${c.id}" data-org="${c.organization_id}"><label>Qué quieres compartir<select name="kind" id="visit-share-kind"><option value="all">Catálogo completo</option><option value="category">Una categoría</option><option value="selection">Selección de productos / pedido preparado</option></select></label><label id="visit-category-field" hidden>Categoría<select name="category">${[...new Set(list.map(p=>p.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><div id="visit-selection-field" hidden><label>Buscar productos<input id="visit-product-find" type="search" placeholder="Nombre o referencia"></label><div class="visit-product-select">${list.map(p=>`<label data-search="${esc((p.title+' '+p.sku).toLowerCase())}"><input type="checkbox" name="product" value="${p.id}"><span>${esc(p.title)}<small>${esc(p.sku)}</small></span><input type="number" name="qty-${p.id}" aria-label="Cantidad de ${esc(p.title)}" min="1" max="9999" value="1"></label>`).join('')}</div></div><p class="visit-hint">El enlace mantiene los productos autorizados y refleja sus cambios. El comercio revisa cantidades y precios antes de enviar.</p><button class="btn primary">Generar enlace y QR</button></form>`);}
 async function action(name,button){if(!name.startsWith('visit-'))return false;if(name==='visit-new')newDialog();
  if(name==='visit-pick'){if(!clients.length)clients=await allData('clients');dialog('Elige un comercio',clients.length?'<div class="visit-clients">'+clients.map(clientCard).join('')+'</div>':'<p>Preregistra el negocio antes de compartir su catálogo.</p><button class="btn primary" data-action="visit-new">Nuevo comercio</button>');}
  if(name==='visit-client')await clientDialog(button.dataset.id);
  if(name==='visit-share')await shareDialog(button.dataset.id);
  if(name==='visit-followup'){const c=clients.find(c=>c.id===button.dataset.id);dialog('Seguimiento · '+c.name,`<form id="visit-followup-form" data-client="${c.id}" data-org="${c.organization_id}" data-seller="${c.seller_id}"><label>Nota<textarea name="note" maxlength="2000" required></textarea></label><label>Próximo contacto<input name="nextDate" type="date"></label><button class="btn primary">Guardar seguimiento</button></form>`);}
  if(name==='visit-assign'){const c=clients.find(c=>c.id===button.dataset.id),sellers=(await allData('sellers')).filter(s=>s.organization_id===c.organization_id);dialog('Responsable · '+c.name,`<form id="visit-assign-form" data-client="${c.id}" data-org="${c.organization_id}"><label>Vendedor<select name="sellerId"><option value="">Atendido por administración</option>${sellers.map(s=>`<option value="${s.id}" ${s.id===c.seller_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><p class="visit-hint">Al cambiar el responsable, los enlaces anteriores dejan de funcionar. Genera uno nuevo para conservar la atribución correcta.</p><button class="btn primary">Guardar responsable</button></form>`);}
  if(name==='visit-copy'){await navigator.clipboard.writeText(location.origin+'/c/#'+lastAccess.token);notify('Enlace copiado');}
  if(name==='visit-revoke'){await api(scope('commercial/revoke',button.dataset.org),{method:'POST',body:{id:button.dataset.id}});await clientDialog(button.dataset.client);notify('Enlace revocado');}
  if(name==='visit-present'){dialog('Mostrar catálogo al cliente','<form id="visit-handoff"><p>El cliente verá únicamente su catálogo y pedido. Elige un PIN local para volver a tu espacio en este dispositivo.</p><label>PIN para volver al vendedor<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" autocomplete="off" required></label><button class="btn primary">Abrir modo cliente</button></form>');}
  return true;
 }
 async function submit(form,fields){if(!form.id.startsWith('visit-'))return false;
  if(form.id==='visit-register'){const access=await api(scope('commercial/preregister',fields.organizationId),{method:'POST',body:fields});clearCache();clients=await allData('clients');await accessResult(access);}
  if(form.id==='visit-followup-form'){await api(scope('followups',form.dataset.org),{method:'POST',body:{customerId:form.dataset.client,sellerId:form.dataset.seller,note:fields.note,nextDate:fields.nextDate||null}});await clientDialog(form.dataset.client);notify('Seguimiento guardado');}
  if(form.id==='visit-assign-form'){await api(scope('clients/assign',form.dataset.org),{method:'POST',body:{id:form.dataset.client,sellerId:fields.sellerId||null}});clearCache();clients=await allData('clients');await clientDialog(form.dataset.client);notify('Responsable actualizado');}
  if(form.id==='visit-share-form'){const values=new FormData(form),selected=values.getAll('product'),kind=fields.kind;if(kind==='selection'&&!selected.length)throw Error('Selecciona al menos un producto.');const options=kind==='category'?{categories:[fields.category]}:kind==='selection'?{products:selected,items:selected.map(id=>({productId:id,quantity:Number(fields['qty-'+id])}))}:{};await accessResult(await api(scope('commercial/access',form.dataset.org),{method:'POST',body:{clientId:form.dataset.client,options}}));}
  if(form.id==='visit-handoff'){const salt=crypto.randomUUID(),digest=await hash(salt+fields.pin);sessionStorage.setItem('surtiva.handoff',JSON.stringify({salt,digest}));location.assign('/c/#'+lastAccess.token);}
  return true;
 }
 document.addEventListener('input',e=>{if(['visit-find','visit-product-find'].includes(e.target.id)){const target=e.target.id==='visit-find'?'.visit-client':'.visit-product-select label';document.querySelectorAll(target).forEach(n=>n.hidden=!n.dataset.search.includes(e.target.value.toLowerCase()));}});
 document.addEventListener('change',e=>{if(e.target.id==='visit-share-kind'){document.querySelector('#visit-category-field').hidden=e.target.value!=='category';document.querySelector('#visit-selection-field').hidden=e.target.value!=='selection';}});
 return {page,action,submit};
}
async function hash(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export function handoffLocked(){return !!sessionStorage.getItem('surtiva.handoff');}
export function showHandoffLock(app,onUnlock){app.innerHTML='<main class="handoff-lock"><h1>Volver al vendedor</h1><p>Ingresa el PIN de este dispositivo para volver a tu espacio.</p><form id="unlock-handoff"><label>PIN<input name="pin" type="password" inputmode="numeric" autocomplete="off" required></label><button class="btn primary">Continuar</button><p role="status"></p></form><small>Este PIN protege la presentación en este dispositivo; no reemplaza tu contraseña.</small></main>';app.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const stored=JSON.parse(sessionStorage.getItem('surtiva.handoff'));if(await hash(stored.salt+new FormData(e.target).get('pin'))!==stored.digest){e.target.querySelector('[role=status]').textContent='PIN incorrecto';return;}sessionStorage.removeItem('surtiva.handoff');onUnlock();});}
